### ISSUE TITLE
error in compling OpenFAST in Ubuntu 14.04

### ISSUE THREAD

**Issue by mapengnan** [OpenFAST/openfast#1038]
I'm not familiar with Ubuntu. I'm trying to compile OpenFAST in Ubuntu 14.04 but I got some trouble which could be seen in the picture below. I don't know what's the meaning of undefined reference to 'pthread_create'. Any reply is very grateful. 
![2](https://user-images.githubusercontent.com/101178670/157351244-29269601-6278-43f6-8cda-1395f26768a7.png)

**Comment by andrew-platt** [comment]
Hi @mapengnan,

The error with `pthread` is because the linker is unable to find it (see https://askubuntu.com/questions/453860/unable-to-locate-package-pthread).  You are likely missing some of the necessary packages on your system required to link in the that library.  Since Ubuntu 14.04 is nearly 8 years old and support for it ended in 2019, it may be difficult to install the package at this point (I'm not sure the `apt` repositories are still available).  You may want to  consider upgrading to a more recent version of Ubuntu.

Regards,
Andy

**Comment by mapengnan** [comment]
Dear andrew,
Thank you for your reply in time. Maybe I should install the package using the apt. Thanks again.

Best wishes,
Pengnan

**Comment by mapengnan** [comment]
Dear all,
I'm trying to compile OpenFAST in Ubuntu 14.04. The error indicates"a version of GNU GFortran greater than 4.6.0 is required but CMake could not detect your GFortran version". However, GNU Fortran 4.8.4 was installed in this system. I'm lost. Any reply is very grateful.
![3](https://user-images.githubusercontent.com/101178670/157397698-305c880e-715b-43f1-aabd-a5d9e876fe58.png)

**Comment by rafmudaf** [comment]
FYI you can also install OpenFAST with [conda](https://docs.conda.io/en/latest/miniconda.html):
```bash
conda install openfast
```

**Comment by rafmudaf** [comment]
@mapengnan have you resolved this issue?
