### ISSUE TITLE
User-defined wind and user-defined waves

### ISSUE THREAD

**Issue by SudharsanKalidoss** [OpenFAST/openfast#1100]
Hi all,

    I want to introduce my own set of wind and wave elevation data with respect to time. In OpenFAST documentation, I found that there is an option for user-defined profiles but detailed instructions are not available. I need to provide different wind and wave profiles are different instances of time. For example, for a simulation of 300s, the first 100s will be running with a wind speed of 12 m/s, wave ht 3m and 10s then next 100s wind speed 22m/s, wave ht 6m and 16s followed by wind speed 12 m/s, wave ht 3m and 10s. I don't want to start the simulation from a previous data file. My question is, Is it possible to run all the three conditions simultaneously  in a single run? If so, assuming user-defined functions is the option, How it can be done?

Thanks

**Comment by jjonkman** [comment]
Dear @SudharsanKalidoss,

Regarding the wind, if you are OK using wind that is uniform across the rotor (rather than using full-field turbulence), the uniform wind data file format supported by InflowWind (`WindType` = 2) can be used to specify wind that is time varying with wind speed steps at various times.

Regarding the waves, HydroDyn supports a user-specified wave elevation time series option (`WaveMod` = 5), which presumably can be used to model different regular wave trains in sequence.  But I'd be concerned that aliasing may be introduced through the FFT method used if the specified wave elevation time series is not continuous when you switch from one regular wave train to another.

Best regards,

**Comment by SudharsanKalidoss** [comment]
Thank you @jjonkman.
