### ISSUE TITLE
Screen show error when i run the OPENFAST

### ISSUE THREAD

**Issue by L-Ethan** [OpenFAST/openfast#1134]
Hi everyone, I'm very new user of OpenFAST and a first year doctoral student.
When i run the openfast, the screen show en error,like this
![image](https://user-images.githubusercontent.com/104621769/169322637-18346952-c160-4742-93c6-1c32d6ef42c8.png)
it means: Unable to continue executing code because mkl_sequential.2.dll could not be found, a reinstallation may resolve the problem.
In the case folder,i copy three program in it, Command Prompt.exe  +  MAP_x64.dll  + openfast_x64.exe, like this
![9U}UGA7VSRSDZK5~L9DF@JX](https://user-images.githubusercontent.com/104621769/169323126-2ddd81fb-48dc-426a-adb4-b773160b46ac.png)
My computer is win11, and i use the OPENFAST 3.0.0.
I don't know what is mkl_sequential.2.dll. I try to find this program in my computer but failed. So I can't solve the problem.
I hope there are people who have encountered this problem can help answer it. Thank you very much!

**Comment by L-Ethan** [comment]
Dear @bjonkman 
Sorry for the late reply. I attended the course of professional English writing this morning, which was very interesting but a little difficult for me~~
I have already compile OpenFAST with VS2019 + oneApi2022. 
Do these version match the OPENFAST3.0?
![image](https://user-images.githubusercontent.com/104621769/169451836-52d833c8-fe23-4e01-a211-00870947e189.png)
![image](https://user-images.githubusercontent.com/104621769/169451917-931a5877-5e89-46b4-bbcb-d03a42d16446.png)
1, I also compile the DISCON DLL. I change the Scheme configuration to Release and x64. 
![image](https://user-images.githubusercontent.com/104621769/169452142-38e0a5c1-bce1-4332-9c7d-b2a0b41aec08.png)
![image](https://user-images.githubusercontent.com/104621769/169452295-d9ef6909-b5f0-47f1-8a6d-3f95ce71b996.png)
And then E:\OpenFAST3.0\openfast-3.0.0\openfast-3.0.0\reg_tests\r-test\glue-codes\openfast\5MW_Baseline\ServoData  generat these programs.
![image](https://user-images.githubusercontent.com/104621769/169452441-e70425b5-9a5f-4729-8d79-f4dada972a14.png)
2, Next i compile the FAST, i change the configuration both for the "FAST" and "FASTlib"
![image](https://user-images.githubusercontent.com/104621769/169452921-83197894-fa3d-4a43-8425-23b75ce345ec.png)
Then the E:\OpenFAST3.0\openfast-3.0.0\openfast-3.0.0\build\bin generate these programs.
![image](https://user-images.githubusercontent.com/104621769/169452974-3d70cc87-f4d3-4143-886f-a05f483ef715.png)
3, Finally i copy these two program and CMD.exe to the case folder
![image](https://user-images.githubusercontent.com/104621769/169453128-66e49303-2910-46a6-afd0-829650d1eb16.png)
![image](https://user-images.githubusercontent.com/104621769/169453388-37b1faed-ba6e-4133-b227-7a424f49e558.png)

Am I doing everything right? Is there a problem with the installed software version?

**Comment by L-Ethan** [comment]
Dear @bjonkman 
I download OpenFAST3.1 from a Bilibili (like youtube) video tutorial blogger today. Then I copy "openFast_x64.exe" from his folder into my folder and did the calculation. And then it work successfully. As you said, I made a mistake in the compilation process of FAST. So is there something wrong with the process I'm operating above? Or maybe there's something wrong with my software version?
Tomorrow is the weekend, so have a nice weekend in advance.
(By the way, today is May 20, and 520 means "I love you" in Chinese homonym~.)

**Comment by bjonkman** [comment]
@L-Ethan, When you changed the `Runtime Libraries` to `Debug Multithread DLL`, you told the compiler to link with dynamic libraries (instead of static ones). This means when you run OpenFAST_x64.exe, it will need to have access to the compiler's runtime DLLs. You can still use this executable, but you'd have to make sure the command prompt you are using knows where the DLLs are located. This is where you would want to run from the Intel environment: `Start -> Intel <Compiler Version> -> Compiler <version> environment`.

You should not need to change those Runtime libraries when you build OpenFAST in Release mode. For Release mode, I would recommend using the `Multithreaded` option:
![image](https://user-images.githubusercontent.com/6108781/169843756-dab9e7c1-0f42-4fd8-96fe-2208893a50f5.png)

Also, if you aren't changing any code, you can download pre-compiled binaries from the OpenFAST Releases page: https://github.com/OpenFAST/openfast/releases. The `Assets` section of each tagged release contains binaries that you can use.

**Comment by L-Ethan** [comment]
Dear @bjonkman
I have been able to run it.
Thanks all.
Best regard.
