### ISSUE TITLE
Run WP_Baseline  using  Fast.Farm

### ISSUE THREAD

**Issue by robytian** [OpenFAST/openfast#1147]
Dear all,
            I used fast. Farm to build a wind farm model composed of **9 WP1.5MW wind turbines**. When I wanted to change the **Angle** of inflow wind to **90 or other angles**, the following errors occurred.
![1655101262268(1)](https://user-images.githubusercontent.com/86820784/173291892-32af68bf-eeb2-4256-bdba-ee1a686255a2.jpg)
            I set **4m/s** steady wind in **InflowWind**, **PropagationDir** to 90, I don't know if this is correct. But I didn't get an error running a single wind turbine using OpenFast.

**Comment by robytian** [comment]
The case I use are **WP_Baseline** and **WP_VSP_ECD**. Does it have a suitable controller to use?

**Comment by jjonkman** [comment]
Dear @robytian,

Presumably because you've set `PropagationDir` to 90 deg, you've also set the nacelle-yaw angle of the wind turbines close to -90 deg in each OpenFAST model; is that correct?  (Otherwise I would expect that you'd receive this error.)  Can you clarify how long into the simulation you receive these errors and what the nacelle-yaw angles of the wind turbines are?

The controller provided with the OpenFAST models of the WindPACT 1.5-MW baseline turbine provided in the OpenFAST r-test use the sample user-defined pitch controller developed by Craig Hansen (`PCMode` = 3, implemented in _PitchCntrl_ACH.f90_) and the simple variable-speed torque controller (`VSContrl` = 1).  This pitch controller is not compatible with FAST.Farm because of the use of SAVEd variables implemented within the _PitchCntrl_ACH.f90_ source file while multiple instances of OpenFAST are used by FAST.Farm.  You'll have to change this controller if you want to make use of the WindPACT 1.5-MW baseline turbine in FAST.Farm, e.g,, by switching to ROSCO: https://github.com/NREL/ROSCO.

Best regards,

**Comment by robytian** [comment]
> Dear @robytian,
> 
> Presumably because you've set `PropagationDir` to 90 deg, you've also set the nacelle-yaw angle of the wind turbines close to -90 deg in each OpenFAST model; is that correct? (Otherwise I would expect that you'd receive this error.) Can you clarify how long into the simulation you receive these errors and what the nacelle-yaw angles of the wind turbines are?
> 
> The controller provided with the OpenFAST models of the WindPACT 1.5-MW baseline turbine provided in the OpenFAST r-test use the sample user-defined pitch controller developed by Craig Hansen (`PCMode` = 3, implemented in _PitchCntrl_ACH.f90_) and the simple variable-speed torque controller (`VSContrl` = 1). This pitch controller is not compatible with FAST.Farm because of the use of SAVEd variables implemented within the _PitchCntrl_ACH.f90_ source file while multiple instances of OpenFAST are used by FAST.Farm. You'll have to change this controller if you want to make use of the WindPACT 1.5-MW baseline turbine in FAST.Farm, e.g,, by switching to ROSCO: https://github.com/NREL/ROSCO.
> 
> Best regards,

This error occurred when I was just running.In addition, I would like to ask where to see or set the yaw Angle of each turbine?

**Comment by jjonkman** [comment]
Dear @robytian,

Here are my answers to your questions:
1) Assuming you've not changes this, the OpenFAST models of the WindPACT 1.5-MW baseline wind turbine have been released with the nacelle-yaw degree of freedom disabled (`YawDOF` = False).  As such, to change the yaw angle, all you have to do is set the initial yaw angle, `NacYaw` in ElastoDyn, equal to the desired yaw angle, which will remain fixed throughout the simulation.
2) If you have not changed `NacYaw` when setting `PropagationDir` = 90 deg or 270, the nacelle-yaw error will be 90 degrees; hence the error.  To align the rotor with the inflow, you should use `NacYaw` = -90 deg for `PropagationDir` = 90 deg and `NacYaw` = 90 deg for `PropagationDir` = 270 deg.  Please note that your figure uses the incorrect orientation of PropagationDir.  A PropagationDir of 90 deg will come from above and 270 deg will come from below in your figure because the wind direction in InflowWind follows meteorological convention (positive rotation about the negative Z axis).

Best regards,

**Comment by robytian** [comment]
> Dear @robytian,
> 
> Here are my answers to your questions:
> 
> 1. Assuming you've not changes this, the OpenFAST models of the WindPACT 1.5-MW baseline wind turbine have been released with the nacelle-yaw degree of freedom disabled (`YawDOF` = False).  As such, to change the yaw angle, all you have to do is set the initial yaw angle, `NacYaw` in ElastoDyn, equal to the desired yaw angle, which will remain fixed throughout the simulation.
> 2. If you have not changed `NacYaw` when setting `PropagationDir` = 90 deg or 270, the nacelle-yaw error will be 90 degrees; hence the error.  To align the rotor with the inflow, you should use `NacYaw` = -90 deg for `PropagationDir` = 90 deg and `NacYaw` = 90 deg for `PropagationDir` = 270 deg.  Please note that your figure uses the incorrect orientation of PropagationDir.  A PropagationDir of 90 deg will come from above and 270 deg will come from below in your figure because the wind direction in InflowWind follows meteorological convention (positive rotation about the negative Z axis).
> 
> Best regards,

As you said, I changed the elastoDyn **yaw DOF to False**, **initial Nacyaw degree to 90**，PropagationDir in Inflowwind was set to 90. The following error still occurred
![image](https://user-images.githubusercontent.com/86820784/173714492-f3bfcc34-864b-43aa-930f-b12a5403c47b.png)

**Comment by robytian** [comment]
> Dear @robytian,
> 
> Here are my answers to your questions:
> 
> 1. Assuming you've not changes this, the OpenFAST models of the WindPACT 1.5-MW baseline wind turbine have been released with the nacelle-yaw degree of freedom disabled (`YawDOF` = False).  As such, to change the yaw angle, all you have to do is set the initial yaw angle, `NacYaw` in ElastoDyn, equal to the desired yaw angle, which will remain fixed throughout the simulation.
> 2. If you have not changed `NacYaw` when setting `PropagationDir` = 90 deg or 270, the nacelle-yaw error will be 90 degrees; hence the error.  To align the rotor with the inflow, you should use `NacYaw` = -90 deg for `PropagationDir` = 90 deg and `NacYaw` = 90 deg for `PropagationDir` = 270 deg.  Please note that your figure uses the incorrect orientation of PropagationDir.  A PropagationDir of 90 deg will come from above and 270 deg will come from below in your figure because the wind direction in InflowWind follows meteorological convention (positive rotation about the negative Z axis).
> 
> Best regards,

**YawDOF=False, PropagationDir=90°, NacYaw = -90** as you said, it can run successfully. Thank you again for your patience.
