### ISSUE TITLE
Bug in How HydroDyn Sorts the Hydrodynamic Coefficients for Strip-Theory Members

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#12]
The member-based hydrodynamic coefficients in HydroDyn do not appear to be sorted correctly when they are specified top-down instead of bottom-up.  This bug was reported in the following forum topic: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1636.

**Comment by ebranlard** [comment]
I confirm the bug with the version of HydroDyn in OpenFAST v2.0.0 ( 0769598a17e19b3ccd00a85cde389995f55024a8 )

This bug occurs when the "MEMBERS" are defined such that MJointID1 is a joint above MJointID2. The "MEMBER-BASED HYDRODYNAMIC COEFFICIENTS" defined by the users for each JointID are not respected by OpenFAST.

Three unit test cases are enclosed:
- "Ref": member with first node below the second node
- "Rev": member with first node above the second node, the hydro coeffs are reversed accordingly
- "RefBug": member with first node below the second one, but hydro coeffs are not reversed.

NOTE: all cases outputs at positions 0.1 0.5 and 0.9 along the member. When the members are reversed in direction, outputs at 0.1 needs to be compared with 0.9 and vice-versa.

As it is:
- The results from "Rev" and "Ref" do not match, revealing the bug.
- The results from "Rev" and "RefBug" match, revealing that the hydro coeffs are indeed not swaped correctly.

After the bug is fixed, the results from "Rev" and "Ref" should match (comparing outputs at 0.1 of one cases with the outputs at 0.9 of the other, and vice versa, and outputs at 0.5)

[Issue12.zip](https://github.com/OpenFAST/openfast/files/2761110/Issue12.zip)
