### ISSUE TITLE
How to use the Standalone HydroDyn

### ISSUE THREAD

**Issue by L-Ethan** [OpenFAST/openfast#1221]
Hi, i want  to use the standalone HydroDyn to get the wave's results.  I have download the  HD_v2.05.00.exe, and expanded archive into  my folder. But when i run it from the DOS command prompt, i get an error messages：
![1660740147986](https://user-images.githubusercontent.com/104621769/185129891-4ea7646d-b5ad-418f-85a5-a1d1cbc52e12.jpg)
![image](https://user-images.githubusercontent.com/104621769/185130315-e25430c4-d08d-4952-90da-9140ef740828.png)
![image](https://user-images.githubusercontent.com/104621769/185130508-4566391f-99be-454e-b3d4-f439628e75cb.png)
Would you mind to tell me  how to solve this error?
Thanks!

**Comment by bjonkman** [comment]
There may be an issue with how this version of the HydroDyn driver parses relative paths. It probably thinks the paths are relative to where you are running the code, not relative to the Test_001.dvr file location. I would try to either (1) cd into your `C:\Users\user\Desktop\FJTJ\wave\HydroDyn\CertTest` directory and run the code from there or (2) change the `HDInputFile` parameter to be the full file location instead of a relative file location (i.e., `C:\Users\user\Desktop\FJTJ\wave\HydroDyn\CertTest\Test_001.dat`. The `OutRootName` probably has the same issue.

**Comment by L-Ethan** [comment]
Hi ,thank you very much for your reply. I have obtained the calculation result according to your first suggestion.
