### ISSUE TITLE
About the output of motion with 6 degrees of freedom

### ISSUE THREAD

**Issue by yk202208** [OpenFAST/openfast#1247]
At which point is the output of the 6-DOF motion?
Can I change the height at which I want to output the movement in the settings?
I want to output the motion of the FOWT center of gravity position.

**Comment by jjonkman** [comment]
Dear @yk202208,

Presumably you are referring to the 6-DOF motion output by the ElastoDyn module; is that correct?  The 6-DOF motion output from ElastoDyn is expressed relative to the platform reference point defined by ElastoDyn input `PtfmRefzt`.

Best regards,

**Comment by HYFOAM** [comment]
Dear @jjonkman 

     I am doing a simulation of a 5MW OC4Semi. I would like to know if there is a way to make the platform perform single degree of freedom motion. For example only Pitch, Sway motion of the platform is performed.

Best regards,

**Comment by jjonkman** [comment]
Dear @HYFOAMm

Yes, you can enable/disable each platform DOF individually through the DEGREES OF FREEDOM flags in the ElastoDyn primary input file, e.g., setting PtfmSgDOF = FALSE disables the surge DOF.

Best regards,

**Comment by HYFOAM** [comment]
Dear @jjonkman 

Thank you for your reply, in fact I am using sowfa-openfast to study the mechanism of the effect of platform motion (single DOF motion) on the wake and unit load of a floating wind turbine. In order to make the effect single, I want to make the platform move in a certain degree of freedom with a certain regularity.

(1) Is there any good way to achieve this regular motion of the platform?
(2) In fact, this kind of similar research already exists, but it is not the same as the method I used. Do you have any better ideas or suggestions for my research direction?

Best regards,

**Comment by HYFOAM** [comment]
Dear @jjonkman

Thank you for your reply, in fact I am using sowfa-openfast to study the mechanism of the effect of platform motion (single DOF motion) on the wake and unit load of a floating wind turbine. In order to make the effect single, I want to make the platform move in a certain degree of freedom with a certain regularity.

(1) Is there any good way to achieve this regular motion of the platform?
(2) In fact, this kind of similar research already exists, but it is not the same as the method I used. Do you have any better ideas or suggestions for my research direction?

Best regards,

**Comment by jjonkman** [comment]
Dear @HYFOAM,

Regarding (1), similar questions have been discussed both here in OpenFAST issues (e.g., see:  https://github.com/OpenFAST/openfast/issues/617) and on our forum (e.g., see: https://forums.nrel.gov/t/control-for-scaled-down-5mw-nrel/1087/14?u=jason.jonkman).

I'm not sure I understand your second question.

Best regards,

**Comment by HYFOAM** [comment]
Dear @jjonkman

Thank you for your answer to the first question, I have understood how to do it.

The second question I would like to ask is, NREL has done a lot of work on the SOWFA-OpenFAST coupling calculation, what other innovations do you have for the SOWFA-OpenFAST coupling calculation of FOWT wake and load? For example, what conditions should I calculate, or what aspects should I analyze in depth. 

Thank you very much for your answer!

Best regards,

**Comment by HYFOAM** [comment]
Dear @jjonkman

Thank you for your answer to the first question, I have understood how to do it.

The second question I would like to ask is, NREL has done a lot of work on the SOWFA-OpenFAST coupling calculation, what other innovations do you have for the SOWFA-OpenFAST coupling calculation of FOWT wake and load? For example, what conditions should I calculate, or what aspects should I analyze in depth.

Thank you very much for your answer!

Best regards,

**Comment by jjonkman** [comment]
Dear @HYFOAM,

I would say there has certainly been some good high-fidelity modeling work done on the impact of FOWT motion on rotor aeordynamics and wakes, but there is much more to do for large flexible rotors, different floater configurations, and FOWT wind farm arrangements.  HFM results need to cover the wide space of designs and conditions, be validated against measured data, used to inform improvements to engineering models, and applied to advance the design of FOWT and wind farms,

Best regards,

**Comment by HYFOAM** [comment]
Dear @jjonkman
      Thank you for your reply! I will carefully consider these things you have mentioned.

Best regards,
