### ISSUE TITLE
OpenFAST MHK error

### ISSUE THREAD

**Issue by SondreT** [OpenFAST/openfast#1257]
Hello,
I am working on an MHK project and want to compare experimental results with numerical programming in OpenFAST.
But I get this error when I try to run OpenFAST initially:
![mhk](https://user-images.githubusercontent.com/114136653/191680426-14b1e5b6-a04f-461e-927e-d356f416fdd1.png)

Isn't MHK implemented in the code yet? Appreciate any help!

Best regards
Sondre

**Comment by jjonkman** [comment]
Dear @SondreT,

My understanding is that the `MHK` switch must currently be set to 0 because important functionality relevant to MHK turbines, such as buoyancy in the blades (see: https://github.com/OpenFAST/openfast/pull/957, scheduled for release in OpenFAST v3.3), is still under development.

Best regards,

**Comment by SondreT** [comment]
@jjonkman thank you very much for your help.
Best regards
Sondre
