### ISSUE TITLE
InflowWind scalemethod

### ISSUE THREAD

**Issue by Sam-Ramsahoye** [OpenFAST/openfast#1262]
Hello,

Am I correct in thinking that TurbSim .bts files are ignored by the InflowWind scaling parameters for turbulence section? Are there any plans to allow them to be scaled in the future? I'm running OpenFAST v3.1. 

Best,
Sam

**Comment by bjonkman** [comment]
The scaling parameters section in InflowWind is used only for for HAWC-formatted data files (WindType=5).

Scaling full-field turbulence files is valid only if the wind that is contained in the files was generated with a uniform standard deviation. While this is true for (most of?) the IEC turbulence models, this is not a valid assumption for some other models. The .bts files contain their scaling parameters inside the file, based on how the turbulence was originally generated. As far as I know, there are no plans to change how that is scaled in the future.

If you would like to scale FF turbulence inside of InflowWind, you could generate either HAWC (WrHAWCFF=true) or Bladed-style (WrBLFF=true) files in TurbSim. In that case, you should also set the shear and flow angles to 0 in TurbSim so that the scaling works as you intended. You'd need to add any shear and wind direction separately in InflowWind. (In TurbSim, set WindProfileType = "PL", PLExp=0, VFlowAng=0, HFlowAng=0, and use an IEC turbulence model.)

If you choose the Bladed-style output format (WrBLFF=true) in TurbSim, you should use WindType = 7 in InflowWind so you can add the scaling.
