### ISSUE TITLE
ERROR OpenFAST: Nodal output not found

### ISSUE THREAD

**Issue by SaeedHAMB** [OpenFAST/openfast#1288]
Dear Jonkman,  
i am trying to visualise floating wind Turbine with ParaView. wenn i run open fast in order to get the VTK files i get the following error
![image](https://user-images.githubusercontent.com/115216664/196069115-268033c3-0350-450e-b6f9-b7be34d48fac.png)

could you help me with? 

this what i modifide in the Inputs Data 
![image](https://user-images.githubusercontent.com/115216664/196069396-ed3bd87d-b41d-4edb-a5fd-c0fddfb4d39f.png)

![image](https://user-images.githubusercontent.com/115216664/196069488-8c973c73-1e62-4a0a-8095-1a98e6da2970.png)

where can i find something about repeated Troubleshooting?  
 
i am using  OpenFAST V3.2.0 

thank you for your patience

**Comment by bjonkman** [comment]
I don't see your actual error message is. The screenshot ends before it prints any errors. 

I don't see anything unusual in your input file settings, but you are outputting surfaces, which require some additional information in AeroDyn. Maybe you could output basic meshes instead of surfaces (use VTK_type=2) and see if that helps. But it's hard to tell without the actual error message.

I think most of the information on VTK visualization for OpenFAST is in the [FAST8 ReadMe document](https://raw.githubusercontent.com/OpenFAST/openfast/dev/docs/OtherSupporting/FAST8_README.pdf), starting on page 33.

**Comment by SaeedHAMB** [comment]
that is the Error what i get. (FATAL ERROR) 
![image](https://user-images.githubusercontent.com/115216664/196240529-a0bd1274-cc28-4497-9ad0-203093cf045b.png)

**Comment by SaeedHAMB** [comment]
an all vtp files have a "DebugError" as you see below 
![image](https://user-images.githubusercontent.com/115216664/196243530-7a5ba8cf-8c2d-4145-a0f4-525f9e3bc14e.png)

**Comment by jjonkman** [comment]
Dear @SaeedHAMB,

The actual error is that the controller, _DISCON_OC3Hywind.dll_ cannot be loaded.  Does this file exist in the directory specified in your ServoDyn input file?

When you have visualization enabled, but OpenFAST aborts due to an error, ".DebugError" is appended to the visualization filenames.  These can sometimes be useful to debug errors when they are associated with turbine geometry.  But in your case, OpenFAST is aborting because it can't find the controller DLL you've selected.

Best regards,

**Comment by SaeedHAMB** [comment]
Dear @jjonkman , 
 _DISCON_OC3Hywind.dll_ should be at _"../5MW_Baseline/ServoData/DISCON_OC3Hywind.dll"_ an i have take a look there and found the folder _DISCON_OC3_with the contents: 
![image](https://user-images.githubusercontent.com/115216664/196253406-3082dc3c-4a77-4377-99a2-3e8d5d6706e3.png)

should i copy the folder _5MW_Baseline_ to my current order ?

**Comment by SaeedHAMB** [comment]
you are genius it functions. i hope i learned more how to trapshooting
thanks a lot
