### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Sunwannasleep** [OpenFAST/openfast#1290]
Hello
1. I found that the generator in OPENFAST is a doubly fed induction generator (DFIG) because it has a gearbox.I wonder how to change the generator to a permanent magnet synchronous generator (PMSG)？
2. I can't find the output current and voltage in the excel file ‘_OutList_’ .
Thanks for your help!

**Comment by jjonkman** [comment]
Dear @Sunwannasleep,

The simple torque control and generator models available in the ServoDyn module of OpenFAST are given as torque-speed relationships, rather than supporting detailed physics of the electrical drive.  Voltages and currents are only modeled directly in the (also simplified) Thevenin-Equivalent Induction Generator model (`VSContrl` = 0, `GenModel` = 2).  Alternatively, you can implement your own detailed electrical drive model by using one of the user-defined options.

FYI: The following NREL report may be of interest to you: https://www.nrel.gov/docs/fy14osti/59195.pdf.

Best regards,

**Comment by Sunwannasleep** [comment]
Thanks a lot, and I will read the docs carefully.
By the way, is there useful  data of 5MW PMSG (such as stator resistance, reactance and flux linkage) in NREL?

**Comment by jjonkman** [comment]
Dear @Sunwannasleep,

I'm not aware of the existence of such data.  That said, I'm not an expert on the electrical drive.

Best regards,
