### ISSUE TITLE
Unsuccessful Compilation of FAST_SFunc.mexmaci64 Using M1 CPU Mac

### ISSUE THREAD

**Issue by Melancho7ee** [OpenFAST/openfast#1308]
**Bug description**
I tried to compile the "FAST_SFunc.mexmaci64" file in my M1 mac (arm based), in order to run simulation using OpenFAST+Simulink. Former settings have succeeded, but when I ran the create_FAST_SFunc.m, I got the following error information.

```
>> create_FAST_SFunc

----------------------------
Creating /usr/local/lib/FAST_SFunc.mexmaci64

使用 'Xcode with Clang' 编译。 (P.S. by me: This sentence means: Compile with 'Xcode with Clang')
In file included from /Users/melancholee/OpenFAST/glue-codes/simulink/src/FAST_SFunc.c:476:
/Applications/MATLAB_R2019a/MATLAB_R2019a.app/simulink/include/simulink.c:1922:15: warning: 'sprintf' will always overflow; destination buffer has size 200, but format string expands to at least 224 [-Wfortify-source]
        (void)sprintf(errmsg,
              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:47:3: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
  ^
1 warning generated.

错误使用 mex (P.S. by me: This sentence means: Wrong use of mex)
ld: warning: ignoring file /usr/local/lib/libopenfastlib.a, building for macOS-x86_64 but attempting
to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_FAST_AllocateTurbines", referenced from:
      _mdlInitializeSizes in FAST_SFunc.o
  "_FAST_DeallocateTurbines", referenced from:
      _mexFunction in FAST_SFunc.o
      _mdlUpdate in FAST_SFunc.o
      _mdlTerminate in FAST_SFunc.o
      _checkError in FAST_SFunc.o
  "_FAST_End", referenced from:
      _mexFunction in FAST_SFunc.o
      _mdlUpdate in FAST_SFunc.o
      _mdlTerminate in FAST_SFunc.o
      _checkError in FAST_SFunc.o
  "_FAST_Sizes", referenced from:
      _mdlInitializeSizes in FAST_SFunc.o
  "_FAST_Start", referenced from:
      _mexFunction in FAST_SFunc.o
      _mdlStart in FAST_SFunc.o
      _mdlOutputs in FAST_SFunc.o
  "_FAST_Update", referenced from:
      _mdlUpdate in FAST_SFunc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


出错 create_FAST_SFunc (line 64) (P.S. by me: This sentence means: error occurred in create_FAST_SFunc (line 64) )
mex('-largeArrayDims', ...
```

I asked a user with intel cpu mac, and he has helped me get over with former problems and finally we got stuck at this error. He did not encouter this error when running create_FAST_SFunc.m with intel cpu mac. So I am wondering if it is possible for a M1 cpu mac to compile FAST_SFunc.mexmaci64 successfully? Because I noticed this message above
```
ld: warning: ignoring file /usr/local/lib/libopenfastlib.a, building for macOS-x86_64 but attempting 
to link with file built for macOS-arm64
```
P.S. I am not very familiar with the compilation of mex files. Most of the compilation work are done according to the user guide and with the help of the aforementioned kind person. Many thanks for your help! :-)

 Some of the software versions I am using are as follows:
**OpenFAST Version** v3.0.0
**MATLAB Version** r2019a
**System Information** OS: macOS Ventura 13.0

**Comment by ZHIXINFENG** [comment]
I got the same problem, did you solve it?

Best regards

**Comment by ZHIXINFENG** [comment]
Hi, I think the problem is the file derived by Make is with the MacOS-arm64 architecture. But the current 'mex' function in Matlab is with x86-64 architecture. And it is difficult to solve this problem because the gfortran is not able to generate the x86-64 file in our computer.

Notsure if we can use a x86-64 file generated by an Itel core MacBook Pro, since I have no access to that kind of MBP.

**Comment by Melancho7ee** [comment]
I haved made it to compile openfast in a M1 CPU macbook last time, but failed to run create_FAST_SFunc.m to get the mexmaci64. Later, I used another Macbook to do the same, however, I failed in the 'make' procedure in my terminal.

error this time:

ld: warning: ignoring file /Applications/MATLAB_R2022b.app/bin/maci64/libmex.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64


<img width="585" alt="CleanShot 2023-01-02 at 22 24 29@2x" src="https://user-images.githubusercontent.com/116873649/210244365-613f4070-144f-4d55-b39c-357395761912.png">

I am just confused about it. Why I succeeded compilation last time but failed this time? And how to solve the problem?

**Comment by deslaughter** [comment]
@Melancho7ee, I was able to reproduce the compilation issue described in your previous post. This is indeed caused by compiling OpenFAST with a macOS-arm64 compiler and trying to link against the Matlab library which is macOS-x86_64 (Intel architecture). There are two possible solutions: 1) use a x86_64 compiler on the M1 mac to match the Matlab architecture or 2) use an arm native version of Matlab.

I recommend option 2 because a beta version of Matlab has been released for Apple Silicon at https://www.mathworks.com/support/apple-silicon-r2022b-beta-conf.html. Since the software is in beta, it is free to try and does not require activation. It will probably also run faster on the M1 Mac than the x86_64 Matlab.

After installing Matlab 2022b Beta, I was able to build and link the Simulink module for OpenFAST. I also tested with the `Run_OpenLoop.m` example. I needed to add the following flags when running CMake to specify where Matlab and it's libraries are located:

`-DMatlab_ROOT_DIR=/Applications/MATLAB_R2022b_beta.app`
`-DMatlab_MEX_LIBRARY=/Applications/MATLAB_R2022b_beta.app/bin/maca64/libmex.dylib`

Please let me know if this works for you.

**Comment by Melancho7ee** [comment]
@deslaughter Great! I succeeded getting the "FAST_SFunc.mexmaca64" file following your advice. And I also tested the `Run_Openloop.m` as well as running a Simulink simulation in Matlab/Simulink. However, both will lead to the breakdown of MATLAB (as soon as I started simulation, the matlab would just crash). I was confused about why this happened. From my view, what I understood is that when we get the OpenFAST by cmake, it is the newest version by fault. and the `mex` file also matches the newest version of OpenFAST. But my current files were built in OpenFAST v3.0.0, so I am not quite sure whether this affects my Matlab' breakdown.
Many thanks to your kind help and look forward to your reply. :-)

**Comment by deslaughter** [comment]
@Melancho7ee, I'm terribly sorry that I didn't see your response. You can check out a specific version of OpenFAST to compile using git. First clone all of the tags with `git fetch --all --tags`. Then do `git checkout tags/v3.0.0` to checkout v3.0.0. Rebuild everything using CMake and you will have an executable that is compatible with your input files.

**Comment by Melancho7ee** [comment]
> @Melancho7ee, I'm terribly sorry that I didn't see your response. You can check out a specific version of OpenFAST to compile using git. First clone all of the tags with `git fetch --all --tags`. Then do `git checkout tags/v3.0.0` to checkout v3.0.0. Rebuild everything using CMake and you will have an executable that is compatible with your input files.

Thanks for your help! I will try it later and respond the result to you

**Comment by ZHIXINFENG** [comment]
> @Melancho7ee, I was able to reproduce the compilation issue described in your previous post. This is indeed caused by compiling OpenFAST with a macOS-arm64 compiler and trying to link against the Matlab library which is macOS-x86_64 (Intel architecture). There are two possible solutions: 1) use a x86_64 compiler on the M1 mac to match the Matlab architecture or 2) use an arm native version of Matlab.
> 
> I recommend option 2 because a beta version of Matlab has been released for Apple Silicon at https://www.mathworks.com/support/apple-silicon-r2022b-beta-conf.html. Since the software is in beta, it is free to try and does not require activation. It will probably also run faster on the M1 Mac than the x86_64 Matlab.
> 
> After installing Matlab 2022b Beta, I was able to build and link the Simulink module for OpenFAST. I also tested with the `Run_OpenLoop.m` example. I needed to add the following flags when running CMake to specify where Matlab and it's libraries are located:
> 
> `-DMatlab_ROOT_DIR=/Applications/MATLAB_R2022b_beta.app` `-DMatlab_MEX_LIBRARY=/Applications/MATLAB_R2022b_beta.app/bin/maca64/libmex.dylib`
> 
> Please let me know if this works for you.

Hi @deslaughter , I am confused on where to specify the Matlab and its libraries when running CMake.   Do you mean add these two line while generating the S-function in Matlab?

Thanks a lot in advance!

**Comment by deslaughter** [comment]
@ZHIXINFENG, the error message is saying that the MEX file can't find the openfastlib shared library (.dylib). This is a difficult problem, which should be resolved in our upcoming 3.5.0 release of OpenFAST. However, you may be able to get it working by following https://www.mathworks.com/matlabcentral/answers/359497-best-way-to-locate-shared-dylib-libraries-used-by-matlab-mex-files-on-macos-x. 

The first thing I would try is symlinking `libopenfastlib.dylib` into `/usr/lib/` via `ln -s /Users/zf/Documents/FAST/OpenFAST/openfast-main/build/glue-codes/openfast/libopenfastlib.dylib /usr/lib/libopenfastlib.dylib` (check that those paths are right first). Shared libraries are complicated on macs and they contain references to their directories, rpath, so moving the dylib file probably won't work.

Let me know if it still doesn't work and I'll look into it some more. As for lines specifying the location of Matlab when running CMake, it would look like:

`cmake -DMatlab_ROOT_DIR=/Applications/MATLAB_R2022b_beta.app -DMatlab_MEX_LIBRARY=/Applications/MATLAB_R2022b_beta.app/bin/maca64/libmex.dylib ..`

But, since you were able to build the MEX file, CMake must have found Matlab without the additional info.

**Comment by Melancho7ee** [comment]
It’s been a long time until we finally made it!
With MATLAB R2023b Prerelease and OpenFAST v3.5.0, I succeeded in generating "FAST_SFunc.mexmaca64" in my M1-chip MacBook. And the Simulink+OpenFAST finally run with no error.
Many Thanks for your help! @deslaughter 
![untitled](https://github.com/OpenFAST/openfast/assets/116873649/d4536629-e904-4b99-a451-b39a353d0414)

**Comment by andrew-platt** [comment]
@Melancho7ee, the MATLAB 2023b prerelease was the key to getting it working?

**Comment by Melancho7ee** [comment]
> 

Yes, I think so. If one wants to produce the "FAST_SFunc.mexmaca64" file, an Apple-Silicon-Native version Matlab is required. And the newest MATLAB 2023b is the first MATLAB that is native for Apple Silicon (M1 and M2).

**Comment by Melancho7ee** [comment]
> @Melancho7ee, the MATLAB 2023b prerelease was the key to getting it working?
Yes, I think so. If one wants to produce the "FAST_SFunc.mexmaca64" file, an Apple-Silicon-Native version Matlab is required. And the newest MATLAB 2023b is the first MATLAB that is native for Apple Silicon (M1 and M2).
In earlier times, I tried old versions of matlab such as 2019 and 2022, but failed. Since they can only generate "FAST_SFunc.mexmaci64". NOTE the i64 means it is for intel chips based MacBook.

**Comment by Melancho7ee** [comment]
> @Melancho7ee, the MATLAB 2023b prerelease was the key to getting it working?

Yes, I think so. If one wants to produce the "FAST_SFunc.mexmaca64" file, an Apple-Silicon-Native version Matlab is required. And the newest MATLAB 2023b is the first MATLAB that is native for Apple Silicon (M1 and M2).
In earlier times, I tried old versions of matlab such as 2019 and 2022, but failed. Since they can only generate "FAST_SFunc.mexmaci64". NOTE the i64 means it is for intel chips based MacBook.

**Comment by Melancho7ee** [comment]
Since the problem is successfully solved, I would like to close this issue. Thanks for all your reply and help. :-)
