### ISSUE TITLE
OLAF outputs the induced velocity field of the wake

### ISSUE THREAD

**Issue by robytian** [OpenFAST/openfast#1374]
Dear all,

1.I want to calculate the result as a standard spiral helix of the wake,What parameters do I need to modify to make tip vortices and root vortices behave completely? (use uniform wind)
![helix](https://user-images.githubusercontent.com/86820784/206991495-504c9991-d12b-421b-84b3-a7734adcb6f3.png)
2.Based on question 1, I think it is possible that the WAKE EXTENT AND DISCRETIZATION in the Helix_OLAF file is related to the WAKE REGULARIZATIONS AND DIFFUSION. 

3.In addition, WakeLength is set to 900 by default, so the total wake is calculated by multiplying DT by 900 in the fst file?

If I want to get a wake velocity field with 10 times the rotor diameter, am I modifying WakeLength?

4.The fourth question is also related to the above. I did not find the relevant parameters of output wake velocity field. I want to achieve the velocity field in the plane from 1 times of rotor diameter to 10 times of distance from the hub, just like the Y-Z plane of the output of Fast.Farm. Or the velocity at the hub along the X axis at different rotor diameters.

Thanks all,
Best wishes,

**Comment by ebranlard** [comment]
Hi,

I would recommend that you have a look at the guidelines for OLAF 

https://openfast.readthedocs.io/en/dev/source/user/aerodyn-olaf/RunningOLAF.html

These guidelines apply to the latest dev version. The dev version renamed some variables and introduced one extra parameter (nNWPanelsFree).

1. Can you clarify what you mean by behave completely? the Helical wake example has no rollup, no distortion of the wake, it’s a pure helix, because it’s using a large value of FreeWakeStart
2. Regularization and wake length are not related. The parameter may increase with downstream distance when using “age” as a regularization method. 
3. Yes that is correct. The guidelines will help answer your question, but you do need to account for the wind speed. 
4. the grid outputs of Olaf might do what you want. You can check the documentation for these outputs on readthedocs. 
I hope some of it will help!
