### ISSUE TITLE
Setting 3 wave directions

### ISSUE THREAD

**Issue by BukalNUS** [OpenFAST/openfast#1389]
I set the number of wave directions to 3, but how do i find out in which direction are the waves in such as coming towards the floating offshore wind turbine from which direction?

**Comment by jjonkman** [comment]
It seems like I answered a very similar question from you yesterday: https://github.com/OpenFAST/openfast/issues/1388.

FYI -- Rather than opening up a new issue for each of your questions, it would be better to start an OpenFAST Discussion (https://github.com/OpenFAST/openfast/issues/1388) or move such questions to our user forum (https://forums.nrel.gov/).  OpenFAST Issues is meant for questions related to bugs, feature requests, compiling, etc.
