### ISSUE TITLE
Running the OpenFAST.exe compiling from source code

### ISSUE THREAD

**Issue by YangLeiTH** [OpenFAST/openfast#1412]
Dear,

After completing to compile from OpenFAST v3.0 source code using VS2017+fortran, I run the executable file(openfast_x64.exe), however, the system reminded me that it can not find the mkl_sequential.dll file. Then I compared the executable file(openfast_x64.exe) compiling from source code and downloading from github release, they are indeed different in size, the fomer is 31MB, the latter is 55.2MB. I wonder if there are setting errors before building the solution?

Best regards,
YangLei

**Comment by bjonkman** [comment]
If you build OpenFAST using cmake on Windows using Visual Studio, it links with dynamic libraries. You will need to run the executable it generates from the Intel compiler command prompt (which sets the path to find those libraries). You can find this command prompt under `Start -> Intel <Compiler Name> -> Compiler <version> for Intel x64 Visual Studio 2017 environment`.

The executables in the GitHub release assets are built using the Visual Studio solution file, which builds with static libraries. When you use static libraries, they are built into the final executable, so you won't need to find .dlls on your system to run the code.

Both executables should give the same results.

**Comment by YangLeiTH** [comment]
Dear @bjonkman,

I added the mkl_sequential.dll file to the system environment, the OpenFAST_x64.exe can be run this time. However, after running the HydroDyn, it abort as follow.

![image](https://user-images.githubusercontent.com/119639841/213383922-ce7eb08c-9dd7-46cc-b5fa-5e9114507e86.png)
Does it means that I must add some other dynamic libraries to the system environment such as KERNELBASE.dll?

I rebuilt the the Visual Studio solution with static libraries setting as follows. 
![1674114653374](https://user-images.githubusercontent.com/119639841/213384885-1b7a3ef5-714a-4b72-9470-c83acd90dce1.png)

But it reported an error as follows.
![1674114760572](https://user-images.githubusercontent.com/119639841/213385236-e22f6d55-328a-4318-a064-b9de9993a830.png)

It seems the solution can only built successfully using dynamic libraries. If there are some mistakes with setting in VS?

**Comment by bjonkman** [comment]
If you change the runtime library settings in the Visual Studio solution file, you must make sure ALL of the projects that are being linked into that executable use the same settings. It looks like you have changed the FAST project to use debug libraries in its `Release` configuration (instead of `Multithreaded`, your project says `Debug Multithreaded`).  I would suggest you change that library back to its original state and use the `Debug` configuration of the solution instead of changing the libraries for `Release` configuration. If, however, there is some reason you need to change one of the libraries, you must change `FAST`, `FASTLib`, _and_ `MAP_dll` projects to use the same kinds of libraries.

The crash you show when using the dynamic library executable looks like it could be a problem with the source code. If it didn't have the correct libraries, it would fail to run at all, so that is not the issue. Which version of the code did you build? And, did you make any changes to it before building?

**Comment by YangLeiTH** [comment]
Dear @bjonkman 

I redownload the source code and build the solutions successfully using static libraries. The executable(openfast_x64.exe) can be run normally. I will build it using static libraries latter. My question has been solved. Thank you!

Best regards,
YangLei
