### ISSUE TITLE
wind turbine power calculation

### ISSUE THREAD

**Issue by Chen-cl97** [OpenFAST/openfast#1424]
Hi，
Why the power coefficients have  negative numbers by BEM calculation, and this phenomenon is particularly obvious in the calculation of floating wind turbine.
Besides, I can not find wake deflection for a yaw wind turbine by OLAF, even though the yaw degree is 30°. This is why and how to set the parameter in OLAF.dat?  
Thanks!

**Comment by ebranlard** [comment]
Hi @Chen-cl97, you can try to set your OLAF inputs according to the guidelines, and see if that helps:
https://openfast.readthedocs.io/en/dev/source/user/aerodyn-olaf/RunningOLAF.html#guidelines

With regards to yaw, you can check the output  `NacYaw` from OpenFAST, `RtSkew` from AeroDyn. At first it's best to run simulations with the YawDOF set to False in ElastoDyn. If you set it to True, make sure the YawNeut in ServoDyn is also set to 30 deg otherwise the yaw spring will bring the nacelle back to 0 degree.
