### ISSUE TITLE
Questions about HydroData

### ISSUE THREAD

**Issue by YangLeiTH** [OpenFAST/openfast#1471]
I found that the .hst file of spar, semi, tlp in the HydroData folder is a little strange. The hydrostatic restoring stiffness of roll and pith, i.e. k44, k55 is less than zero. Does it mean that the center of mass is higher than the center of buoyancy, which contributing to decreased restoring stiffness, even contributing a lot more than the second order moment of water area? If so, the platform can't stand the disturbance? Even a liittle disturbance will cause the platform collapse without a mooring system?

I wonder how the hydroData generated? For example, for a spar type FOWT, Which value is the center of mass of whole system set in WAMIT?

**Comment by jjonkman** [comment]
Dear @YangLeiTH,

These data are correct.  The hydrostatic restoring included in the WAMIT data should only account for buoyancy effects, not the contribution of system mass/weight, which is otherwise accounted for in the structural modules of OpenFAST and should not be double counted.  For more explanation, see my post dated April 10, 2012 in the following topic on our forum: https://forums.nrel.gov/t/about-wamit-model-for-5mw-oc3-hywind/482.

Best regards,

**Comment by YangLeiTH** [comment]
Dear @jjonkman 

Thank you! It help a lot.

Best regards,
