### ISSUE TITLE
About the generation of BTS and WND files in the FAST INFLOWIND document.

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#1495]
Hello everyone, 
I am considering generating a BTS wind speed file with the features of an overall increasing trend with fluctuations up and down, as shown in the figure following:
![image](https://user-images.githubusercontent.com/56157328/225844350-be3a87af-24db-4c3f-a20e-4d4a8e51d6f8.png)
Additionally, I would like to know how to extract information from an Excel file with wind speed changing over time and convert it into a WND file.

**Comment by shipors** [comment]
I have tried to copy wind speed and time data from an Excel file into a WND file and input it into FAST, but I did not get a SUM file. How can I solve this problem?

**Comment by ebranlard** [comment]
Hi @shipors, 
The easiest in your case would be to generate a regular BTS file using TurbSim, and then add a linear slope to it using the python toolbox. You can see examples of how to manipulate a BTS file here: 
https://github.com/OpenFAST/python-toolbox/blob/main/pyFAST/input_output/examples/Example_TurbSimBox.py
You would have to adapt line 104, to add a linear slope instead of adding a constant. 

If you want to generate a TurbSim box from a given time series, you need to use a constrained time series in TurbSim, with `TurbModel = "TIMESR"` and specifying a `UserFile`. You can refer to the TurbSim manual for more info on the method and its limitations. I'm enclosing a example of input file to this post. You can find a more advanced example [here](https://openfast.readthedocs.io/en/dev/source/user/turbsim/appendix.html#turbsim-input-files).

You could also write a .WND file and use it directly in InflowWind (not TurbSim), using `WindType=2` to prescribe a uniform field that varies with time. But prescribing a turbulent time series in this manner is unphysical. I'm enclosing an example o WND file for a wind step. 

I hope that helps. 

[TS_dt0.05_example.txt](https://github.com/OpenFAST/openfast/files/11002753/TS_dt0.05_example.txt)


[WindStep_Example.txt](https://github.com/OpenFAST/openfast/files/11002877/WindStep_Example.txt)

**Comment by jjonkman** [comment]
Dear @shipors,

I would just add to what @ebranlard said about the unphysical nature of modifying a TurbSim output to include time-varying mean wind speed.  Even if the TurbSim wind data is changed so that the wind profile changes as a function of time, the use of this wind data within OpenFAST would be approximate. This is because OpenFAST's InflowWind module creates a 4D wind field (3 spatial + time) from the 3D TurbSim-generated wind field (2 spatial + time) using Taylor’s frozen turbulence assumption, i.e., the planes of 2D wind are propagated at a given fixed mean wind speed and direction, the wind speed of which is the parameter stored in the TurbSim output. It would be difficult to make this value time varying.

This topic has been discussed several times on our forum, e.g., see: https://forums.nrel.gov/t/stitch-together-turbsim-timeseries/2245.

Best regards,

**Comment by shipors** [comment]
Dear @ebranlard,

Thank you for your recent help and support. Your advice and suggestions have been incredibly valuable. My question has been answered.

Best wishes!

**Comment by shipors** [comment]
Dear @ebranlard,

Thank you for your recent help and support. Your advice and suggestions have been incredibly valuable. My question has been answered.

Best wishes!

**Comment by shipors** [comment]
Dear @jjonkman,

I just made the modifications to the WND file as ebranlard suggested, and that was enough for me. Your advice has taught me a lot. Thank you for your support and assistance.

Sincerely,
