### ISSUE TITLE
About how ad_VerticalAxis_OLAF is calculated and parameterized

### ISSUE THREAD

**Issue by engineerYuXN** [OpenFAST/openfast#1508]
Dear all
@ebranlard @jjonkman
I have some questions I would like to ask you about the r-test/modules/aerodyn/ad_VerticalAxis_OLAF
1.How should I calculate this model directly using aerodyn？
2.The relevant parameters of the tag in the following figure, such as the environment parameters, can modify the labeled area according to the requirements？
![image](https://user-images.githubusercontent.com/87838413/228790242-176a4957-e7d2-4e8f-9733-b9d4622b1e35.png)
3.Where can I find literature or reports about the model
4.Is it possible to visualize the aerodynamic calculations of the model by means of post-processing software？
5.If I want to compare this model with my CFD calculations, do you have some  suggestions?
6.How should I determine the model parameters in that module？
Since I have no previous relevant experience, my question may not be very good, I hope you can give relevant advice.

Thank you so much!

**Comment by jjonkman** [comment]
Dear @engineerYuXN,

Have you already reviewed the AeroDyn and OLAF documentation?  If not, I would start there as I would expect that to answer most of your questions:
https://openfast.readthedocs.io/en/main/source/user/aerodyn/index.html#
https://openfast.readthedocs.io/en/main/source/user/aerodyn-olaf/index.html

Our related journal paper may also be insightful for you: https://wes.copernicus.org/articles/7/455/2022/.

Best regards,

**Comment by engineerYuXN** [comment]
Dear developer, I have encountered the following problem when running ad_VerticalAxis_OLAF, and I don't know how to solve it
<img width="641" alt="微信截图_20230408201543" src="https://user-images.githubusercontent.com/87838413/230720604-a66b8604-2f33-41d3-940e-4c758af4d54f.png">

**Comment by ebranlard** [comment]
Dear @engineerYuXN 

It looks like you are using an old executable for the aerodyn driver, and you are calling that executable with an AeroDyn file. You would need to compile your own driver executable and call the executable using an aerodyn driver input file (diffrent from an AeroDyn file). You can find more information about the compilation and the driver input file here: 
       https://openfast.readthedocs.io/en/dev/source/user/aerodyn/driver.html
If you use the `main` branch of the OpenFAST repository to compile, make sure you use example files from the `r-test` repository that are also in the `main` to ensure  that the inputs are compatible with the executable. 
I hope that helps!

**Comment by engineerYuXN** [comment]
> 

Thank you for answering my question
I have another small question about OutListParameters

I selected the output parameters in OutListParameters, but in the calculation results, the output was all zero. I don't know where the problem occurred
<img width="1159" alt="2" src="https://user-images.githubusercontent.com/87838413/231627500-2b1992d1-2bfb-4443-bdac-3731ddf25ac6.png">


<img width="1216" alt="1" src="https://user-images.githubusercontent.com/87838413/231627505-661d5456-c35c-41ee-880b-0d73ddeff98d.png">

**Comment by jjonkman** [comment]
Dear @engineerYuXN,

I'm not sure I can answer your questions, but here are a few responses:
1. To better understand your problem setup, can you share your full AeroDyn input file?  What wind conditions are you simulating?
2. Can you clarify the level of differences you are seeing or share a plot?  Do both results have the same units?
3. I'm not sure I understand your question.

Best regards,

**Comment by engineerYuXN** [comment]
Thanks for your reply @jjonkman
1.I'm doing a simulation with steady wind, and here are the relevant settings for my aerodyn input file

<img width="1276" alt="1" src="https://user-images.githubusercontent.com/87838413/231929642-cf5db93e-e6bc-434f-82a0-4b456bb8b2a9.png">
<img width="1275" alt="2" src="https://user-images.githubusercontent.com/87838413/231929660-622838d0-ec2e-422c-a372-68434bd9d8a2.png">
2.Since I am currently unable to determine the wind wheel parameters of VAWT, I still need to confirm this issue
3.I would like to consult whether to change the blade extension and chord length (blue line) by changing the parameters in the AD_blade.dat, and if I want to change the diameter of the wind wheel to change the ad_driver relative position of the blade in .dvr (red line), I don't know if the above idea is correct. If not, please tell me where I should modify the blade spread, chord length and rotor diameter

<img width="1256" alt="4" src="https://user-images.githubusercontent.com/87838413/231930992-7d98f8da-dc99-48c8-b99e-0019a37a05f5.png">
<img width="1172" alt="3" src="https://user-images.githubusercontent.com/87838413/231931165-50fa1850-8887-4b4a-846f-d99724e9ac68.png">
Thank you very much

**Comment by ebranlard** [comment]
Hi @engineerYuXN 

When using vertical axis turbine  (`HAWTProjection=False`), AeroDyn doesn't know the rotor area or typical radius, which is why the Rotor area, tip speed ratio, power coefficient, thrust coefficients, etc. are zero. You'll have to compute these quantities from your own knowledge of the geometry and using quantities such as RtAeroPwr, RtAeroMxg or RtAeroMxh. 

You can use VTK outputs (`WrVTK`) to double check your change of geometry. 

I would recommend looking at the aerodyn driver documentation and the sketch therein to get familiar with the coordinate systems. This can help you set up the geometry of the turbine. If you want the blades to be further away from the tower, you'll have to change the coordinate of the origin of the blades in the hub coordinate system (`BldOrigin_h`).

To generate turbulent wind that approximatively matches the ones from a CFD calculation you'll want to find the average shear profile, power spectrum, and coherence in your CFD simulation, and try to set the TurbSim inputs so that they approximate these values in a stastisical sense. You can also constraint the turbulence box (using `TurbModel=TIMESR`) to match some time series from CFD at given points.  

If you have the flow field from CFD (without wind turbine disturbances), you can extract the flow field at a given plane of your CFD simulation for all time steps, and write it into the BTS format using pyFAST (you can start with this [example ](https://github.com/OpenFAST/python-toolbox/blob/dev/pyFAST/input_output/examples/Example_TurbSimBox.py) to get familiar with it)
 
I hope that helps. 

Emmanuel

**Comment by shipors** [comment]
@engineerYuXN 可以加个联系方式交流下吗？

**Comment by engineerYuXN** [comment]
> @engineerYuXN 可以加个联系方式交流下吗？

你好，你可以把你的微信发到我的邮箱中，我来加你（我的邮箱：yuxiaonan@hrbeu.edu.cn)
