### ISSUE TITLE
NaN from AD15 if no inflow

### ISSUE THREAD

**Issue by andrew-platt** [OpenFAST/openfast#1564]
**Bug description**
In the branch for PR #1008, if inflow is set to none but AD15 left on, NaN's appear in the AD15 output.

I'm putting this issue here so that we remember to look at it when we merge PR #1008.  Best guess at the moment is something went wrong in a merge at some point.

Reported by @luwang00

**Comment by bjonkman** [comment]
Do you have an example set of input files where this was an issue? I ran a case just now with CompInflow=0 and CompAero=2 and didn't have this issue.

**Comment by luwang00** [comment]
I did some further experimentation with the [OC4 Jacket from r-test](https://github.com/luwang00/r-test/tree/f/SeaState_ConstrWave_Compare/glue-codes/openfast/5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth). It looks like NaNs start to appear if `CompInflow=0` and the initial `RotSpeed=0` in ElastoDyn. I also tried `WakeMod=0` and `AFAeroMod=1` typical for idling rotors, and I'm still getting NaNs.

**Comment by bjonkman** [comment]
I think this should be fixed with https://github.com/OpenFAST/openfast/pull/1567. This is a bug fix that I fixed a while ago and should have sent to @ebranlard before that merge (sorry!). Also, due to some IT issues today, I haven't been able to check if that PR solves the issue @luwang00 reported, but that's where my debugger triggered an error earlier today, so this solves at least *part* of the issue.

**Comment by andrew-platt** [comment]
Just tested with 3.5.0 and this appears to be fixed.
