### ISSUE TITLE
running OpenFAST with turbines as fans/propellers

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#1572]
Hello OpenFAST team,

I am curious - - Is there a way we could run the OpenFAST wind turbines as propellers or fans by setting the generators behave as motors somehow?

Best,
Tanmoy

**Comment by jjonkman** [comment]
Dear @tchatte3,

Yes, OpenFAST can function during motoring conditions, e.g., for simulating turbine start-up scenarios.   The aerodynamics should be well captured by OpenFAST, but you'll need to set up a controller or generator model that functions in the motoring condition.

Best regards,

**Comment by jjonkman** [comment]
Dear @tchatte3,

I could be wrong, but I'm not aware that ROSCO has control options for turbine motoring, start-up, or sustained propeller mode.

If Cp is defined as the amount of wind power available in ambient wind that is converted to useful mechanical power, I would think Cp would be negative for a propeller, because for a propeller, you are putting mechanical power in to generate wind.

Best regards

**Comment by tchatte3** [comment]
@jjonkman ,

Thank you. Sorry , If I am confusing you on question (2), but apart from the sign -- ideally Cp magnitude could be same just from the aero and structural principles even for a propeller. For a real design scenario however, Cp = 0.5 say for turbine. For a propeller or fan , ideally Co could be - 0.5. But, in reality, do you have any insight what the Cp for FAN would be I am guessing cp- fan = - 0.48 or maybe - 0.45. Or could it be smaller??

**Comment by jjonkman** [comment]
Dear @tchatte3,

Betz limit does not apply to a propeller.   From a quick Google search, I see that propellers can operate at higher efficiencies, up to 90%.

Bet regards,

**Comment by tchatte3** [comment]
Thanks, @jjonkman -- makes sense.
