### ISSUE TITLE
How to achieve power reserve control strategies？

### ISSUE THREAD

**Issue by lidongh123** [OpenFAST/openfast#1574]
I am trying to implement a derating method of the 5MW_Land_BD_DLL_WTurb using Simullink.For now, I am just working on the second region to test my  controller , at a free steady wind speed of 9m/s.I want to changing the powe control law to make the speed to deviate from optimal.
The power  reserve control strategy is：
![%8$W8HH95~B}K@G42%Q CB4](https://github.com/OpenFAST/openfast/assets/91535351/15565655-1525-4bb4-870d-dc94c9364835)
The Common power  control strategy is：
![{@DI2DICQHVZSN@B(KYM`F7](https://github.com/OpenFAST/openfast/assets/91535351/c23eb18e-2ec4-4b09-bcd0-2bad29fc4cf7)
X is the generator speed.Y is the generator output power.
However, I encountered some problems : under the two control strategies, the generator speed did increase, but the generator output power almost did not change.
 I hope to be able to get your guidance on this issue and what might be causing it.
Best regards,

**Comment by dzalkind** [comment]
Hi, 

It looks like you're trying to change the torque = k\omega^2 law to change the power output.

By decreasing the torque, you're going to end up at a higher generator speed, but about the same power because you have only changed the aerodynamic efficiency (Cp) by a small amount when moving the TSR to a suboptimal location on the Cp surface.

To better reduce the power in Region 2, you can change the aerodynamic efficiency via blade pitch.  I wrote a paper on this topic that might be helpful.  Section 5 of [this article](https://onlinelibrary.wiley.com/doi/full/10.1002/we.2705) describes the approach I used.

Best, Dan

**Comment by lidongh123** [comment]
Dear @dzalkind ,

Thank you for your reply. All of my doubts have been addressed.

Best regards.
