### ISSUE TITLE
How to get detailed model for standard semi 5MW floating wind turbine

### ISSUE THREAD

**Issue by YangLeiTH** [OpenFAST/openfast#1575]
Dear all,

I want to work on the structural analysis for FOWT platform(combined with FEM software and hydrodynamic software). While I am confused that there are no detailed model for FOWT, so that I can not analyze the structural problem. I wander if NREL have provided the detailed model about standard semi 5MW FOWT(including the internal structure of platform)?

Best regards,

**Comment by jjonkman** [comment]
Dear @YangLeiTH,

When both SubDyn and HydroDyn are enabled, OpenFAST can consider the floating substructure as a flexible structure, including hydroelastic effects for calculating internal member-level loads, where the structure is represented as series of structural elements like beam, cable, or rigid link interconnected by joints like cantilevered, pin, universal or ball.  So, the member-level loads that can be calculated including forces and moments at each cross section of the structure.  Detailed structural analysis in terms of hydrodynamic pressure distributions and stress and strain of structural details beyond those listed above are not directly considered in OpenFAST.

That said, NREL is in discussion with other developers regarding adding interfaces to OpenFAST so that the detailed structural calculations could be calculated in the future.

Best regards,

**Comment by YangLeiTH** [comment]
Dear @jjonkman 

As we known, some commercial software like Homer can have already solved the detailed structural calculation. However, as for stress and strain of structural details, it need to master the detailed drawing of structure, instead of series of structural elements. I wander how you find the detailed drawing of structure if you want to calculate the stress and strain of structural details. Or the detailed drawing of standard semi 5MW floating wind turbine can be public?

Best regards,

**Comment by jjonkman** [comment]
Dear @YangLeiTH,

I'm not aware of public information containing detailed structural drawings of the DeepCwind semisubmersible supporting the NREL 5-MW baseline wind turbine or for similar reference floating substructure models.  You'll may need to develop these yourself based on your own assumptions about the structural details.

Best regards,

**Comment by YangLeiTH** [comment]
Rear @jjonkman 

Thank you very much!

Best regards,
