### ISSUE TITLE
The effect of areodynamic imbalance

### ISSUE THREAD

**Issue by Wangzhenyu12** [OpenFAST/openfast#1645]
Hello, everyone!

I want to study the effect of areodynamic imbalance on clearance. According to the OpenFAST Documentation Section 4.2.1: Aerodynamic imbalances are possible through the use of geometrical differences between each blade.

Then I modify BlCrvAC and BlCrvAng in AeroDyn_blade.dat to set initial bending for blade1 of a 5MW onshore wind turbine, the BlCrvAC of blade tip is about -10m. BlCrvAng are recalculated by the formula.
BlCrvAng(n) = atan ( (BlCrvAC(n+1) - BlCrvAC(n-1) ) / ( BlSpn(n+1) - BlSpn(n-1) )*180/pi.

The AeroDyn_blade.dat of blade1 is shown below.
![image](https://github.com/OpenFAST/openfast/assets/74004322/57adb529-4d09-41e9-8b77-cbf5dd2fafdd)

Then I replace ADBlFile(1) in AeroDyn15.dat and output TipClrnc1,TipClrnc2 and TipClrnc3. I do not use BeamDyn in the calculation.
The raw clearance output data are like sine waves. I only care about the minimum clearance so I pick every lowest point of each cycle from the raw clearance data and draw the minimum clearance figures of every blade. The sampling frequency is same as the rotation frequency for every blade. I think the minimum clearance occurs at the moment when the blade passes the tower according to the definition of TipClrnc.

According to the description of BlCrvAC:upwind turbines have negative BlCrvAC for improved tower clearance. But this is not consistent with my calculation result. The clearance of blade1 has surprisingly become smaller than other two blades. And The clearance difference is very small. The clearance time-series are shown below under mean wind speed 3m/s with IECturbc B. 
![image](https://github.com/OpenFAST/openfast/assets/74004322/be629953-ed8d-4165-b058-40d206acc3f7)

As far as I understand, the clearance of blade1 should be much longer than the other two blades because of the initial bending -10m.
 I also calculate the results under different mean wind speed such as 1m/s and 12m/s, The results are similar.

Please help me to solve this problem. 
Thanks and regards!

**Comment by jjonkman** [comment]
Dear @Wangzhenyu12,

Your approach sounds OK.  I believe the issue is that you are outputting the blade tip-to-tower clearance from ElastoDyn rather than AeroDyn.  `TipClrnc1` is an ElastoDyn output whereas `B1NβClrnc` would be the equivalent output of AeroDyn, where β is a number in the range [1,9], corresponding to entry β in the `BlOutNd` list, which you'd want to set to the node at the tip (= `NumBlNds`).  ElastoDyn output `TipClrnc1` is calculated between the tip node in ElastoDyn and the yaw axis and AeroDyn output `B1NβClrnc` is calculated between the aerodynamic output node β and the tower axis, minus the local tower radius.

When you define the aerodynamic offsets in AeroDyn (`BlCrvAC`, `BlSwpAC`), these define offsets of the aerodynamic center from the pitch axis.  When you use ElastoDyn to model the blades (as opposed to modeling the blades in BeamDyn), the undeflected blade is always straight and lying along the pitch axis (including tip node).  Adding aerodynamic offsets in AeroDyn does not change the shape of the blade in ElastoDyn; rather, it only changes the calculation of the aerodynamic loads and how these loads get mapped to the structural model.

FYI: I would normally expect an aerodynamic imbalance to involve a change in aerodynamic twist, chord, or airfoil data between blades, not necessarily a change in aerodynamic centers.

Best regards,

**Comment by Wangzhenyu12** [comment]
Dear @jjonkman 
Thanks for your quick reply. This answer solved my most doubts.
And I have other questions:

1. As modifying BlCrvAC or BlCrvAng does not change the shape of the blade in ElastoDyn, is it same for modifying BlTwist, BlChord or BlAFID?  
2. Is it correct changing the shape of the blade by modifying  kp_xr, kp_yr, kp_zr and initial_twist in BeamDyn.dat?
3. If the answer of question 2 is "Yes", do I also need to modify aerodynamic offsets in AeroDyn to make aerodynamic center is also changed at the same time?

Thanks and regards!

**Comment by jjonkman** [comment]
Dear @Wangzhenyu12,

My answer is "yes" to questions 1 and 2.  Regarding question 3, the aerodynamic shape of the blade is defined in AeroDyn and the structural shape of the blade is defined in ElastoDyn or BeamDyn.  Adding curvature to the blade in BeamDyn will not automatically add curvature to the blade in AeroDyn.  You should place the structural nodes in BeamDyn where the cross-sectional mass and stiffness matrices are defined and you should place the aerodynamic nodes in AeroDyn where the airfoil polar data are defined.

Best regards,
