### ISSUE TITLE
How to get the tower section torsion stiffness

### ISSUE THREAD

**Issue by Lizhihaosong** [OpenFAST/openfast#1674]
In the Fast User's Guide, It mentions the tower section torsion stiffness, i.e., abbreviation as TwGJStiff. How can I get this data, such as NREL 5MW wind turbine. The fast code file seems to only have tower section side-to-side stiffness (TwSSStif) and tower section fore-aft stiffness (TwFAStif)

**Comment by jjonkman** [comment]
Dear @Lizhihaosong,

The tower torsional stiffness in the structural model of FAST v7 and earlier was only used in the FAST-to-ADAMS preprocessor, not within FAST v7 itself.  The structural model of FAST v7 was transformed into the ElastoDyn module of FAST v8 and OpenFAST.  Because support for the FAST-to-ADAMS preprocessor was dropped, the tower torsional stiffness input to ElastoDyn was eliminated from the tower input file.  If you want to model tower torsion, you must model the tower within SubDyn instead of ElastoDyn.

Best regards,

**Comment by Lizhihaosong** [comment]
Once the size of tower section is given and the elastic modulus or shear modulus, the tower torsional stiffness can be determined.

**Comment by Fandier** [comment]
Dear @jjonkman 
I would like to know if the the tower torsion is taken into account when modelling the structural dynamics of the floating wind turbine in FAST. If it is considered, why is the torsional stiffness not found in the tower input parameters?

**Comment by jjonkman** [comment]
Dear @Fandier,

ElastoDyn does not currently consider tower torsion, although we have plans to add that degree of freedom to ElastoDyn in the future.

If you model the tower within SubDyn rather than ElastoDyn, you can model the tower torsion (within SubDyn).  That said, SubDyn is inherently linear, so, the geometric nonlinearities of the tower that are captured within ElastoDyn are neglected if you model the tower within SubDyn.

Best regards,

**Comment by Fandier** [comment]
Dear @jjonkman
Thanks for you reply. I have another question to ask. I found out that mooring and hydrodynamic forces are taken into account in the calculation of tower modal shapes by Bmode. I would like to know that for a free-free constrained tower, do I need to consider mooring and hydrodynamic forces as well?
![image](https://github.com/OpenFAST/openfast/assets/73537352/70028ff1-8070-4794-ae47-0dcb6bd81cc9)

![image](https://github.com/OpenFAST/openfast/assets/73537352/01243ac6-27f5-4db3-b3ba-e3e5d2a683f5)

**Comment by jjonkman** [comment]
Dear @Fandier,

The tower natural frequencies and mode shapes of a floating offshore wind turbine will be impacted by the tower-base boundary conditions, including floater mass, center of mass, and inertia; hydrodynamic added mass; hydrostatic stiffness; and mooring stiffness.

Best regards,
