### ISSUE TITLE
What is the data structure of 90m_12mps_twr-u.bin

### ISSUE THREAD

**Issue by calcin** [OpenFAST/openfast#1689]
Dear all,

When I used TurbSim to generate the wind field I set WrHAWCFF to True, so I got the three files 90m_12mps_twr-u.bin 90m_12mps_twr-v.bin 90m_12mps_twr-w.bin After I looked up the information and learned that these three files are binary files, I passed the I converted them to decimal by python code, and got a column of data, which is related to the .inp file I set up, the main settings of my .inp are as follows:
--------Turbine/Model Specifications-----------------------
         29 NumGrid_Z - Vertical grid-point matrix dimension
         29 NumGrid_Y - Horizontal grid-point matrix dimension
       0.05 TimeStep - Time step [seconds]
         10 AnalysisTime - Length of analysis time series

The column of data I got has a total of 168200 rows, which is exactly 29*29*200, so I'm guessing that the data should be arranged in a certain way, traversing the entire coordinate points and time points, and now my question is what kind of arrangement is this data in, and I would like to replace it so that I can modify the wind field to my own wind field.
Here is my guess on how this file is laid out, starting from the first data to the last data in order, first in the y direction when the y direction is full of 29 rows after the 2nd z direction continue to row 29 slower until the row is 29 slower, and then continue to row the second time step, the operation is the same as above. This is my guess, I hope to be able to give me this guess to correct the error.
Any help would be appreciated.

**Comment by ebranlard** [comment]
Hi @calcin 
You can find a [python reader for Mann Box]( https://github.com/OpenFAST/python-toolbox/blob/dev/pyFAST/input_output/mannbox_file.py#L89) files here. It is consistent with the ways HAWC2 and OpenFAST reads the Mann boxes. 
   
One of the complication with MannBoxes is that the lateral coordinates goes from Ly/2 to -Ly/2, so the reader flips it back so that the data is in an order that is more conventional. From the top of my head I can't remember the order of the binary storage. 

This python script should help you do what you need: read a file, modify the field (the data structure , and then write it back (see this [documentation example](https://github.com/OpenFAST/python-toolbox/blob/dev/pyFAST/input_output/mannbox_file.py#L37)). 

(For TurbSim, you'll find it a [similar reader here](https://github.com/OpenFAST/python-toolbox/blob/dev/pyFAST/input_output/turbsim_file.py#L61). )

If you have issue using these scripts, feel free to post issues on the python-toolbox repository.

**Comment by calcin** [comment]
Dear @ebranlard ，
Through your tips, I use pyFAST this library, he is very powerful to solve the problem of how to modify the bts file, I have to say that this is a very good library, thank you very much for your help, wish you a happy life!
