### ISSUE TITLE
How to get the input of the Aerodyn standalone module

### ISSUE THREAD

**Issue by YangLeiTH** [OpenFAST/openfast#1755]
Hi @jjonkman, 

I recently came across the updated version of the Aerodyn standalone module, which now requires time series inputs such as rotor speed, yaw, and blade pitch. It seems that these time series are related to the Servodyn module. I am curious to know how I can obtain these time series for a specific example.

Lei Yang

**Comment by jjonkman** [comment]
Dear @YangLeiTH,

The updated version of the standalone driver of AeroDyn does support user-specified time series where you can prescribe the structural motion normally sent to AeroDyn from a structural module when AeroDyn is coupled through OpenFAST.  However, the updated version of the standalone driver of AeroDyn also supports simpler analysis types, e.g., whereby the rotor spins at a constant speed with fixed pitch and fixed yaw and without base motion.

The user-specified time series option is there to support situations where you may want to know what the aerodynamic loads will be if you the wind turbine structure experiences specific transient events.  These time series can be whatever you want, e.g., taken from measurements or made up based on some event you have in mind.  You could derive them from a coupled OpenFAST simulation, but that kind-of defeats the purpose because if you already have the coupled OpenFAST simulation result, you probably wouldn't need to run the standalone AeroDyn driver.

Best regards,

**Comment by YangLeiTH** [comment]
Thank you very much!
