### ISSUE TITLE
5MW_Land_DLL_WTurb: differences between my simulation and reference manual

### ISSUE THREAD

**Issue by falascao** [OpenFAST/openfast#1840]
Hi,
I am currently attempting to replicate the results presented in the 'Definition of a 5-MW Reference Wind Turbine for Offshore System Development,' specifically focusing on the plots found on page 32. My approach involves running OpenFAST simulations using the '5MW_Land_DLL_WTurb' model and visualizing the simulation outputs in MATLAB. However, a notable issue I have encountered pertains to the rated wind speed. The obtained value closely approaches 12 m/s, whereas the manual specifies a rated wind speed of 11.4 m/s.
Attached below are my results:
![WhatsApp Image 2023-10-27 at 11 49 12](https://github.com/OpenFAST/openfast/assets/146757474/20a27ffd-f01e-466d-8600-a295ff8b293c)
![WhatsApp Image 2023-10-27 at 11 50 14](https://github.com/OpenFAST/openfast/assets/146757474/d5528c5a-e8e9-4cde-924e-d64a1cf2a06a)

These come from the manual:

![WhatsApp Image 2023-10-27 at 11 50 50](https://github.com/OpenFAST/openfast/assets/146757474/023be965-32f6-44bc-9674-9a096368eafc)
![WhatsApp Image 2023-10-27 at 12 07 23](https://github.com/OpenFAST/openfast/assets/146757474/152d7730-705b-4db4-b94b-060ee5bebe59)

Could you tell me why the results are different? Is there something in OpenFAST that needs to be configured differently?
Thank you very much for your time in advance.
Best regards

**Comment by jjonkman** [comment]
Dear @falascao,

Your results also don't look like they are quite converged.  Are you running separate simulations at each mean wind speed and recording the steady-state response for each simulation?  Or how are you computing the steady-state response?

Best regards,

**Comment by falascao** [comment]
Dear,
I try both with steady-state and uniform wind but i obtain the same results.
This is the uniforme wind file that i use:
![image](https://github.com/OpenFAST/openfast/assets/146757474/47406fab-df46-4b01-a5ce-f97fab44ef15)
![image](https://github.com/OpenFAST/openfast/assets/146757474/4957d6f4-21ea-4138-99fb-0b5364a8c5a8)

Thanks for your response.
Best regards

**Comment by jjonkman** [comment]
Dear @falascao,

It looks like you are using linear ramp of wind speed with `WindType` = 2.  It will be hard for the wind turbine to reach steady-state with this set up because the turbine response will always lag the wind speed.

Instead, I would suggest running separate simulations at different mean wind speeds with `WindType` = 1 and let the system reach steady-state before recording the solution.

Alternatively, you can use `WindType` = 2 with wind speed steps (e.g., using the _PwrCrvJump.wnd_ file found here: https://drive.google.com/file/d/1E78jP0SDaC3VICgjwNMEv_HZswnpCLKU/view?usp=drive_link), holding each step a long enough time for the solution to reach steady state before stepping to the next wind speed.

Best regards,

**Comment by opendiego** [comment]
Dear @jjonkman 

I'm part of the team with Falascao, and I'd like to express our sincere gratitude for your prompt response and willingness to assist. It's possible that we may not have explained our situation clearly initially. Despite that the plots we provided were conducted under uniform wind conditions, also, we initially performed a steady-state analysis with a wind type parameter set to 1. During this analysis, we recorded various Power values corresponding to different wind speeds used as input parameters.

in this specific scenario, we observed that at the rated wind speed recommended in the reference manual (11.4), we did not achieve the expected rated power output but a lower value. It's possible that we may not have allowed the system to reach a steady-state condition before recording the results. Our simulation duration was limited to 300 seconds. Is it possible that this duration was too short, or could there be an issue that prevented the simulation from achieving a steady state?

Best regard.

**Comment by jjonkman** [comment]
Dear @opendiego,

Just a few comments:

- How similar are your results with `WindType` = 1 and `WindType` = 2?
- It may take a very long time to reach a pure steady state (if it ever does).  But my guess is after the core transients die away, the solution will oscillate a small amount about some mean value.  I would consider this mean value the steady-state solution.
- The original analysis for the NREL 5-MW baseline wind turbine was performed with a much older version of the software.  The AeroDyn module of OpenFAST has been overhauled extensively since then.  I have not recomputed the wind-speed dependent steady-state response recently, but I wouldn't be surprised if the steady-state response has shifted a bit (including a small shift in rated speed) between the original and now.

Best regards,

**Comment by falascao** [comment]
Dear @jjonkman,

we believed that there was a problem in our setup, but if you confirm that the results can be correct, we continue with our work.
thanks again for your answers.
Best regards,

**Comment by jjonkman** [comment]
Dear @falascao,

I agree that your results are likely correct once you ensure that you are properly recording the steady-state solution at each mean wind speed.

Best regards,

**Comment by Didi-X** [comment]
I am using `OpenFAST-3.5.0`. I am running the OpenFAST simulation with "`5MW_Land_DLL_WTurb`" and the wind speed is 11.4m/s. `WindType`=1After stabilizing, my `Genpwr `is 4.77MW. I'm curious why I didn't get to 5MW. I'm curious what Settings to change to get to 5MW. 
I have turned off `FlapDOF1`, 2, and 3 in ElatoDyn because the Genpwr is lower when the simulation is turned on.
@opendiego @falascao I wonder if your problems have been solved

**Comment by Didi-X** [comment]
I found some discussion here, but I don't know which outcome to follow.
> https://forums.nrel.gov/t/nrel-5mw-reference-wt-power-curve/2359

**Comment by Didi-X** [comment]
Yes, I ran the simulation at `CompElast=2`(ElastoDyn + BeamDyn for blades) and I think 11.75m/s is achievable reach rated power.
I want to pay attention to the change of rotor power. Do you know how to output rotor power under` CompElast=2` (it can output normally when `CompElast=1`).

**Comment by Didi-X** [comment]
Yeah, I think it's my problem, I can see it.
Thank you very much.
