### ISSUE TITLE
Mooring line diameter conversion formula in Moordyn.

### ISSUE THREAD

**Issue by LeoHongLiZuo** [OpenFAST/openfast#1842]
Dear guys,
Mooring line diameters in the Moordyn module of Openfast in the UMaineSemi model is 0.333m as show in the below figure.
![图片](https://github.com/OpenFAST/openfast/assets/108517989/ff48f9e8-fdca-423c-8799-cb8212413800)
And in 'Definition of the UMaine’ of ‘nominal diameter’ is 0.185 m as show in the below figure.
![图片](https://github.com/OpenFAST/openfast/assets/108517989/ebaad767-267f-4a5a-a7a2-e6cb4a7297b5)
I didn 't find a specific description of the formula in "MoorDyn User’s Guide".
![图片](https://github.com/OpenFAST/openfast/assets/108517989/fadfd2be-4a61-4ca1-bef0-2fbc7a7019d0)
I 'd like to know the conversion formula between ‘volume equivalent diameter’ in Moordyn and ‘nominal diameter’.
Because the follow-up study may use other mooring line diameter, so I want to ask what is the conversion formula between ‘volume equivalent diameter’ and ‘nominal diameter’.
Best wishes!
Leo

**Comment by andrew-platt** [comment]
@mattEhall  and @RyanDavies19, can you answer this?

**Comment by mattEhall** [comment]
Hi Leo,
MoorDyn doesn't really care about nominal diameter, so that's why this info isn't in the model or its documentation. (I'll also post a link to this related discussion we had: https://github.com/IEAWindTask37/IEA-15-240-RWT/issues/170) Converting between a volume-equivalent diameter and a nominal diameter is really just a conversion related to what reference dimension is used for a mooring line product. It can usually be figured out from product specifications. Because chains are standardized, there should be a certain ratio for studless and studlink chains. For studless, we have been using a value of 1.8, such as found here https://github.com/NREL/MoorPy/blob/master/moorpy/MoorProps_default.yaml#L48
Matt

**Comment by LeoHongLiZuo** [comment]
Dear andrew-platt and mattEhall,
Thanks very much for your patient help and answers !
Best wishes!
Leo
