### ISSUE TITLE
FAST.Farm wind turbinds' speeds do not match wake trends

### ISSUE THREAD

**Issue by Yongbyon** [OpenFAST/openfast#1904]
![image](https://github.com/OpenFAST/openfast/assets/141715638/e73d021e-3f6a-4499-b6e7-bcc759069bba)
![image](https://github.com/OpenFAST/openfast/assets/141715638/50dd63ea-4d1b-41c9-b048-835b4fdadce7)
![e281547e764d9201af0c115cb69274a](https://github.com/OpenFAST/openfast/assets/141715638/9c3a8cc3-6ab9-427f-bb1d-123431e13df0)
The distribution of wind turbines in the wind farm is shown in Fig. 1, and I used smooth winds, and the simulation time is one hour, but the simulation results do not match the wake trend. The wind speed given in the figure is the average wind speed of each turbine in the second half hour, which obviously does not conform to the wake trend, how is it?
Your answers are much appreciated！

**Comment by Yongbyon** [comment]
My current thinking is that it is normal for wind speeds to increase a little and decrease a little in the later units, and by the later units, it is unlikely to be just as harshly decreasing. Because the difference between the free-flow wind speed and the wind speed in the wake area is very large, the energy exchange is more adequate, until the wind speed at the next unit, has basically made up for the wake loss, or even will be higher than when there is no loss. But I don't know if this idea is right, because the third turbine wake wind speed than the second unit is going to be higher, this place do not know how to explain.

**Comment by jjonkman** [comment]
Dear @Yongbyon,

I guess I'm not too surprised by these results.  I've certainly seen before that the 3rd turbine down the row in a wind farm produces more power than the 2nd because the 2nd turbine is heavily waked by the 1st turbine, which means the 2nd turbine will have less mean thrust and a weaker wake than the 1st turbine, which boosts the power of the 3rd turbine.  It seems like an equilibrium across turbines has been achieved for turbines 4-8. The laterally 30-m increasing offset per downstream turbine is also not as common as a test as aligned flow down the row, so, I have less intuition with the offset.

Please note that FAST.Farm is meant for transient dynamic analysis (e.g., with turbulence or gusts).  While you can run with steady, uniform inflow, please note that NREL has other tools (e.g., FLORIS) that are better suited for that application.  Moreover, the wake parameters of FAST.Farm have not been calibrated against data without turbulence, so, improvements to FAST.Farm are likely possible if the wake parameters were to be recalibrated for uniform inflow.

Best regards,

**Comment by Yongbyon** [comment]
Thank you very much for your answer, I'm gradually understanding the principle of it
