### ISSUE TITLE
DWM Driver

### ISSUE THREAD

**Issue by sayerhs** [OpenFAST/openfast#2]
DWM driver contains `USE ifport` which is specific to Intel Fortran Compiler. This code fails to compile with `gfortran`.

**Comment by rafmudaf** [comment]
I've made some fixes to the DWM driver (use ntwc lib for input handling, comment the intel specific library imports because they don't seem to be used).

This can be seen at https://github.com/rafmudaf/openfast/tree/bugfix/dwm_driver

@ghaymanNREL @jjonkman @bjonkman does anyone have an input file for dwm driver?

**Comment by rafmudaf** [comment]
Looks like it should be called:
`
    CHARACTER:: PriFile =  'DWM-driver\wind_farm.txt'
`

**Comment by jjonkman** [comment]
@rafmudaf -- You can find an example wind_farm.txt file in the test directory of the DWM archive on NWTC Information Portal: https://nwtc.nrel.gov/DWM.

That said, I would not spend time working to resolve issues with DWM because--as mentioned in issue #93--we plan to replace DWM with FAST.Farm once it is publicly released.

**Comment by rafmudaf** [comment]
Thanks @jjonkman. Since DWM will be deprecated by FAST.farm, I'll hold off on any further improvements to the DWM driver and leave this issue open for future reference until FAST.farm is released.

**Comment by rafmudaf** [comment]
With @mylonasc's help, the dwm driver compiling bugs have been resolved for linux, mac, and windows. There are some hard coded paths so runtime errors are expected if these aren't updated in the driver source code.

I'm closing this issue since it is related specifically to compiling, and I will not open another issue for runtime problems since DWM will be deprecated per #93. If other issues arise regarding this, please comment on issue #93.
