### ISSUE TITLE
How to calculate the sensitivity of aerodynamic power and thrust to the rotor speed using OpenFAST linearization

### ISSUE THREAD

**Issue by ietqlw** [OpenFAST/openfast#2123]
Dear @jjonkman ,

I tried to obtain the sensitivity of aerodynamic power and thrust to the rotor speed using OpenFAST linearization. But the states only contain the `'ED First time derivative of Variable speed generator DOF (internal DOF index = DOF_GeAz), rad/s'` and `'ED First time derivative of Drivetrain rotational-flexibility DOF (internal DOF index = DOF_DrTr), rad/s'`. Then I can only get the sensitivity of aerodynamic power and thrust to the generator speed. I am not sure whether the sensitivity to rotor speed = the sensitivity to generator speed * gearbox ratio.

With best regards,

liangwen qi

**Comment by jjonkman** [comment]
Dear @ietqlw,

Actually, the degree of freedom (DOF) in ElastoDyn (ED) referred to as the "generator DOF (internal DOF index = DOF_GeAz)" is expressed relative to the low speed shaft, not the high-speed shaft.  We refer to this DOF with the word "generator" because it is on the generator side of the drivetrain torsional spring-damper.  But the speed of the generator is the gearbox ratio (`GBRatio`) times the first derivative of this DOF.   So, the aerodynamic linearization with respect to this DOF is already relative to the low-speed shaft speed, so, there is no reason to multiply by `GBRatio`.

Best regards,

**Comment by ietqlw** [comment]
Dear @jjonkman,

Thank you very much for your kind and clear answer.

With best regards,

liangwen qi
