### ISSUE TITLE
Push docker images to dockerhub & additional images for >3.5.3<4.0 releases

### ISSUE THREAD

**Issue by mayankchetan** [OpenFAST/openfast#2143]
**Is your feature request related to a problem? Please describe.** 

- Availability of OpenFAST docker images on DockerHub
- Release of 3.5.x versions after 4.0 release (long term support for 3.5)

**Describe the solution you'd like**
- Add DockerHub credentials to repo and update GH actions to allow push to DockerHub.
- Add new workflow for releases > 3.5.3 < 4.0 based on current GH actions.

**Describe alternatives you've considered**
- Above solutions are simple to implement.

**Additional context**
[edit by @andrew-platt] This issue is a placeholder so we don't forget about it when we do a 3.5.4 release post 4.0 release.

**Related**
#2124 
#2139 
#2141

**Comment by andrew-platt** [comment]
For the new workflows for releases in the 3.5.x series after releasing a 4.0.0, we will need to remove the `:latest` so that it doesn't overwrite the latest release.

Also note that we many need to consider a `main-3.5.x` branch for such a release, and add some wildcard options into the new workflow to pick up on the `main-*`.  This would allow the same workflow to be used on all future older maintainance releases.

**Comment by andrew-platt** [comment]
We've addressed this with 3.5.5 (mostly -- automated builds don't work on GH due to memory limits).  Closing this as complete.
