### ISSUE TITLE
BeamDyn Standalone Fails to Converge feature

### ISSUE THREAD

**Issue by James-Ilosta** [OpenFAST/openfast#2196]
Hi,

I was wondering if it would be possible to write something into the BeamDyn outfile that would indicate that the simulation had failed to converge, or if it fails for any other reason. As far as I can tell, I only get a message in my terminal. Apologies if this already exists. If it does please could you point me to where the option is and how to set it up?

I am currently running the BeamDyn Driver from OpenFAST 3.5.2

**Comment by jjonkman** [comment]
Dear @James-Ilosta,

The BeamDyn summary file is written at module initialization (when convergence can't be reported) and the time-series output files have a specific format not conducive to messages (that would otherwise "break" post-processors).  That said, you can always save messages written to the terminal to a file if that is what you want.

Best regards,
