### ISSUE TITLE
Improper AeroDyn output channel names

### ISSUE THREAD

**Issue by kshaler** [OpenFAST/openfast#221]
In the documentation at Sections 6.1.5.2 and 6.2.8.2, PDFs are provided that have the names of all AeroDyn and BeamDyn output channel names, respectively.

https://openfast.readthedocs.io/en/master/_images/ad_output_channel.pdf
https://openfast.readthedocs.io/en/master/_images/bd_output_channel.pdf

In both PDFs, some of these channel names have greek letters in them, which isn't valid.

**Comment by jjonkman** [comment]
@kshaler,

This is by design.  The greek letters represent a numerical value within a certain range, as explained in the associated sections of the AeroDyn and BeamDyn documentation:
https://openfast.readthedocs.io/en/master/source/user/aerodyn/appendix.html#aerodyn-list-of-output-channels
https://openfast.readthedocs.io/en/master/source/user/beamdyn/appendix.html#beamdyn-list-of-output-channels

I hope that helps.

Best regards,
