### ISSUE TITLE
The wake of wind turbine is abnormal under dynamic yaw

### ISSUE THREAD

**Issue by zgSong123** [OpenFAST/openfast#2240]
Dear jjonkman,

I hope this email finds you well. I am writing to inquire about a potential issue I encountered while using OpenFAST v3.0.0.

In my simulation, I utilized the UserYawCont module to implement sinusoidal yaw misalignment on the NREL OC4 Semi wind turbine. Upon examining the VTK files and the yaw angle curves generated by the simulation, it appears that the turbine indeed undergoes sinusoidal yaw misalignment as intended. However, I noticed that the wake behavior of the turbine under sinusoidal yaw misalignment remains identical to that of the case without yaw misalignment.
<img width="776" alt="1" src="https://github.com/OpenFAST/openfast/assets/156583319/5de65886-c8a0-40e9-ab93-838a1a4fbd6b">

<img width="776" alt="2" src="https://github.com/OpenFAST/openfast/assets/156583319/0c51ac1a-2750-474f-ba59-f1bb37d6f469">

I am reaching out to seek your insights into this matter. Could you please provide some guidance or suggestions on what might be causing this discrepancy? 

Best regards，

**Comment by jjonkman** [comment]
Dear @zgSong123,

Is the cut-off frequency in the wake evolution model of FAST.Farm (`f_c`) above the frequency of the yaw oscillation?  If not, I could foresee the oscillation being filtered out in the wake calculation of FAST.Farm.

Otherwise, please shore more information on what you are seeing in the FAST.Farm/OpenFAST response beyond the visualization; are you sure there is no differences in the response?

Best regards,

**Comment by zgSong123** [comment]
Dear OpenFAST Developers,

As you mentioned, it appears that I had overlooked this problem all along. Your help has been invaluable, and I truly appreciate it.

Thank you once for your support and guidance.

Best regards,

**Comment by zgSong123** [comment]
Dear jjonkman,

As you mentioned, it appears that I had overlooked this problem all along. Your help has been invaluable, and I truly appreciate it.

Thank you once for your support and guidance.

Best regards,
