### ISSUE TITLE
Is it appropriate to use FAST.Farm version 3.2.0 for conducting fatigue analysis?

### ISSUE THREAD

**Issue by niuyue321** [OpenFAST/openfast#2268]
Dear @jjonkman,

I am using FAST.Farm version 3.2.0 to conduct many simulations with turbulent wind profiles generated by TurbSim, followed by MLife to compare the fatigue loads among different wake conditions for a downstream turbine: fully waked, partially waked, and non-waked. Today, I noticed that in the abstract of your newly published paper, "Development and Verification of an Improved Wake-Added Turbulence Model in FAST.Farm," you mentioned, "Previous studies hypothesized that the lack of WAT modeling was the source of underprediction of fatigue loads, in particular for cases at low turbulence intensities and/or stable atmospheric boundary layers."

I am wondering if it is still appropriate to use FAST.Farm version 3.2.0 for conducting fatigue analysis. What if I only care about the relative differences? If not, has this new model been implemented in the most recent FAST.Farm version 3.5.3? 

Best wishes,
Yue

**Comment by jjonkman** [comment]
Dear @niuyue321,

As stated in that paper, we've noted that FAST.Farm underpredicts fatigue damage of waked wind turbines for cases with low turbulence intensity and/or stable atmospheric boundary layers due to a lack of wake-added turbulence.  To put a number on that, I would say that we've seen FAST.Farm underpredict fatigue damage of waked turbines without wake-added turbulence when the ambient turbulence intensity is less than 10%.  For ambient turbulence intensity higher than 10%, wake-added turbulence is negligible.  So, whether older versions of FAST.Farm are "appropriate", depends on the conditions simulated.

Wake-added turbulence has been added to FAST.Farm through the following PR: https://github.com/OpenFAST/openfast/pull/2202, which will be first released in OpenFAST v4.0.

Best regards,

**Comment by niuyue321** [comment]
Dear @jjonkman,

I see. Thank you very much for your help; I really appreciate it!

Best regards,
Yue
