### ISSUE TITLE
Problem in farm level shared mooring

### ISSUE THREAD

**Issue by DynaStyhAn** [OpenFAST/openfast#2272]
Dear Professor jjonkman,
I am learing SHARED MOORING SYSTEM these days. I successfully run a 2 turbines model, I want to add a share mooring between the two turbines (definitely it is not a reasonable design because I only use it to practice.)I rewrite the single moor dyn and change it to a farm level moor dyn according to docs, it suggested me that 'Unable to find matching line type name for Line 1',but I haved defined the type of line1,I wish you can give me solutions,thanks! 
![屏幕截图 2024-06-19 121602](https://github.com/OpenFAST/openfast/assets/173226451/325b60a9-7ab1-4fc4-b8a6-fae56475be99)
![屏幕截图 2024-06-19 121632](https://github.com/OpenFAST/openfast/assets/173226451/aaf8ddac-49ea-4cfd-b204-3f8b7f388f4d)
![屏幕截图 2024-06-19 121647](https://github.com/OpenFAST/openfast/assets/173226451/08205a2a-2fcf-4e59-901b-f68cf0b13473)
![屏幕截图 2024-06-19 121711](https://github.com/OpenFAST/openfast/assets/173226451/512d1b34-7fdc-42a2-97d7-3d456b9755b8)
![屏幕截图 2024-06-19 122308](https://github.com/OpenFAST/openfast/assets/173226451/94a1857b-ac50-4086-8d8b-a96ba72f82b7)

**Comment by RyanDavies19** [comment]
@DynaStyhAn try formatting your MoorDyn input file according to the MoorDyn version 2 convention (see screenshot below). The docs are not up to date for MoorDyn with FAST.Farm, apologies on our end for that. The screenshot below is from the updated documentation that we are in the process of getting uploaded. The FAST.Farm input file you have looks correct, nothing has changed on that side between MoorDyn version 1 and version 2. 
![Screenshot 2024-06-20 at 9 36 32 AM](https://github.com/OpenFAST/openfast/assets/101124339/7e5739e6-d5dd-410d-8eb4-6b64c243a27d)

**Comment by DynaStyhAn** [comment]
> @DynaStyhAn try formatting your MoorDyn input file according to the MoorDyn version 2 convention (see screenshot below). The docs are not up to date for MoorDyn with FAST.Farm, apologies on our end for that. The screenshot below is from the updated documentation that we are in the process of getting uploaded. The FAST.Farm input file you have looks correct, nothing has changed on that side between MoorDyn version 1 and version 2. ![Screenshot 2024-06-20 at 9 36 32 AM](https://private-user-images.githubusercontent.com/101124339/341474893-7e5739e6-d5dd-410d-8eb4-6b64c243a27d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NDIzNzEsIm5iZiI6MTcxODk0MjA3MSwicGF0aCI6Ii8xMDExMjQzMzkvMzQxNDc0ODkzLTdlNTczOWU2LWQ1ZGQtNDEwZC04ZWI0LTZiNjRjMjQzYTI3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwMzU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWI2MmU1NDEwN2YwZjM4ZTEyOWMyYWI1Y2NhMGJlNTg0NDM3NzEzYzhhMTI0ZTEyOTVhMjIyYTgxNDYzZjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NFQaA-w6rYtz7cSDvkdzUdsylkpmubN1bE4VK4obXdk)

Dear @RyanDavies19,I revised my MoorDyn input file in accordance with your screenshot, unfortunately it showed the same tips I met with last time.I wonder whether  I should also revise the moor dyn input files of the two single turbine.They have same moor dyn input files,and I moved turbine1 378m in the x direction and turbine2 30m in the y direction.Should I use the previous coordinate of two wind turbines in farm-level moor dyn or the coordinate before I moved the two wind turbines?
Best regard!
![屏幕截图 2024-06-21 162614](https://github.com/OpenFAST/openfast/assets/173226451/2acc2afd-45f6-441a-beeb-a8e5acd39d81)

![屏幕截图 2024-06-21 121153](https://github.com/OpenFAST/openfast/assets/173226451/33b8f6d1-cc87-4f80-9eeb-1bc1704f80f4)
![屏幕截图 2024-06-21 121139](https://github.com/OpenFAST/openfast/assets/173226451/f302747e-8725-47e3-a72d-6d114ce8b525)

**Comment by RyanDavies19** [comment]
@DynaStyhAn Two points: First, you need to remove the NLines flag in your shared moorings file (line 25 of the file). This is the reason FAST.Farm is aborting. 

Additionally the position of the points with the turbineN attachment need to be defined relative to the turbines position, while the fixed points are defined in the global frame. In your shared moorings file then you only need to apply your x and y transformations to points 1-3 and 7-9. Points 4-6 and 10-12 should not be changed from your single turbine cases as they define the location of the fairleads from the turbines center.

**Comment by DynaStyhAn** [comment]
> 两点：首先，您需要删除共享系泊文件（文件的第 25 行）中的 NLines 标志。这就是FAST的原因。农场正在中止。
> 
> 此外，需要相对于涡轮机位置定义带有 turbineN 附件的点的位置，而固定点则在全局坐标系中定义。在共享系泊文件中，只需将 x 和 y 变换应用于点 1-3 和 7-9。第 4-6 点和第 10-12 点不应从单个涡轮机壳体中更改，因为它们定义了导缆器与涡轮机中心的位置。

Dear @RyanDavies19~~,I made new progress according to your suggestions, It is extraordinary useful! However,I am so sorry to bother you again because I met new problems.
1.Why Catenary solve of Line 1-7 are unsuccessful?
2.Why it always reminds me 'NaN detected' not only in the process of simulation but also at the end(NaN state detected)
3.Why 'Fairlead tensions did not converge within TMaxIC=60 seconds'and What methods are usually used to solve this kind of problems?
If it's not too much trouble, could you provide me with some guidance on these problems.I would be honored if you could share your thoughts which can help a lot on my project.Words cannot express how grateful I am~~
![屏幕截图 2024-06-22 125143](https://github.com/OpenFAST/openfast/assets/173226451/21a57fe8-187f-4fc0-9ef1-999276a6c127)
![屏幕截图 2024-06-22 125153](https://github.com/OpenFAST/openfast/assets/173226451/ea5d6252-7340-470c-9842-19c7741ec9c7)
![屏幕截图 2024-06-22 125219](https://github.com/OpenFAST/openfast/assets/173226451/2554b333-af3f-4110-92a7-1be1e4dd384b)

**Comment by RyanDavies19** [comment]
@DynaStyhAn with regards to your questions:

1. The catenary solve unsuccessful means that the catenary solver algorithm in MoorDyn failed so the lines are initializing as linear lines between the fairlead and anchor. In order for your system to be in a steady state before applying external dynamics, MoorDyn uses dynamic relaxation to let the line "fall" into place by running MoorDyn with scaled drag coefficients. The parameters that control dynamic relaxation are (from the docs site):
![Screenshot 2024-06-24 at 8 56 26 AM](https://github.com/OpenFAST/openfast/assets/101124339/d335213c-206e-44c5-a8ee-556092653eab)

2. The repeated nan's are because once the system fails there isn't an exit from the loop running the dynamic relaxation. Every error after the first NaN is almost always caused by that first error. 

3. Same as my answer to #2. That specifically means that the system did not reach steady state after 60 seconds of dynamic relaxation runtime.

Now for how to fix these errors: It's hard to say whats going on without seeing your updated input file. However for the simulation to fail in the first time step generally means that there is something wrong with how positions are defined in the MoorDyn input file. In your case something wrong with the position and/or size of line 7. From your set-up you shared before your two turbines are ~380m apart, but the length of line 7 is only 100m. If this is what you have in your current input file, then this will cause MoorDyn to crash. Also using CdScaleIC = 4 could also cause issues with numerical stability. If you fix the line 7 length and still have issues, try reducing CdScaleIC.

**Comment by RyanDavies19** [comment]
FYI MoorDyn + FAST.Farm docs have been updated: https://moordyn.readthedocs.io/en/latest/inputs.html#moordyn-with-fast-farm-inputs

**Comment by DynaStyhAn** [comment]
> FYI MoorDyn + FAST.Farm docs have been updated: https://moordyn.readthedocs.io/en/latest/inputs.html#moordyn-with-fast-farm-inputs

Thanks!Your response is very detailed！ You help me a lot !You're the most kind-hearted person in the world~~
