### ISSUE TITLE
One small problem

### ISSUE THREAD

**Issue by sffgd** [OpenFAST/openfast#2302]
Hello everyone,
     When I process openfast output data, for example: RootMxb1, RootMxb2, RootMxb3.I know that this is the root moment representing the 3 blades, but I don't know the position of the blades corresponding to RootMxb1, RootMxb2, and RootMxb3.
     Thank you！
![微信图片_20240705091513](https://github.com/OpenFAST/openfast/assets/144923930/c8b1a175-6f72-45cd-8129-432fd1deee39)

**Comment by jjonkman** [comment]
Dear @sffgd,

The position of the blades is defined by the rotor azimuth angle, which is an output of ElastoDyn (`Azimuth`) just like `RootMxb1`, etc. are.  ElastoDyn output `Azimuth` reports the azimuth angle of blade 1.  The azimuth angle of the other two blades is 120 or 240 degrees different for 3-bladed rotors.  If you are asking about the ordering of the blades in ElastoDyn, the convention for 3-bladed rotors in ElastoDyn is that blade 3 is ahead of blade 2, which is ahead of blade 1, so that the order of blades passing a through a given azimuth is 3-2-1 repeat.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman,

Thank you for your reply！According to your reply, I have identified the position and azimuth of the 3 blades on the diagram, is this correct? 

Best regards,

![图片1](https://github.com/user-attachments/assets/b47880d9-d0a9-4721-a48e-ba4f54914d1d)

**Comment by jjonkman** [comment]
Dear @sffgd,

Well, you haven't stated if your diagram is from an observer who is upwind looking downwind (with clockwise rotation) or from an observer who is downwind looking upwind (with counterclockwise rotation).

Given your azimuth labeling, it looks like you are showing clockwise rotation (so the observer is upwind looking downwind), but in this case, you've swapped the labeling of blades 2 and 3.

Best regards,

**Comment by sffgd** [comment]
Dear @jjonkman，
 Thank you for your reply！Here's what needs to be confirmedan that observer is upwind looking downwind (with clockwise rotation), so I updated the image above. May I ask if the position of the three blades is correct?
![Uploading 图片2.png…]()

**Comment by sffgd** [comment]
Dear @jjonkman, 
Thank you for your reply！Here's what needs to be confirmedan that observer is upwind looking downwind (with clockwise rotation), so I updated the image above. May I ask if the position of the three blades is correct?
![图片2](https://github.com/user-attachments/assets/fcbd926f-1407-4ff7-8362-9393e5460c91)

**Comment by sffgd** [comment]
Dear @jjonkman,
 Thank you for your reply！
