### ISSUE TITLE
about Moordyn

### ISSUE THREAD

**Issue by HANloading** [OpenFAST/openfast#2326]
Dear All,
I have some questions about the operation of Moordyn, I am considering a semi-submersible platform with three columns, each column is connected to 3 anchor chain lines, so there are 9 anchor chain lines in total, and I would like to ask if moordyn can handle 9 lines? If not, what is the maximum number of lines that can be handled? If it can, does the value of BA/-zeta affect the accuracy of the anchor chain load? Or are there other factors that can affect the accuracy of the anchor chain load?
Best regards!
![image](https://github.com/user-attachments/assets/594e480c-666c-4ae9-8f8c-858809c07177)

**Comment by RyanDavies19** [comment]
Hi @HANloading, 

There is no limit to the number of lines that MoorDyn can handle, but with more lines comes increased computation times. BA/-zeta is the value for the internal damping of the line which helps with numerical stability by reducing high frequency vibrations. Typically it is set to -1. For the anchor chain loads, the values you get will be depend on the chain properties you provide in the MoorDyn input file (see [input files](https://moordyn.readthedocs.io/en/latest/inputs.html#id2) in the docs). MoorDyn's modeling of lines has been well validated, provided you give the correct input parameters for the lines you are trying to model.

**Comment by HANloading** [comment]
@RyanDavies19 
Thank you for your answer.
The problem I'm having now is that when I run moordyn, it prompts some warning messages, and I'm not really sure what's going on, and when this load data is applied to my model, the model's platform produces unpredictable movements.
If I know the pre-tension of each anchor chain line, in addition to the known equivalent mass, the vertical combined force. Can I get the anchor chain static matrix?
![image](https://github.com/user-attachments/assets/eee15bd0-0f29-4437-a3ed-47142e917bf1)
![image](https://github.com/user-attachments/assets/898b248d-cbd6-4a4a-adc7-5c57b062e25b)
[Lines.txt](https://github.com/user-attachments/files/16276609/Lines.txt)

**Comment by RyanDavies19** [comment]
@HANloading 

It's hard to say what's happening without knowing the MoorDyn errors or the bigger simulation you are running. However based on your input file I cold see some potential issues. First your mooring lines are 750m long, however your fairlead and anchor points are further apart than that (example point 1 and 2 have horizontal difference of 750m and vertical difference of 70m). If that doesn't crash MoorDyn it will cause a very taut mooring system. Additionally, your water depth is 200m, while the deepest point you have is only at -55m. Lastly it seems you switched fairlead and anchor points after point 10, because your coupled points are now at -55m and your fixed points are at +16m. 

With regards to the quasi-static mooring stiffness matrix, that is not a feature of MoorDyn because it is a dynamic model. If you need the stiffness matrix refer to the OpenFAST forum for information: https://forums.nrel.gov/search?q=stiffness%20matrix%20mooring

**Comment by HANloading** [comment]
Dear @RyanDavies19 
Now that the water depth and the unstretched length of the anchor chain line have been modified according to tender's suggestion, although it can run successfully and express the anchor chain load more correctly, running the device prompts some warnings, may I ask the reason for this warning why exactly?
![image](https://github.com/user-attachments/assets/c87ba218-b03e-4ad9-9195-5b4d055c9b00)
[Lines.txt](https://github.com/user-attachments/files/16314469/Lines.txt)

**Comment by RyanDavies19** [comment]
@HANloading 

It looks like you are using a very old version of MoorDyn/OpenFAST that has not been updated in 7 years. It's hard to say what's causing issues as the code has had major improvements since then. If possible please try to use the most recent release of the code: https://github.com/OpenFAST/openfast/releases/tag/v3.5.3

For transferring your MoorDyn v1 input file to MoorDyn v2 format, the documentation has descriptions of both file types that should make it possible to convert things over: https://moordyn.readthedocs.io/en/latest/inputs.html

**Comment by HANloading** [comment]
Dear @RyanDavies19 
Thank you very much for your reply, it has successfully solved my problem!
