### ISSUE TITLE
How to get the copyright of an image in the document

### ISSUE THREAD

**Issue by robytian** [OpenFAST/openfast#2337]
Dear @jjonkman  and all

I want to cite something in my review about an image in the online  documentation, and I'd like to ask how I can get the copyright for it.
Thanks

BR,
Roby

**Comment by jjonkman** [comment]
Dear @robytian,

Depending on the image you are referring to, the image may have been included in an official NREL publication, which you could cite directly: https://www.nrel.gov/research/publications.html?utm_medium=print&utm_source=corporate&utm_campaign=pubs.

Otherwise, to cite OpenFAST or its online documentation directly, see a related discussion in the following OpenFAST discussion: https://github.com/OpenFAST/openfast/discussions/733.

Best regards,

**Comment by robytian** [comment]
Dear jjonkman

Thank you for your answer, am I to understand that if I quote an image from a publication or manual, I don't need to get the copyright of the image, I just need to explain it and quote it in the appropriate place.

BR,
Roby

**Comment by jjonkman** [comment]
Dear @robytian,

 Yes, that is correct.  If you copy an image from an NREL publication, it is sufficient if you properly cite the source of the original image.

Best regards,
