### ISSUE TITLE
 Grid too small in Y direction

### ISSUE THREAD

**Issue by shipors** [OpenFAST/openfast#2377]
Hello, 

I am attempting to run a wind farm simulation (with one turbine) using FAST.Farm in a Windows environment, but I am consistently encountering the following error:
![1723810475164](https://github.com/user-attachments/assets/d72ecac4-482a-47b5-9d81-28b78d46862f)

Everything runs smoothly when I use FAST.

As you can see, I am using version 3.5.2 of FAST.Farm_x64_OMP, with Mod_AmbWind set to 2. The specific fstf file and fst file are as follows. I am puzzled about where the Y boundary [-600, 600] comes from. Could you provide some suggestions regarding this issue?

[issue.zip](https://github.com/user-attachments/files/16637033/issue.zip)

THANKS!

**Comment by shipors** [comment]
Unfortunately, the same error persists in version 3.5.3. 

By the way, both versions 3.5.2 and 3.5.3 directly downloaded and used will prompt a stack overflow error, which requires adjusting the stack reserve size during compilation. This issue was supposed to be resolved in version 3.5.3, but it appears that it has not been addressed.

**Comment by jjonkman** [comment]
Dear @shipors,

The Y boundary range of [-600, 600] comes from the TurbSim wind data file you are using (which is using `GridWidth` = 1200 m).  (Note: You shared a TurbSim input file, but this does not appear to be the one you are using because `GridWidth` in that file is 145 m.)  The points at -4000 m etc. triggering the error comes from your settings of the low- and high-resolution domains within FAST.Farm.  Naturally, with `Mod_AmbWind` = 2, all points in the low- and high-resolution domains of FAST.Farm must fall within the bounds of the wind specified within InflowWind, which in your case is the 1200-m wide TurbSim domain.

FYI: We generally recommend using the Python scripts provided in the OpenFAST Toolbox when generating inflow and setting up FAST.Farm models: https://github.com/OpenFAST/openfast_toolbox/tree/main/openfast_toolbox/case_generation.

Best regards,
