### ISSUE TITLE
Support in model adaptation

### ISSUE THREAD

**Issue by GBA217** [OpenFAST/openfast#2384]
Hi,
I want to build a 2MW onshore WTG model with 40m rotor radius in OpenFAST. I have the basic elastodyn and aerodyn inputs which are from an old FAST model of the same. But since I'm new to OpenFAST, I'm trying to build this by modifying NREL 2p8MW by replacing inputs starting from the airfoil and blade structure. Could this approach work? What would be the ideal way to do it?

Here is where I'm right now:

In Elastodyn input, I have modified the sections Turbine Configuration, Mass and Intertia, Blade, Drivetrain and Tower sections to the 2MW model values.

In Aerodyn input file, I have modified the sections Airfoil Information, Rotor/Blade Properties, Tower Influence and Aerodynamics.

Controller used is DLL generated from ROSCO v2.9. In the DISCON.in file, I have made the following changes:
PC_RefSpd 122.9 to 188.5
VS_MinOMSpd 37.8 to 80 since I want the turbine to startup around 780rpm
VS_RtPwr from 2800000 to 2000000
VS_RefSpd to 188.5

With these modification, when I run a Ramp simulation, I'm seeing the below results:

![Capture](https://github.com/user-attachments/assets/b49c6630-85a5-4e9e-8b44-ad4d0847bc9e)

The rotor RPM (blue) is ramping upto around 780 and then pretty much staying there. The Generator torque (black) is zero upto the point where RPM reaches 780 and then it starts to increase but the increase is slower than I would expect resulting in slow Ramp up in Power too and eventually the Power (red) not reaching 2MW even thought he Wind speed is constantly increasing upto 30m/s during the 1000s. 

Please give me a general direction of next steps to make the model work. In case this is wrong approach, please let me know how to modify an already existing model to a different rotor and power rating.

Thank You

**Comment by abhineet-gupta** [comment]
Hi @GBA217,
A DISCON.IN file has several other parameters that need to be modified based on the target turbine.
We recommend that Instead of modifying the DISCON.IN file directly, you redesign the controller from scratch.
[ROSCO](https://github.com/NREL/ROSCO) provides simple tools for this purpose.
See [example-3](https://github.com/NREL/ROSCO/blob/main/Examples/03_tune_controller.py) in particular.
You might also need to look at example 1 and 2 to understand the basic working of ROSCO controller tuning process.

If you run into any roadblock with controller design, please create an issue on the ROSCO github and we'll be able to help you there.

Abhineet
