### ISSUE TITLE
Possible Bug in DISCON Interface FA/SS Accelerations 

### ISSUE THREAD

**Issue by Sam-Ramsahoye** [OpenFAST/openfast#2441]
Hello,

I think I may have found a bug in the passing of nacelle fore-aft acceleration to the swap array received by the controller.

In https://github.com/OpenFAST/openfast/blob/main/modules/servodyn/src/BladedInterface.f90 line 1009 and 1010, elements 53 and 54 are set as YawBrTAxp and YawBrTAyp respectively. 

According to https://openfast.readthedocs.io/en/main/_downloads/d8bd014121d6505cb25cf49bee5eaa80/Old_FAST6_UsersGuide.pdf, these accelerations are defined in the Tower-Top/Base-Plate Coordinate System and move with the platform but don't yaw with the nacelle.

I'm not sure what the intention is here as I'm not overly familiar with the DISCON interface but ROSCO seems to assume the FA signal rotates with the nacelle. I found this after obtaining different controller behaviour running simulations at 90 degrees to my original tests.

Best,
Sam

**Comment by jjonkman** [comment]
Dear @Sam-Ramsahoye,

I guess the question is whether this is a bug in OpenFAST or ROSCO.  Internal coordinate system "p" within ElastoDyn (that passes the acceleration to ServoDyn) is in the tower-top / base-plate coordinate system, which moves with the tower top, but doesn't yaw with the nacelle.  My understanding is that this is what is called out in DNV Bladed's documentation for these channels of the avrSWAP array, which OpenFAST is mimicking.  My guess is the issue is with ROSCO, not OpenFAST.  I'd suggest posting this issue on ROSCO GitHub issues: https://github.com/NREL/ROSCO/issues.

Best regards,

Best regards,

**Comment by Sam-Ramsahoye** [comment]
@jjonkman Thanks Jason. I'll raise the issue with the ROSCO developers.
