### ISSUE TITLE
The question about calculating first-order wave forces by HydroDyn.

### ISSUE THREAD

**Issue by Novoyz** [OpenFAST/openfast#2469]
Dear everyone,

Recently, when I used HydroDyn to specify regular waves with fixed periods, wave directions, wave heights and phases, and calculated the first-order wave forces, I found that for periods not mentioned in the.1 file, there would be a large error when calculating the first-order wave forces corresponding to that period. When I compared my.1 file with the examples in the r-test, I found that the number of wave periods I specified in the frequency domain is far less than the number of periods in the examples. So I would like to ask if this is the cause of the problem? If so, how should it be solved? I will attach the configuration file and screenshots of calculation results below.
![屏幕截图 2024-10-17 105359](https://github.com/user-attachments/assets/f3253144-0215-4235-bda8-2d6f901f6781)

Best regards.

**Comment by jjonkman** [comment]
Dear @Novoyz,

Presumably you are referring to the _.3_ file (instead of the _.1_ file) that contains the wave-excitation loads as a function of period and direction.

For periods not in the file _.3_ file, HydroDyn will interpolate the data between the periods.  This appears to be what HydroDyn is doing in your results (with the surge force amplitude of 5000000 N at 9 s, 7000000 N at 7 s, and 6000000 N at 8 s).  It is your sima solution that does not look correct. 

Our recommend discretization of the first-order potential-flow solution to be used by HydroDyn is documented in the HydroDyn modeling guidance section on readthedocs: https://openfast.readthedocs.io/en/main/source/user/hydrodyn/modeling_considerations.html#floating-systems-modeled-with-potential-flow.


Best regards,

**Comment by Novoyz** [comment]
I am very sorry to have wasted your time and this opportunity to ask questions. The wave load is indeed in the.3 file. The.1 file is for added mass and damping. Before you replied, I always thought there was a problem with the hydrodyn calculation. Now it seems that it is not. I also don't understand why I always had this idea. Thank you very much for your reply. I think I need to be more careful in the future.😅
