### ISSUE TITLE
pitch angle problem under steady wind

### ISSUE THREAD

**Issue by Wangzhenyu12** [OpenFAST/openfast#2500]
Dear Jonkman:
         I meet a similar question like #2461. My model is 5MW onshore wind turbine. The Openfast version is v3.5.4. CompElast=1. I use steady wind, set WindType=1 and HWindSpeed=11.4 (rated wind speed). In INITIAL CONDITIONS, I set RotSpeed=12.1(rated rotation speed), and others remain 0. No other parameters in model are modified. 
        Then I output some parameters as below. 
I do not know why the pitch angle is about 6°？
![image](https://github.com/user-attachments/assets/7d2fd0b7-61dd-4083-a898-431aeb50fcb0)

I also change the HWindSpeed. When HWindSpeed=9, pitch angle and rotor speed curve are like Sin function. But when HWindSpeed=8, pitch angle curve becomes normal. 
The results are similar with or without BeamDyn. Please tell me what makes this result happen. If it is the initial condition problem, how to modify the parameters? Thanks.
![image](https://github.com/user-attachments/assets/44f9ce52-56fa-4011-9074-9efed139b45b)

![image](https://github.com/user-attachments/assets/f431e2ea-b49b-4fbd-89a8-c760e0382f28)

**Comment by jjonkman** [comment]
Dear @Wangzhenyu12,

The pitch angle increases sizeably for wind speeds just above rated.  A pitch angle of 6deg for the NREL 5-MW baseline wind turbine means that the wind speed is slightly above rated.  Given that the rated speed of this turbine is documented to be 11.4 m/s, can you clarify how you set-up your OpenFAST model?  E.g., other than `WindType` and the wind speed in InflowWind and initial conditions in ElastoDyn, what have you changed relative to the example model provided in the r-test: https://github.com/OpenFAST/r-test/tree/main/glue-codes/openfast/5MW_Land_DLL_WTurb?

As has been discussed in many other topics on this forum, when using active control, it is important to initialize the `RotSpeed` and `BlPitch` properly based on their expected (mean) values conditioned on the mean hub-height wind speed you are simulating, otherwise, OpenFAST may respond erratically or take a while to converge.  For the NREL 5-MW baseline wind turbine, the initial conditions are documented in Figure 9-1 of its specifications report: https://www.nrel.gov/docs/fy09osti/38060.pdf.  At 9 m/s, I'd expect that you'd use `RotSpeed` = 10.3 rpm and `BlPitch` = 0deg; at 8 m/s, you should use `RotSpeed` = 9.2 rpm and `BlPitch` = 0deg.

Best regards,

**Comment by Wangzhenyu12** [comment]
Dear [jjonkman](https://github.com/jjonkman),
Thanks for your quick reply. I check my model input files and find an error modification in Aerodyn15.dat which results in this phenomenon. After correction, the pitch angle remains 0° when HWindSpeed is less than 11.4m/s.

Best regards,
