### ISSUE TITLE
Tower model development from scratch

### ISSUE THREAD

**Issue by GBA217** [OpenFAST/openfast#2523]
Hi,

I'm trying to model a onshore tower for a 2MW model for which I have the structural data like Tower section height, outer diameter shell thickness, Emod, Gmod, density. I have a few questions which came up while trying to build an OpenFAST model from these information.

1. How is the TMassDen cansidered exactly?
If I have tower section height out diameter and shell thickness(all in m) like shown below (representatory),
4.95      3.800      0.024
4.96      3.790      0.023
7.90      3.650      0.022
10.85     3.500      0.021
and if I have to find the TMassDen at height 7.9m, do I just find the area of the hollow circular region and multiply by the material density? Or do I have to consider the area of adjacent sections too (averaging)? (Asking this because I'm not sure how exactly the TMassDen is used in the OpenFAST)

2. How do I incorporate point masses which represent the tower flanges and the mass of the internals present in the tower platforms? Does OpenFAST have provision for that?

3. I have not considered the point masses yet as I'm not sure how to do it. I understand that I have to use Bmodes.exe and ModeShapePolyFitting to find the eigen frequencies and the corresponding polynomial coefficients to be used in the elastodyn tower data file. The 1st mode frequency in fore-aft and side-side are close to the expected value but the 2nd mode frequencies are not (lower than expected). Could this be because the point masses are not considered? 

TIA

**Comment by jjonkman** [comment]
Dear @GBA217,

Here are my responses.

1. `TMassDen` in the ElastoDyn tower file should equal the cross sectional area times the material density.  You shouldn't need to average between adjacent sections.  See Table 9 in the old FAST v6 User's Guide for definitions of the tower properties (`TMassDen`, `TwFAStif`, `TwSSStif`) used by ElastoDyn: https://openfast.readthedocs.io/en/main/_downloads/d8bd014121d6505cb25cf49bee5eaa80/Old_FAST6_UsersGuide.pdf.  For cylindrical cross sections of isotropic material, the calculations are straightforward.
2. ElastoDyn does not support point masses in the tower.  To approximate the effect of the point masses, you'd have to incorporate their effect in the distributed tower properties.  That said, you could model the tower in SubDyn instead of ElastoDyn and SubDyn does incorporate point masses directly, with the only limitation that SubDyn is inherently linear while ElastoDyn considers geometric nonlinearities of the tower deflection.
3. I'm not sure I understand what you are comparing against, but the use of BModes and ModeShapePolyFitting is one way to compute the tower mode shapes for use by ElastoDyn (while ElastoDyn requires the user to specify mode shapes (shape functions), it does not require tower natural frequencies to be specified).  If you switch to SubDyn, you don't need to supply tower mode shapes, as these are calculated internally within SubDyn.

Best regards,

**Comment by GBA217** [comment]
Hi @jjonkman,
Thanks for the response. I have a few follow-up questions:
1. Regarding subdyn, is it possible to define the tower using both elastodyn and subdyn together to capture both the geometric non-linearities as well as effect of point masses?

2. Regarding the mismatch in 2nd eigen mode frequency of tower, I compared the results against the results from Flex5 model of the same turbine.
To get a better understanding, I tried to get the frequencies of the NREL5MW using Bmodes and I again see that the 1st mode FA and SS are closely matching but the 2nd mode FA and SS are lower than expected (~2.9Hz in the report):
![image](https://github.com/user-attachments/assets/c6629e2e-9bdd-4696-b253-9a4cd5ac9c7b)


Is this an expected deviation when moving from ADAMS to Bmodes?

These are the input parameters that I used in case of NREL5MW:
![image](https://github.com/user-attachments/assets/999eab4a-a54a-47a4-8cfa-8ad0a498420d)
![image](https://github.com/user-attachments/assets/186b1eb7-7edd-480b-a698-eb6ab53b50db)

Section data:
![image](https://github.com/user-attachments/assets/0bd538b7-7e2f-435f-97e2-412dc5896d85)

Does this look okay or is there anything I can change to get the 2nd mode results more accurately?

TIA

**Comment by jjonkman** [comment]
Dear @GBA217,

Here are my responses:

1. There must be a clear boundary (without overlap/duplication) between the structural members considered in ElastoDyn and the structural members considered in SubDyn.  Normally this would be at the tower base (to represent the tower in ElastoDyn) or the tower top (to represent the tower in SubDyn).

2. Your BModes input files look fine.  BModes treats the rotor-nacelle assembly (RNA) rigidly whereas other modes (like ADAMS) likely treat the RNA with structural elasticity, e.g., blade flexibility.  This flexibility will have more of an impact on the higher bending modes (that is, blade flexibility will have more of an impact on the 2nd tower bending modes than it will on the 1st tower bending modes).  When deriving tower mode shapes for ElastoDyn, we typically assume a rigid RNA (e.g., using BModes), but assume the mode shapes are valid when used within ElastoDyn with a flexible RNA.  (A small amount of error in the mode shapes / shape functions used in ElastoDyn will likely not negatively impact the accuracy of ElastoDyn that much.)  The natural frequencies captured by ElastoDyn within OpenFAST, though, account for the full coupling between the tower and blades, and so, the 2nd tower bending natural frequencies captured by ElastoDyn will differ from BModes.

Best regards,
