### ISSUE TITLE
The simulation of a pile model subjected to a force at one end in stand-alone SubDyn

### ISSUE THREAD

**Issue by Jane-daria** [OpenFAST/openfast#2526]
Hi OpenFAST Community,

I hope this message finds you well. I ‘m modeling a pile foundation in standalone SubDyn (using SubDyn driver file, filename.dvr), with one pile end subjected to a force or displacement.
In my setup, I have modeled a pile where the base point (Base reaction joint) is fixed. A user-defined displacement is applied at the top point (TP reference point). The desired displacement at pile top is to make it displace along x direction while keeping the other directions free. 
However, when configuring in subdyn driver, it seems that motions/rotation along all 6 directions at the TP point (pile top) have to be set to constant/time-varying values. That is to say, they are all constrained which deviate from my desired loading. 
Hence, my question is can I find a way to displace the pile top along x direction while release other DoF at pile top.

Best regards
![image](https://github.com/user-attachments/assets/068bd214-b5d1-4a72-87da-a32f70add805)

**Comment by jjonkman** [comment]
Dear @Jane-daria,

SubDyn is set up so that the motion (3 translations, 3 rotations) of the interface node is prescribed as input to SubDyn by the driver / calling program, with SubDyn returning the reaction loads (3 forces, 3 moments) at the interface node as output back to the driver / calling program.  Changing that to use different inputs and outputs would require a source code change.

Best regards,

**Comment by Jane-daria** [comment]
Thank you for your explanation @jonkman, and your proposed solution @RBergua. In fact, some constraints at the fixed end (pile bottom) also need to be released in my subsequent calculations. However, this is still a great attempt. 
Thank you again for your kind responses!

Best regards
