### ISSUE TITLE
Issue with Adding a Constant Torque Offset in ServoDyn

### ISSUE THREAD

**Issue by dorsamgh** [OpenFAST/openfast#2549]
Hello, I hope you're doing well. 

In a part of my project, I attempted to modify the source code related to ServoDyn to add a torque value of 10 kNm to the generator torque. (The turbine model is IEA-15-240-RWT-UMaineSemi, and I am using OpenFAST version 3.3.0.) 
I implemented this as follows: 
![image](https://github.com/user-attachments/assets/c4410163-6a6e-497f-b3b9-b43aadb4e8ba)

However, when I plot the difference between the normal and faulty states, the offset value is not consistently -10 and varies. Could you please guide me on this?
![image](https://github.com/user-attachments/assets/f76c78b2-ddae-49a9-b88b-4f061de86c19)

Thank you in advance.

**Comment by jjonkman** [comment]
Dear @dorsamgh,

Can you clarify what you are plotting as the "Error between Column 2 and Column 3"?

Because you are augmenting the generator torque after it is output from the controller, I imagine this could cause confusion in the controller considering that the blade pitch and generator speed (which likely depend on torque) may not be consistent.  I think it would be preferred to modify the torque within the controller directly.  I gather that you are using ROSCO given your use of the IEA Wind 15-MW RWT, so, modifying ROSCO is likely preferred over modifying ServoDyn.

Best regards,

**Comment by dorsamgh** [comment]
Dear @jjonkman 

Thank you for your prompt response. This plot shows the difference between the generator torque in the normal state and the state with a 10 kNm offset. I expected that from second 400 onward, given the fault scenario, all values would be -10, but this is not the case.  

Yes, I intended to use ROSCO. For example, to implement a previous fault scenario (blade pitch angle stuck), but I was unable to set it up correctly in Simulink with my model and ran into issues.  

If I want to run and modify ROSCO outside the Simulink environment, is it possible? And is there no way to implement this bias directly within the ServoDyn source code?

thank you
