### ISSUE TITLE
How to Properly Change Different Wind Directions

### ISSUE THREAD

**Issue by axxyyyyyyyy378** [OpenFAST/openfast#2574]
Hi everyone,

Recently I wanted to test the turbine's response to different wind directions. In the "5MW_OC4Semi_WSt_WavesWN" case, the default wind propagation direction is 0° (aligned with the positive X-axis, `PropagationDir = 0°`), and the turbine rotor and nacelle are directly facing the incoming wind (`NacYaw = 0°`, aligned with the negative X-axis). 

I generated a turbulent wind field using TurbSim and changed the wind propagation direction in InflowWind to 90° (`PropagationDir = 90°`). Then I encountered some issues: Do I need to adjust other parameters? Should I set `NacYaw` to 90° in ElastoDyn to ensure the turbine faces the wind directly? 
I tried this approach, but the program failed to run due to aerodynamic errors (see the first figure below). However, if I keep `NacYaw = 0°`, the program runs but still shows some warnings (see the second figure below). What adjustments should I make?

<img width="701" alt="1734620766873" src="https://github.com/user-attachments/assets/9c963bb4-959e-405d-86b6-a994c6e98429" />

<img width="693" alt="1734620685827" src="https://github.com/user-attachments/assets/330035fe-5430-4942-8503-0789cd1dba1d" />

Thanks in advance.

**Comment by jjonkman** [comment]
Dear @axxyyyyyyyy378,

To minimize yaw error/misalignment, you should change the yaw angle when you change the wind direction.

However, `PropagationDir` in InflowWind uses meteorological convention (positive `PropagationDir` is clockwise when viewed from above) whereas the yaw angle in OpenFAST uses right-hand rule convention (positive `NacYaw` is counterclockwise when viewed from above).  Thus, to minimize yaw error/misalignment, you should set `NacYaw` = -`PropagationDir`.

Note that if you change `NacYaw` and the nacelle-yaw degree of freedom of ElastoDyn is enabled (`YawDOF` = TRUE), you should also set `YawNeut` in the ServoDyn module equal to `NacYaw` or the nacelle will quickly snap from `NacYaw` back to `YawNeut` due to the nacelle-yaw spring in ServoDyn.

Best regards,

**Comment by axxyyyyyyyy378** [comment]
Dear @jjonkman,

Thank you for your professional response. My issue has been resolved.

Best regards,
