### ISSUE TITLE
BeamDyn initialization with non-zero initial azimuth produces strange results

### ISSUE THREAD

**Issue by bjonkman** [OpenFAST/openfast#26]
See attached file for description of the problem.

[BeamDyn_InitializationBug.pdf](https://github.com/OpenFAST/openfast/files/991081/BeamDyn_InitializationBug.pdf)

**Comment by bjonkman** [comment]
@michaelasprague - Has there been any progress on this issue?

**Comment by michaelasprague** [comment]
@bjonkman , sorry, no.  @rafaelmudafort is taking lead on this now; plan is to address this by exposing the problem in the testing harness and to then pursue the fix.

**Comment by andrew-platt** [comment]
In the _CalcIC_ routine, the calculation of the translational velocity is incorrectly referenced.  The root node position needs to be subtracted otherwise the distance used in the cross product is relative to the original root position, not the rotated root position.  We (Envision) have a fix for this that we will give you.

**Comment by michaelasprague** [comment]
@andrew-platt, it would be great if this could be submitted as a pull request -- please let us know if there's another mechanism you'd prefer. Thanks!

**Comment by rafmudaf** [comment]
This issue was fixed in pull request #114
