### ISSUE TITLE
Difference in output between BeamDyn versions

### ISSUE THREAD

**Issue by JelmerPolman** [OpenFAST/openfast#293]
Dear all,

I'm modelling a 80m rotor blade in OpenFAST, in combination with BeamDyn to model the structural dynamics.

I used a BeamDyn driver compiled in single precision under a 64-bit windows system (BeamDyn v1.01.04). Now I upgraded to the latest v2.1.0-version on the master branch, compiled on a 64-bit Linux cluster system using intel/2018b and CMake/3.11.4.

After the version upgrade, I experience large differences in the BeamDyn deflections. As an example, I attached a BeamDyn model of the two versions, where the blade is loaded under a 1g gravity load. As the output files show, the v1.01.04 shows a transient to the correct tip deflection of 1.3m (verified with HAWC2 and Bladed). The newest version of BeamDyn shows a minimal steady tip deflection. 

My question is: where does the difference in output between the two versions comes from? Have the output coordinate system of Beamdyn changed, or have I compiled BeamDyn wrong?

I'm grateful for any thoughts on this matter.

Best regards,
Jelmer Polman

[BeamDyn_Issue.zip](https://github.com/OpenFAST/openfast/files/3216596/BeamDyn_Issue.zip)

**Comment by andrew-platt** [comment]
I think I know what the problem is.  The definition of the output nodes changed between versions from finite element (FE) points (9 total) to the quadrature points (84 total).  This change was made when the mesh resolution was increased.


## v 1.01.04
In the version 1.01.04, the output nodes are at the finite element points.  Thus in you v1.01.04 model, the output nodes selected correspond to the finite element (FE -- where the calculations are performed). These nodal locations are at the spanwise locations of 

```
0.00000E+00
4.00868E+00
1.29093E+01
2.54689E+01
3.99900E+01
5.45111E+01
6.70707E+01
7.59713E+01
7.99800E+01
```

These are given in the summary file as the global node initial position vectors.

## v2.1.0
In the version 2.1.0, the output nodes correspond to the quadrature points given in the blade file.  So, the node 9 as requested is corresponding to a location of `6.9` meters (between FE nodes 1 and 2).  If you want the tip deflection, you will want to include the following channels in the outlist: `TipTDxr` `TipTDyr`, and `TipTDzr`.  If you want a comparable comparison to the FE node locations from v1.01.04, you can select the nodes to output as:

```
          1, 6, 15, 27, 42, 57, 69, 78, 84    OutNd          - Nodes whose values will be output  (-) 
 ```

The quadrature point locations are also listed in the summary file.  To find the nodes closest to the FE nodes, I searched through this list from your model.  The FE node at 25 m falls between quadrature points 27 and 28.

Also, note that this version includes a `QuasiStaticInit` solve option.  This will find the static equilibrium before running the dynamic solve.  This helps reduce the initial transients in a fully coupled solution.

**Comment by andrew-platt** [comment]
I ran your case using BeamDyn compiled from the `dev` branch using gfortran on a Mac (File 1) and compared with your v1.01.04 output file.  I used the `OutNd` as specified above, and set the `QuasiStaticInit` to false.

![Screen Shot 2019-05-31 at 3 32 42 PM](https://user-images.githubusercontent.com/2745453/58735988-82e8e400-83b9-11e9-8449-bd669d0338a2.png)

**Comment by JelmerPolman** [comment]
Thank you for the help. That was indeed the issue I had. 

Best regards,
Jelmer Polman
