### ISSUE TITLE
Difference in forces from AeroDyn and BeamDyn

### ISSUE THREAD

**Issue by JelmerPolman** [OpenFAST/openfast#298]
Dear all,

I have a problem with out-of-plane and in-plane forces from BeamDyn that don't match with the forces from AeroDyn. This leads to highly overestimated blade deformations.  I have compared the forces from AeroDyn (channel Fx and Fy ) with the forces from BeamDyn (channel DFxl and DFyl) over the blade span, see the figure below:

![Forces_AeroDyn_vs_BeamDyn](https://user-images.githubusercontent.com/50822421/60006066-08d21500-9670-11e9-8556-e42da68e555b.png)

I simulated a (simpel) test case with a steady uniform wind field with a fixed-speed rotor and OpenFAST v2.1.0. There is no shaft tilt and blade cone, plus gravity is set to zero to elminate all asymmetry. I have attached the simulation files:

[Simulation_files.zip](https://github.com/OpenFAST/openfast/files/3320105/Simulation_files.zip)

Is there a solution to match the forces from both modules?

Best regards,
Jelmer Polman

**Comment by andrew-platt** [comment]
Hi Jelmer,

The issue here is the outputs are in two different coordinate frames and are about two different spatial lines.  The aerodynamic center is defined by the x and y locations given in the AeroDyn blade file, and the structural center is defined by the x and y locations given by the keypoint line in the BeamDyn input file.  So, all the force and moment outputs from AeroDyn (given by `Fx`, `Fy`, `Mx`, `My` outputs) are centered about the aerodynamic center.  In the transfer of the loads from AeroDyn to BeamDyn, a mapping is done to map the forces and moments from the aerodynamic center over to the structural center defined in BeamDyn.  In your example, the structural center and AeroDynamic center are not coincident with each other, so a distributed force/moment pair for a given node will not look exactly the same coming into BeamDyn (there is a spatial difference there).  The details of this mapping are covered here: https://www.nrel.gov/docs/fy14osti/60742.pdf

The following data is plotted from the 
![AD15_BD_spatial](https://user-images.githubusercontent.com/2745453/60131179-00540a00-9756-11e9-9766-a5783559e906.png)


Regards,
Andy

**Comment by JelmerPolman** [comment]
Hi Andy,

thank you for the reply.

I understand that the coordinate systems are different. However, both reference axis are smooth so I don't understand why the forces in BeamDyn are non-smooth.

The reason why I'm looking at the difference in forces is that the blade deformation does not fit to a reference solution. In the figure below I plot the out-of-plane and in-plane deformation of the testcase calcuated with OpenFAST, and compare it to a Bladed solution. One can see that the deformations are much too high. However, if I feed in the AeroDyn forces as a point force distribution in a BeamDyn-standalone calculation, I get much closer to the Bladed solution. Hence my suspision that AeroDyn does not map the forces correctly to BeamDyn. 

![deflectionOutOfPlane](https://user-images.githubusercontent.com/50822421/60246573-3fea3580-98bf-11e9-8444-86782e78fe0f.png)

![deflectionInPlane](https://user-images.githubusercontent.com/50822421/60246566-3bbe1800-98bf-11e9-8bd0-a2359a7ddb7c.png)

As I understand from the paper, the Point_to_Line2 load mapping algorithm maps the forces from AeroDyn to BeamDyn? Are there any more steps I can take to figure out why the deformations does not match?

Regards,
Jelmer

**Comment by jjonkman** [comment]
Dear @JelmerPolman,

Actually, the aerodynamic applied loads from AeroDyn are transferred to BeamDyn using a line-to-line mesh mapping.

I haven't looked at your input files, but my guess is there are bumps in the BeamDyn loads because your AeroDyn and BeamDyn meshes are not identical and the bumps are exaggerated because of the difference in coordinate systems.  The loads should transfer directly (one-to-one) if the BeamDyn and AeroDyn meshes are identical.  I would suggest playing around a bit with the placement of analysis nodes in AeroDyn and/or trapezoidal points in BeamDyn to understand the sensitivity of the mesh-mapping and to verify that the loads converge as the meshes become closer to identical.

Best regards,

**Comment by JelmerPolman** [comment]
Hello,


Thank you for your help. I have corrected some small mistakes in the keypoints, which shifted the quadrature points which helped a lot. However, I am still not there yet.

I'm trying to figure out how the quadrature points are found based on the keypoints ant the station eta locations. They don't end up exactly in the place where I would expect them.

The curved reference axis is defined by the keypoints. The quadrature points are found by interpolation to the station eta locations. How is this interpolation precisely done? Is the interpolation done linearly, effectively changing the curved reference axis to a piecewise linear axis? 


Best regards,
Jelmer Polman

**Comment by jjonkman** [comment]
Dear @JelmerPolman 

My understanding from the figure in your first post above is that you are using trapezoidal quadrature.  In this case, and assuming BeamDyn input refine = 1, the quadrature points are identical to station eta locations (without interpolation). In this case, but with refine = 2, additional quadrature points would be added to the midpoint between adjacent station eta locations, etc.

Best regards,

**Comment by JelmerPolman** [comment]
Hello,


After a lot of tests, the best solution I came up with, is just to interpolate all cross sectional matrices to the same radial postion of the aerodyn stations. By doing so, most bumps disappeared.

![Forces_AeroDyn_BeamDyn](https://user-images.githubusercontent.com/50822421/62276762-0a4be580-b445-11e9-9666-bee8653e60c9.png)

The blade deflections now fit the Bladed reference solution

![06_deflectionOutOfPlane](https://user-images.githubusercontent.com/50822421/62276809-1fc10f80-b445-11e9-81dd-54843e6977d6.png)
![05_deflectionInPlane](https://user-images.githubusercontent.com/50822421/62276820-23ed2d00-b445-11e9-9047-b7bb865d0cf0.png)


I consider this issue as closed and wanted to thank you both for the help.

Best regards,
Jelmer Polman
