### ISSUE TITLE
Regression Test Failures

### ISSUE THREAD

**Issue by GeorgeElderfield** [OpenFAST/openfast#323]
I am getting 16 passed test and 13 failed tests when trying to run the regression testing method using Visual studio outlined here ... https://openfast.readthedocs.io/en/master/source/testing/regression_test_windows.html.

![image](https://user-images.githubusercontent.com/54076511/63274302-73ca5180-c297-11e9-97cc-1507d0484999.png)

I also tried to inspect the plots as suggested on issue #260 and have matplotlib installed. However I can't seem to produce the plots using -p. Opening the regression test summary gives me a page of the tests, inspecting an individual test gives me the screenshot below and if I select go to plots I get a file no found error. 

![image](https://user-images.githubusercontent.com/54076511/63274341-86448b00-c297-11e9-843f-bdb0f0242fc8.png)

How do I go about producing the regression test plots and fixing the failed tests?

Thanks 

George

**Comment by rafmudaf** [comment]
Hi @GeorgeElderfield,

Given that all of the 5MW cases failed, it seems likely that the DISCON controllers are not compiled correctly or not in the correct location. You should check the log file for those cases for more info. And also check out the docs for [ctest configuration](https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#ctest-configuration).

On the plotting, only the failing test cases will generate plots so since `AWT_YFix_WSt` passed, the plots are not generated. If the 5MW cases also do not have plots, they very likely didn't run. And finally, the linearized cases don't produce a time series so there's nothing to plot there. In fact, the manual regression test script doesn't run the linearization cases. To run all of the tests, you should use the ctest driver.
