### ISSUE TITLE
Building errors using VS code and Windows

### ISSUE THREAD

**Issue by La-Seem** [OpenFAST/openfast#328]
Dear all,

I've been trying to install openFAST for some days now, but without any success. 
The guide that I'm working with is [this](https://raf-openfast.readthedocs.io/en/latest/source/install/install_vs_windows.html). 

I'm using:
- Windows 10
- Visual studio code 2019 (also tried 2017, 2015)
- Intel Fortran (XE2019, + VS integration)
- Configuration: Release, x64
- Git
- Upgraded the two files to their 2019 version

Furthermore, I've tried:
- Redoing all steps on a new Windows account
- Reopening/building VS code (multiple times), after the errors
- Removing all spaces from the file path

The console output is as follows:

`2>------ Build started: Project: FAST, Configuration: Release x64 ------
2>Performing Pre-Build Event...
2>Compiling with Intel(R) Visual Fortran Compiler 19.0.4.245 [Intel(R) 64]...
2>FAST_Prog.f90
2>Linking...
2>ipo: error #11018: Cannot open C:\Users\me\Downloads\code\openfast\build\bin\Registry.lib
2>ipo: error #11018: Cannot open mkl_intel_lp64
2>ipo: error #11018: Cannot open mkl_sequential
2>ipo: error #11018: Cannot open mkl_core
2>ipo: warning #11021: unresolved DGBSV
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved SGBSV
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved DGEMM
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved SGEMM
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved DGESV
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved SGESV
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved DGETRF
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved SGETRF
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved DGETRS
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved SGETRS
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved DGETRI
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved SGETRI
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved DGGEV
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved SGGEV
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved DPOSV
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved SPOSV
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved DPPTRF
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved SPPTRF
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved DGESVD
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved SGESVD
2>        Referenced in FASTlib_x64.lib(NWTC_LAPACK.obj)
2>ipo: warning #11021: unresolved LSAME
2>        Referenced in FASTlib_x64.lib(dlasrt2.obj)
2>        Referenced in FASTlib_x64.lib(slasrt2.obj)
2>ipo: warning #11021: unresolved XERBLA
2>        Referenced in FASTlib_x64.lib(dlasrt2.obj)
2>        Referenced in FASTlib_x64.lib(slasrt2.obj)
2>ipo: error #11023: Not all components required for linking are present on command line
2>LINK : fatal error LNK1181: cannot open input file 'C:\Users\me\Downloads\code\openfast\build\bin\Registry.lib'
2>
2>Build log written to  "file://C:\Users\me\Downloads\code\openfast\vs-build\FAST\x64\Release\BuildLog.htm"
2>FAST - 6 error(s), 22 warning(s)
========== Build: 1 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========`

Please help me with with a solution, such I can resolve these errors.

**Comment by La-Seem** [comment]
This issue has been solved by installing Fortran 2017 together with VS code 2015.

**Comment by ChaoREN1994** [comment]
Hello, 

I have also met the same problem. I wan to know how to solve that 
I'm using:

Windows 10
Visual studio code 2017 
Intel Fortran (XE2020, + VS integration)
Configuration: Release_double, x64
Git
Upgraded the two files to their 2019 version

Instead of using Fortran 2017 and VS code,  can I solve that ?
![BUG](https://user-images.githubusercontent.com/66703137/84208536-4368d380-aab4-11ea-90a4-7e506341d8eb.PNG)

**Comment by ChaoREN1994** [comment]
Hello,

I have also met the same problem. I wan to know how to solve that
I'm using:

Windows 10
Visual studio code 2017
Intel Fortran (XE2020, + VS integration)
Configuration: Release_double, x64
Git
Upgraded the two files to their 2019 version

Instead of using Fortran 2017 and VS code, can I solve that ?

Here is the problem:
Deleting intermediate files and output files for project 'FAST', configuration 'Release_Double|x64'.
Performing Pre-Build Event...
..\CreateGitVersion.bat
Compiling with Intel(R) Visual Fortran Compiler 19.1.0.166 [Intel(R) 64]...
ifort /nologo /O2 /Qipo /fpp /I"C:\Users\Windlover\Desktop\code\openfast\vs-build\FASTlib\x64\Release_Double" /DDOUBLE_PRECISION /stand:f03 /Qdiag-disable:5268,5199 /real-size:64 /double-size:128 /module:"x64\Release_Double\\" /object:"x64\Release_Double\\" /Fd"x64\Release_Double\vc150.pdb" /libs:static /threads /Qmkl:sequential /c /Qlocation,link,"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64" /Qm64 "C:\Users\Windlover\Desktop\code\openfast\glue-codes\openfast\src\FAST_Prog.f90"
Linking...
Link /OUT:"..\..\build\bin\\openfast_x64_Double.exe" /INCREMENTAL:NO /NOLOGO /MANIFEST:NO /SUBSYSTEM:CONSOLE /STACK:9999999 /IMPLIB:"C:\Users\Windlover\Desktop\code\openfast\build\bin\openfast_x64_Double.lib" -qm64 /qoffload-ldopts="-mkl=sequential" "x64\Release_Double\FAST_Prog.obj" "C:\Users\Windlover\Desktop\code\openfast\build\bin\MAP_x64.lib" "C:\Users\Windlover\Desktop\code\openfast\build\bin\FASTlib_x64_Double.lib" "C:\Users\Windlover\Desktop\code\openfast\build\bin\Registry.lib"
ipo: error #11018: Cannot open C:\Users\Windlover\Desktop\code\openfast\build\bin\Registry.lib
LINK : fatal error LNK1181: 无法打开输入文件“C:\Users\Windlover\Desktop\code\openfast\build\bin\Registry.lib”


FAST - 2 error(s), 0 warning(s)

**Comment by ChaoREN1994** [comment]
Thanks to your reponses.   I try again to install the openfast. I deleted the previous Visual Studio 2017 and reinstall Visual Studio 2017 also with l Intel Fortran (XE2020, + VS integration).  

I follow the the https://openfast.readthedocs.io/en/master/source/install/.
1. Used the files from https://github.com/openfast/openfast.git
2. Opened FAST.sln
3. Accepted to upgrade VC++ Compiler and Libraries
4 Chose Release and x64, then Build Solution (not Build FAST).  
This time do not have errors but I only have thses files not including openfast_x64.exe
![1](https://user-images.githubusercontent.com/66703137/84398794-acf5f880-ac00-11ea-9072-7df990d05af2.PNG)
I try to close and reopen the FAST.sln many times.  It have no errors but always without  openfast_x64.exe.

5. In addition , I can  successfully build the  DISCON DLLs with Discon.sln. However with FAST.sln,  Chose Release_double and x64, then Build Solution.  It also have no errors but can't build openfast_x64_double.exe

6. Then I try to use the "windows_openfast_binaries" download form https://github.com/OpenFAST/openfast/releases to do regression tests.  Sadly, All failed!
![2](https://user-images.githubusercontent.com/66703137/84400776-c39d4f00-ac02-11ea-8b9e-d4ce3dbc52cf.PNG)

7. Finally, I also try to run the one example in 0C4 project with jacket foundation in 5MW example. It also failed. 
![3](https://user-images.githubusercontent.com/66703137/84401139-360e2f00-ac03-11ea-81a1-80b5b82de4ec.PNG)


I am newer of  Visual Studio.  Thus, I do not know to solve the problem. In addition, If I only want to use the "5MW_OC4Jckt_ExtPtfm" and "5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth",  Can i use the windows_openfast_binaries download form https://github.com/OpenFAST/openfast/releases ???

Looking forward to your reply. Thanks again!!!

**Comment by bjonkman** [comment]
If you do not plan to change any source code, then **yes, you can just use the binaries from https://github.com/OpenFAST/openfast/releases**. The last error you display here seems to be caused by an InflowWind input file that is not in the correct format for the version of OpenFAST you are using. 

I do find it strange that the openfast executable file is not in the `build/bin` directory if you have no build errors. If you do need help debugging that, please attach the text from Visual Studio's `Output` tab (showing output from the build). But, I'd recommend just using the binaries in the OpenFAST releases page.

**Comment by ChaoREN1994** [comment]
Thanks for your reply.  Here is the output from Fast.sln (Chose Release and x64, then Build Solution). I am sorry that there are Chinese words in output. I hope that It will have not effect on you to read the output results.
![1](https://user-images.githubusercontent.com/66703137/84408342-4aa2f500-ac0c-11ea-9657-60ee2813f1e6.PNG)
The end line of the output says:  Succeed 2,  fail 0,  skip 0

**Comment by ChaoREN1994** [comment]
I change the language in English and rebuild with Fast.sln (Chose Release and x64, then rebuild Solution)
The output is :

1>------ Rebuild All started: Project: FAST_Registry, Configuration: Release x64 ------
1>data.c
1>gen_c_types.c
1>gen_module_files.c
1>c:\users\windlover\desktop\code\openfast\modules\openfast-registry\src\gen_module_files.c(2354): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>c:\users\windlover\desktop\code\openfast\modules\openfast-registry\src\gen_module_files.c(2366): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>misc.c
1>my_strtok.c
1>registry.c
1>reg_parse.c
1>c:\users\windlover\desktop\code\openfast\modules\openfast-registry\src\reg_parse.c(272): warning C4102: 'normal': unreferenced label
1>sym.c
1>symtab_gen.c
1>type.c
1>c:\users\windlover\desktop\code\openfast\modules\openfast-registry\src\type.c(187): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>Generating code
1>All 74 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>Finished generating code
1>FAST_Registry.vcxproj -> C:\Users\Windlover\Desktop\code\openfast\vs-build\Registry\..\..\build\bin\Registry.exe
1>Done building project "FAST_Registry.vcxproj".
2>------ Rebuild All started: Project: MAP_dll, Configuration: Release x64 ------
2>Performing Custom Build Tools
2>======================================================================
2>
2>----- FAST Registry --------------
2>----------------------------------------------------------
2>input file: ..\..\modules\map\src\MAP_Registry.txt
2>opening ..\..\modules\nwtc-library\src/Registry_NWTC_Library.txt
2>generating ..\..\modules\map\src/MAP_Types.f90
2>CUSTOMBUILD : Registry warning : derived data type Ver of type progdesc is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type PtFairDisplacement of type meshtype is not passed through C interface
2>CUSTOMBUILD : Registry warning : derived data type ptFairleadLoad of type meshtype is not passed through C interface
2>
2>Registry for MAP completed.
2> 
2>======================================================================
2>bstraux.c
2>c:\users\windlover\desktop\code\openfast\modules\map\src\bstring\bstraux.c(1004): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
2>c:\users\windlover\desktop\code\openfast\modules\map\src\bstring\bstraux.c(1017): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
2>bstrlib.c
2>c:\users\windlover\desktop\code\openfast\modules\map\src\bstring\bstrlib.c(367): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
2>dpmpar.c
2>enorm.c
2>enorm_u.c
2>lmder.c
2>lmpar.c
2>qrfac.c
2>qrsolv.c
2>freedata.c
2>jacobian.c
2>lineroutines.c
2>mapapi.c
2>c:\users\windlover\desktop\code\openfast\modules\map\src\mapapi.h : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>maperror.c
2>mapinit.c
2>numeric.c
2>outputstream.c
2>residual.c
2>simclist.c
2>lmroutines.cc
2>   Creating library ..\..\build\bin\MAP_x64.lib and object ..\..\build\bin\MAP_x64.exp
2>Generating code
2>All 293 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
2>Finished generating code
2>MAP_dll.vcxproj -> C:\Users\Windlover\Desktop\code\openfast\vs-build\MAPlib\..\..\build\bin\MAP_x64.dll
2>Done building project "MAP_dll.vcxproj".
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Comment by bjonkman** [comment]
It looks like it is recognizing and building only the projects written in C/C++, and not the Fortran projects. Are you sure you installed the Intel Fortran integrations into this version of Visual Studio (after you installed Visual Studio)?

A screen shot of the solution file open in Visual Studio might help.

**Comment by ChaoREN1994** [comment]
Thanks for your reply. Here is screen shot of Visual Studio. Here shows that i have Intel Fortran integrations.
![1](https://user-images.githubusercontent.com/66703137/84425190-711f5b00-ac21-11ea-8d22-aeee6e43b4a3.PNG)

But when I open that FAST.lsn and I see can only build these two.
![2](https://user-images.githubusercontent.com/66703137/84425315-a1ff9000-ac21-11ea-86ca-35d9e0b10a62.PNG)
But when I open that FASTlib.lsn and I see can only build these three.
![3](https://user-images.githubusercontent.com/66703137/84425346-b17ed900-ac21-11ea-9455-6eb9c6b30091.PNG)

**Comment by ChaoREN1994** [comment]
In addition, you are right about the  InflowWind input file.  If I changed that and used one in FASTv8,  It worked
![4](https://user-images.githubusercontent.com/66703137/84425668-41248780-ac22-11ea-8c0b-8cf2953ec3ec.PNG)

Well, I still have some questions about the Openfast and Fastv8

1. One is about the exe. files. In Fastv8 , I see there are Fast_x64.exe and Fast_x64d.exe. In openfast, there are also two for x64(Openfast_x64 and Openfast_x64_double). What is the differences?  If using x64 or x64_double, the results of simualtions will be different?

2. It is about the AeroDyn module.  There are two files AeroDyn14 and AeroDyn15 in FASTv8.  What is the differences?  Also, I know, for different wind speed , I need to intialize the  rotor speed and pitch angle.  I want to know how much rotor speed and pitch angle I should set for a given wind speed? Does that have a rule or an equation?  Could you give me some references?  In addition, If using AeroDyn15,  sometimes FAST will abort at the beginning or during the Fast simulation due to high attack angle ( I can change the High attack limit in the given file but It also happens). However with AeroDyn14, It will not happen. Thus, I would like to know that the differences between the two AeroDyn is huge or not?
![5](https://user-images.githubusercontent.com/66703137/84427204-d0329f00-ac24-11ea-9e5e-644be9080047.PNG)
 file)

3.  It about the 5MW_OC4Jckt_ExtPtfm module. I try to run that but failed. It is also the problem of input file???  How could I fix that (In FASTv8, It does not have this file)? In addition, for the ExtPtfm module, how could I import my new platform matrix using superelement(substructure) method? Do you have any tutorial, technical report or paper about this part?  Thanks!!!
![6](https://user-images.githubusercontent.com/66703137/84427919-eab94800-ac25-11ea-8cc4-ee0c9ee76e69.PNG)

Any way, thank you very much. Your replys are very useful and really save my life!  Looking forward to your responses

**Comment by bjonkman** [comment]
Can you show me the "Solution Explorer" tab instead of the "Team Explorer" tab?

**Comment by ChaoREN1994** [comment]
Here is the "Solution explorer". It shows that FAST and FASTlib incompatible!  how could i fix that?
![7](https://user-images.githubusercontent.com/66703137/84434371-2fe27780-ac30-11ea-98e9-fb07aec9e435.PNG)

**Comment by bjonkman** [comment]
This sometimes happens if you've installed the Fortran integrations in the wrong order or you've upgraded Visual Studio.

Right click on the incompatible projects. It should give you a list of options; I don't recall what they all are at the moment, but hopefully one will stand out to you as the correct one to choose for Fortran projects.

**Comment by ChaoREN1994** [comment]
Thanks for your reply.  Now my interest is  more about the following questions.  Do you have any answers for these?  Especially for the question 3?

> You are right about the InflowWind input file. If I changed that and used one in FASTv8, It worked. i used that windows binaries download from the site!
> ![4](https://user-images.githubusercontent.com/66703137/84425668-41248780-ac22-11ea-8c0b-8cf2953ec3ec.PNG)
> 
> Here are some questions about the Openfast and Fastv8
> 
> 1. One is about the exe. files. In Fastv8 , I see there are Fast_x64.exe and Fast_x64d.exe. In openfast, there are also two for x64(Openfast_x64 and Openfast_x64_double). What is the differences?  If using x64 or x64_double, the results of simualtions will be different?


> 2. It is about the AeroDyn module.  There are two files AeroDyn14 and AeroDyn15 in FASTv8.  What is the differences?  Also, I know, for different wind speed , I need to intialize the  rotor speed and pitch angle.  I want to know how much rotor speed and pitch angle I should set for a given wind speed? Does that have a rule or an equation?  Could you give me some references?  In addition, If using AeroDyn15,  sometimes FAST will abort at the beginning or during the Fast simulation due to high attack angle ( I can change the High attack limit in the given file but It also happens). However with AeroDyn14, It will not happen. Thus, I would like to know that the differences between the two AeroDyn is huge or not?
>    ![5](https://user-images.githubusercontent.com/66703137/84427204-d0329f00-ac24-11ea-9e5e-644be9080047.PNG)
>    file)

> 3. It about the 5MW_OC4Jckt_ExtPtfm module. I try to run that but failed. It is also the problem of input file???  How could I fix that (In FASTv8, It does not have this file)? In addition, for the ExtPtfm module, how could I import my new platform matrix using superelement(substructure) method? Do you have any tutorial, technical report or paper about this part?  Thanks!!!
>    ![6](https://user-images.githubusercontent.com/66703137/84427919-eab94800-ac25-11ea-8cc4-ee0c9ee76e69.PNG)
> 
> Any way, thank you very much. Your replys are very useful and really save my life! Looking forward to your responses

**Comment by bjonkman** [comment]
I suggest you start reviewing some of the documentation and perhaps go through some of the exercises from past modeling workshops here: https://wind.nrel.gov/forum/wind/viewtopic.php?f=38&t=653. Also, you will find input files for the current version of OpenFAST on the r-test repository: https://github.com/OpenFAST/r-test/tree/master/glue-codes/openfast.

Then, if you still have questions, start a new issue here or ask a question on the forum so someone with more modeling expertise can help you.

**Comment by ChaoREN1994** [comment]
Ok, thanks a lot!

**Comment by mishtiyak** [comment]
Hello Sir, Ma'am,

I try to use the "windows_openfast_binaries" (Since I do not plan to change any source code) download form https://github.com/OpenFAST/openfast/releases to do regression tests but upon running its shows some error like.. {{
FAST_InitializeAll:SrvD_Init:BladedInterface_Init:The dynamic library
.\../5MW_Baseline/ServoData/DISCON.dll could not be loaded. Check that the file exists in the
specified location and that it is compiled for 32-bit applications.}}

I am new to this tool and trying my level best to get it done but still strugling hard for solution

![image](https://user-images.githubusercontent.com/69219809/94268827-5916e180-ff5b-11ea-8050-303d671ad689.png)

**Comment by andrew-platt** [comment]
@mishtiyak 
If you downloaded the binaries from https://github.com/OpenFAST/openfast/releases/tag/v2.4.0, the controller DLL's you need will be located inside the folder DISCON_DLLS\Win32. You will need to change the location of the DLL in the ServoDyn input files to match where you downleaded the DLL to.

**Comment by mishtiyak** [comment]
Dear Sir @andrew-platt, Issue got resolved. 
Thank you very much for your quick response.

**Comment by mishtiyak** [comment]
Dear Sir/Ma'am,

I am running "5MW_OC3Mnpl_DLL_WTurb_WavesIrr" and I see below warning message stating that the Mach number exceeds 0.3 and the theory is invalid. However, the simulation doesn't abort.

I see this warning message when I run with higher wind speed (i.e 25m/s). Could you please suggest me way ahead.

Thank you

![image](https://user-images.githubusercontent.com/69219809/94355436-adc47480-00a1-11eb-8852-1fce5f059400.png)

**Comment by andrew-platt** [comment]
Did you change the initial blade pitch for the higher wind speed simulation?  If not, the blade pitch is likely around 0 degrees at the start of the simulation which will cause large transients in blade motion initially.

Ideally you set the initial conditions in the ElastoDyn input file (blade pitch, rotor speed etc) to match the steady state conditions for that wind speed.  This will reduce the initial transients of the simulation and likely get rid of this warning. During steady state operation, the blade pitch will likely be around 20 degrees or so (I don't remember the exact value) at 25 m/s wind speed. So I suggest you run steady wind with ramping wind speed to find the those steady state conditions.

**Comment by mishtiyak** [comment]
Dear Sir @andrew-platt, 

Thank you for your quick help. The issue has been resolved now. 
However, I come up with a new issue now.

1. When I run "5MW_OC3Mnpl_DLL_WTurb_WavesIrr" with DT=0.05 I see below error message (However,with DT=0.005, NO error)

![image](https://user-images.githubusercontent.com/69219809/95006956-9e0bd980-0627-11eb-8dbd-f18ef2a56472.png)

2. If running with DT=0.005 is the only solution, do I need to run ANSYS simulations with time step size =0.005 sec too? Actually, i am importing aerodyne forces into ANSYS for FEA analysis purposes.

3. Also turbsim throwing some error with DT=0.005
![image](https://user-images.githubusercontent.com/69219809/95007050-9d277780-0628-11eb-83ad-830ae9dc87e9.png)

4. Is it mandatory to keep the uniform time step size across Turbsim, FAST, and ANSYS for simulation? Earlier I was running Turbsim with DT=0.05 and than FAST' test19 with DT=0.005 and finally ANSYS with DT=0.05. Can I go this way also? Please share your valuable suggestions.

Thanking you

**Comment by jjonkman** [comment]
Dear @mishtiyak,

Here are my answers to your questions:

1. The time step requirements in OpenFAST are dictated by the natural frequencies of the coupled system.  The time step for the OC3-monopile model should be 0.005 s, unless you've disabled features (degrees of freedom) that would permit the use of a larger time step.  Increasing the time step without disabling features is making your model numerically unstable.  Guidelines for choosing time steps in OpenFAST have been discussed many times on our forum: https://wind.nrel.gov/forum/wind/.

2. I gather you are using a one-way coupling to ANSYS, i.e., you are calculating the aerodynamic loads from OpenFAST and applying them to the ANSYS model without transferring information from ANSYS to OpenFAST?  In this case, I would expect you could use distinct time steps between ANSYS and OpenFAST.  If ANSYS runs with a time step 0.05 s, I would run OpenFAST at 0.005 s but output the OpenFAST time-series data at DT_Out = 0.05 s.

3. The TurbSim and OpenFAST time steps do not need to be identical.  Running TurbSim with a time step of 0.005 would require a large amount of memory, which it doesn't appear that you have.  But there is no reason to run TurbSim with time step smaller than 0.05 s.

4. Yes, that is OK; see my answers to questions 1-3.

Best regards,

**Comment by mishtiyak** [comment]
Dear Sir @jjonkman,

Thank you very much for your support. It really matters a lot to me.

Now I have come up with another issue. Could you please provide me some guidance about how to perform Modal Analysis for Test19 (OC3 Monopile)? I want to compare natural frequencies obtained from FAST with my Ansys Model.

Thank you

**Comment by jjonkman** [comment]
Dear @mishtiyak,

The OC3 monopile model in the r-test uses SubDyn to model the substructure (pile).  The linearization functionality in the current master branch of OpenFAST (v2.4) does not support full-system linearization with SubDyn enabled.  That said, we have recently added this capability, which is included in the following pull request, which is still be reviewed before being merged into the dev branch of OpenFAST: https://github.com/OpenFAST/openfast/pull/537.

Until the new functionality is fully vetted, you cannot use a linearization analysis to perform the modal analysis.  As discussed several times on our user forum (https://wind.nrel.gov/forum/wind/), it may be possible to use white-noise wave excitation to derive full-system natural frequencies.

Best regards,

**Comment by mishtiyak** [comment]
Dear Sir @jjonkman,
Thank you very much for your support.

Please have a check on the below points and share your thoughts on the same.

1.Where in the wind turbine structure, the load from the controller is applied?
2. Does it work at the node of the nacelle ? or does it act the nodes of the blades?
3.If I take the force output from the tip of the low-speed shaft, will it include the forces due to the controller's actions as well?

Thanks and Regards

**Comment by jjonkman** [comment]
Dear @mishtiyak,

I'm not sure I really understand your questions, but the electrical generator torque computed by the controller is applied to the generator, and equal and oppositely applied to the nacelle.  The yaw command is applied at the yaw bearing, with a torque equally and oppositely applied to the nacelle and tower top.  The blade-pitch is applied at the blade root/hub.  In the end, the system is coupled, so, you "feel" the effect of the controller throughout the system.

Best regards,
