### ISSUE TITLE
open and edit checkpoint files

### ISSUE THREAD

**Issue by JelmerPolman** [OpenFAST/openfast#329]
Dear all,

is there a way to open and edit checkpoint files? For example, change TMax so that the simulation ends earlier after a restart than what was originally specifiied in the fast input file.

Best regards,
Jelmer Polman

**Comment by jjonkman** [comment]
Dear Jelmer,

Not really very easily.  Checkpoint files are useful mostly for restarting a simulation that otherwise failed e.g. due to a hardware failure.

If a parameter is independent from all other parameters than you could change it in the checkpoint file before restart.  But if other parameters or variables are dependent on a given parameter, changing only that parameter (and not the others parameters or variables dependent on it) would cause problems.  For example, TMax is used to define the length of arrays in HydroDyn, so, changing only TMax in a checkpoint file would result in HydroDyn arrays of the wrong size.

Best regards,

**Comment by JelmerPolman** [comment]
Dear Jason,


I understand, changing the Chekcpoint files would thus almost always results in errors.

Thank you for your help. 


Best regards,
Jelmer Polman
