### ISSUE TITLE
Missing dll files 

### ISSUE THREAD

**Issue by fsamara12** [OpenFAST/openfast#352]
Hi,

I am new to OpenFast and I am just trying to run the examples provided in r-test but I cannot seem to do so.

I downloaded the openfast_x64.exe source code from the GitHub website. I went to OpenFast --> releases --> then downloaded the windows_openfast_binaries.zip from the website. 

I then ran the openfast_x64.exe from that downloaded folder after I extracted the zip file. I opened a command prompt as administrator then changed the directory using the cd command and typed openfast_x64.exe. I got an error saying that the following files are missing: libifcoremd.dll, libifportMD.dll, libmmd.dll, and svml_dispmd.dll. 

I am not sure what to do. Should I download visual studio on my computer? 

Thanks for your help

Farid Samara

**Comment by andrew-platt** [comment]
The OpenFAST executables you downloaded were compiled using the Intel Fortran compiler.  Since it was dynamically linked, there are several dll's that it expects to find on your system. These are available from Intel  as attributable libraries from: https://software.intel.com/en-us/articles/intel-compilers-redistributable-libraries-by-version

For the release v2.1.0, I think you can download and install the 2018 attributable library:  https://software.intel.com/sites/default/files/managed/92/6a/ww_ifort_redist_msi_2018.5.274.zip

**Comment by fsamara12** [comment]
Hi Andrew,
Thanks so much for you quick reply and help. It works now.
Farid

**Comment by andrew-platt** [comment]
You are welcome!

**Comment by Kamil66824** [comment]
i using sonic cd but i can't download visualmd.dll
