### ISSUE TITLE
CMake for Windows Configure Error - MKL and BLAS Libraries Not Found

### ISSUE THREAD

**Issue by andreowhite** [OpenFAST/openfast#372]
Hello @rafmudaf  I am trying to configure but have got a problem.
It is saying I do not have BLAS and MKL libraries installed. But I thought that was installed via intel paralle Xe 2019.  I have attached file showing the errors (Sorry don't know how to copy and paste the image). 

I first thought about downloading libraries separately but I did not bother since I am not sure if that is the right way to proceed.

Can you help.

[Doc1.docx](https://github.com/OpenFAST/openfast/files/3978507/Doc1.docx)

**Comment by andrew-platt** [comment]
My guess is that you need to specify the path to the libraries with the syntax `cmake .. -DBLAS_LIBRARIES="/path/to/blas" -DLAPACK_LIBRARIES="/path/to/lapack"` (see https://openfast.readthedocs.io/en/master/source/install/index.html#id3).

With the intel compilers on windows, you will also need to set the appropriate environment variables so that cmake finds the correct version. There is usually a script located in the intel compiler install directory that sets this (`C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.3.210\windows\bin\compilevars.bat` on my system).  You will need to run from the command window with the appropriate flags (`ia32` for 32 bit) before attempting to run cmake.

**Comment by saeidfn** [comment]
Dear Andrew,
I have a similar problem with MKL libraries that they couldn't be found. I think the second part of your explanation could be my answer, but I couldn't do it. I have "compilevars.bat" on my system, but I don't know what should I do with it.
If you can explain it more, I can pass this step.

**Comment by saeidfn** [comment]
> My guess is that you need to specify the path to the libraries with the syntax `cmake .. -DBLAS_LIBRARIES="/path/to/blas" -DLAPACK_LIBRARIES="/path/to/lapack"` (see https://openfast.readthedocs.io/en/master/source/install/index.html#id3).
> 
> With the intel compilers on windows, you will also need to set the appropriate environment variables so that cmake finds the correct version. There is usually a script located in the intel compiler install directory that sets this (`C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.3.210\windows\bin\compilevars.bat` on my system). You will need to run from the command window with the appropriate flags (`ia32` for 32 bit) before attempting to run cmake.

Dear Andrew,
I have a similar problem with MKL libraries that they couldn't be found. I think the second part of your explanation could be my answer, but I couldn't do it. I have "compilevars.bat" on my system, but I don't know what should I do with it.
If you can explain it more, I can pass this step.

**Comment by andreowhite** [comment]
@saeidfn I am sorry but I have decided to used FASTv8 for my project. Hence I am currently not working with OpenFAST.

AOAW

**Comment by andreowhite** [comment]
@saeidfn I am sorry but I have decided to used FASTv8 for my project. Hence I am currently not working with OpenFAST.

AOAW

**Comment by andreowhite** [comment]
@saeidfn I am sorry but I have decided to used FASTv8 for my project. Hence I am currently not working with OpenFAST.

AOAW

**Comment by andreowhite** [comment]
@saeidfn I am sorry but I have decided to used FASTv8 for my project. Hence I am currently not working with OpenFAST.

AOAW

**Comment by andreowhite** [comment]
@saeidfn I am sorry but I have decided to used FASTv8 for my project. Hence I am currently not working with OpenFAST.

AOAW

**Comment by andreowhite** [comment]
Hello @saeidfn I am sorry but I have decided to used FASTv8 for my project. Hence I am currently not working with OpenFAST.

AOAW

**Comment by andreowhite** [comment]
Hello @saeidfn I am sorry but I have decided to used FASTv8 for my project. Hence I am currently not working with OpenFAST.

AOAW

**Comment by andreowhite** [comment]
Hello @saeidfn I am sorry but I have decided to used FASTv8 for my project. Hence I am currently not working with OpenFAST.

AOAW

**Comment by andreowhite** [comment]
Hi:
I am sorry but I am no longer using OpenFAST for my project. I am using FASTv8 instead.

Regards,
AOAW

**Comment by bjonkman** [comment]
@saeidfn : 
If you are using the Intel compiler with Visual Studio on Windows, you have a few options for building:

1. Open the Intel compiler environment command prompt for the compiler version you want to use:
![image](https://user-images.githubusercontent.com/6108781/90416082-3dbcda80-e06f-11ea-8b6c-50bd3976b0fe.png)
Then in that window, change to the directory where you want to run cmake. If you have installed this compiler including the MKL libraries, cmake should be able to find them without you explicitly specifying their location.

2. The Intel compiler environment that you open through the Windows Start Menu (above) calls a batch script that sets the paths for the compiler. To see what that script is and what its arguments are, open its properties window:
![image](https://user-images.githubusercontent.com/6108781/90416861-41049600-e070-11ea-8a3f-717cab33361a.png)
Using that information, you can call it directly from a batch script. I personally have a batch script that looks like this _(note: I haven't run it in a while, so the cmake commands may be a little out of date for the OpenFAST version you are using.)_:
```
@IF NOT DEFINED Include call "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019.5.281\windows\bin\ipsxe-comp-vars.bat" ia32 vs2017

cmake --config Release -G "Visual Studio 15 2017" ^
 -DCMAKE_BUILD_TYPE=RELEASE ^
 -DBUILD_DOCUMENTATION=ON ^
 -DBUILD_TESTING=ON ^
 ..\.. 

cmake --build . --config Release --target INSTALL
```
I call this script instead of opening the Intel environment from the start menu.

3. You can also just open the Visual Studio solution file included in OpenFAST instead of using cmake: `<OpenFAST>\vs-build-FAST\FAST.sln` and click `Build`.
