### ISSUE TITLE
Orcaflex interface support

### ISSUE THREAD

**Issue by BenjaminMarechalDice** [OpenFAST/openfast#388]
Hi,

I have a simple question : does Orcaflex interface work in OpenFAST?

I haven't found any information in the documentation of OpenFAST on this subject, except that one have to set CMake option ORCA_DLL_LOAD to ON.
However I have found useful documentation for FAST v8 related to Orcaflex interface. Does this documentation also apply to OpenFAST?

Thank you by advance,
Benjamin Maréchal

**Comment by andrew-platt** [comment]
Hi Benjamin,

To my knowledge, the Ocaflex interface module should still work within OpenFAST.  I don't think the underlying coupling methodology in the glue code has changed since converting from FAST8 to OpenFAST.

 As you noted, the documentation in OpenFAST for this feature is lacking.  The FAST v8 documentation should still apply.

Andy

PS: I'm not actually sure why the `OCRA_DLL_LOAD` flag is defaulted to OFF in cmake.  That was a preprocessor directive I added only to simplify the development of the module, but there is no reason for the default to be set to OFF.

**Comment by BenjaminMarechalDice** [comment]
Thank you Andrew for your answer and your support. I take note of what you wrote about `ORCA_DLL_LOAD` option.

Benjamin
