### ISSUE TITLE
Regression Test

### ISSUE THREAD

**Issue by abdoo0** [OpenFAST/openfast#412]
Hello,

I have followed the procedure given in https://openfast.readthedocs.io/en/master/source/testing/regression_test_windows.html . I have built OpenFast using visual studio 2019 and I have the 3 Discon files in place. Nevertheless, when I use python 3 to run the following command "python manualRegressionTest.py ..\build\bin\openfast_x64_Double.exe Windows Intel 1e-5" , all tests fail.
![Capture1](https://user-images.githubusercontent.com/62108008/76537012-307f3c80-648e-11ea-901b-04a25a5684ec.PNG)
![image](https://user-images.githubusercontent.com/62108008/76537095-53115580-648e-11ea-9478-7c3bf0a1b431.png)
I would be thankful for your help.

kind regards,
Abdoo

**Comment by rafmudaf** [comment]
Run a single test with verbose output to get more information on the error:

```
ctest -V -R AWT_YFix_WSt
```

Do you have numpy installed?

**Comment by abdoo0** [comment]
I do have numpy installed 
How do I run a single test with verbose output?

**Comment by rafmudaf** [comment]
Oh with the Python script you can also add a verbose flag, `-v`, and select a case with `-case AWT_YFix_WSt`.

The full syntax is available with `-h`. Check out this section of the documentation: https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#python-driver

**Comment by abdoo0** [comment]
![image](https://user-images.githubusercontent.com/62108008/76543381-7f7d9f80-6497-11ea-8b68-09f25be49ce2.png)
This is what i get ?

**Comment by andrew-platt** [comment]
you have not successfully compile OpenFAST.  what does `make openfast` give?

**Comment by rafmudaf** [comment]
Or the executable doesn't exist at that location that you passed to the script.

**Comment by abdoo0** [comment]
The input Files are copied to a folder called reg_tests inside the build folder where the executable are

**Comment by abdoo0** [comment]
![image](https://user-images.githubusercontent.com/62108008/76546250-367c1a00-649c-11ea-8af0-e7734cc6ebac.png)

**Comment by rafmudaf** [comment]
Nice - you've located the folder containing the binaries. Now match what you've shown here to the command you used to run the tests.

**Comment by rafmudaf** [comment]
@abdoo0 can you update?

**Comment by abdoo0** [comment]
I am really sorry I couldn't get back to you any earlier, Please accept my apologies for that.
I tried doing what you told without any luck (It's probably because I didn't understand probably what should I do). 
I did change the working directory to  "openfast\reg_tests" 
and pasted the following to my python configured cmd " python manualRegressionTest.py ..\build\bin\openfast_x64_Double.exe Windows Intel 1e-5" still I do get that output

**Comment by rafmudaf** [comment]
You're giving the program, `manualRegressionTest.py`, an incorrect path to the OpenFAST binary on your system. The command you have above is copied directly from the documentation without modifying it for your use case. Specifically, your binary isn't called `openfast_x64_Double.exe`, its called `openfast_x64.exe` as shown in your screen shot of the `bin` directory. This is because you've compiled with single precision instead of double precision. So, reformulate the command you're using and think about the information you should pass to the Python script.

**Comment by abdoo0** [comment]
Got it, Thanks a lot for your kindness and  patience !!

**Comment by abdoo0** [comment]
I rebuilt the solution as double and it worked but some tests still fails for some reason 
![image](https://user-images.githubusercontent.com/62108008/76709768-6e8c9280-6712-11ea-8e32-585245030410.png)

**Comment by rafmudaf** [comment]
The Python script doesn't run the Linear test cases, so those are marked "fail" but they actually didn't run. Otherwise, it's not unusual to have a couple or three failing cases. Differences in compile settings, machine type, and compiler version will cause that. If you're interested, you could turn on plotting in the regression test script and visualize the results. See https://github.com/OpenFAST/openfast/issues/335#issuecomment-538102848 for info on that.

**Comment by abdoo0** [comment]
Alright, Thanks again !
