### ISSUE TITLE
Questions about running BeamDyn as a standalone analysis tool

### ISSUE THREAD

**Issue by iiamdone** [OpenFAST/openfast#443]
Dear all:
            I have a question when i going to use BeamDyn as a standalone analysis tool.
            I  am trying to coupled star-ccm+(CFD software) and BeamDyn to do FSI thing, so i was thinking how should i modify the BeamDyn source code to make the applied load from the analysis-subject to BeamDyn change every time-step. By reading the user's code, it said that `BD_InputSolve subroutine in the Driver_Beam.f90 file` should be modify to my satisfied my idea. But  i also notice that `Dvr_5MW_Dynamic` also have the location to input applied force, line25 to line36.
            So my first question is that how should i modify the code to have different applied load base on every time_step. and should i only modify the source code only or also should i modify `Dvr_5MW_Dynamic file line25 to line36` as well. if you have any paper regarding for such thing please share with me.
            Thanks for any help given.

**Comment by andrew-platt** [comment]
I'm a little unclear on your intention.  I see two possible questions here.

1. pass data from StarCCM to BeamDyn, and then return the new blade shape back to StarCCM for the next time step.  In this case you would need to be able to call BeamDyn from StarCCM and pass data back and forth. Does the StarCCM API support calling external codes to calculate new shapes?
2. Take the output forces from a completed StarCCM simulation and feed the time series into BeamDyn as a standalone post processing step.

Of the two options, 2. is the simplest.  This would require modifying the driver to read a time series input file.  At present the driver only handles constant loads (input lines 25-36 in the driver input file).

Option 1 would require writing a wrapper that could be called from StarCCM.  Depending on the language StarCCM can communicate with, you may need to also add a layer to convert the force information from StarCCM into the necessary input structures that BeamDyn uses, and convert the resulting mesh results into something that StarCCM can work with.  Since BeamDyn represents the entire blade as a line, you will likely also need to add the blade shell layer around the resulting position information so that StarCCM has a shell to work with. You will also need to somehow initialize BeamDyn to get the initial blade shape to feed to StarCCM.  This whole process would be rather involved, but likely possible.

**Comment by iiamdone** [comment]
Thanks andrew.

i am sorry not making my intention clear. Here, my intention is option 1, to make two software communicate data at each time step. As your suggestion，this whole process is rather involved. Since the deformation from BeamDyn needs further-step to  process. So i like to list the steps and see if i understand it right.

1.run Star-ccm+, convert the force into "input structure" to BeamDyn
2.run BeamDyn, then output deformation data (i.e. Tip translational deflection; section motion,from node1 to node9) to Star-ccm+. 
3.The whole process need a Macro or something like that to run automatically

so, if i understand it right. At the step 1, the force i  extract from Star-ccm+ is the force as line25-36 in the drive input file required. And i should put and change the force-and-moment data into line25-26 in the drive input file at every time step. Then no code change needed in other source code, as i mentioned before(`BD_InputSolve subroutine in the Driver_Beam.f90 file`), is that right?

At the step 2, actually i haven't figured it out about how to make the model in Star-ccm+ deform and no need to add a shell layer around resulting position.

Step3, the language Star-ccm+ communicate is Java. So such a process need a Java Macro as i think.

Many thanks,
