### ISSUE TITLE
Add coordinate system diagrams to documentation

### ISSUE THREAD

**Issue by andrew-platt** [OpenFAST/openfast#462]
It would be really useful to add diagrams of the various coordinate frames to documentation on `readthedocs`.  For example, how the nacelle (`xn` etc), yaw-bearing/base-plate (`xp` etc), tower (`xt` etc) coordinate systems relate to each other is not always obvious to the users.  Most of this information exists in the FAST 6 users guide, but that is not readily available to most users.

So I propose we add these diagrams into the documentation on `readthedocs`.  Ideally we also include transformation equations between various outputs (coned coordinates the blade coordinates for example).

**Comment by jjonkman** [comment]
Hi @andrew-platt,

I don't disagree, but this issue is a subset of issue #181, where there is already a request to migrate the old FAST v7 User's documentation into OpenFAST readthedocs.  I would include the "Coordinate Systems" section from the "Model Description" chapter of the old FAST v7 User's Guide part of this migration.

Thanks,

**Comment by andrew-platt** [comment]
Closing this issue.  Will post comment to #181
