### ISSUE TITLE
installing openFAST binaries in windows 10

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#463]
Hi openFAST team,

I have downloaded the openFAST binaries for windows 10. I have also installed the intel libraries, but when I try to install the executable, the command window briefly opens and then nothing happens. Any fixes for that ?

**Comment by rafmudaf** [comment]
Please provide more information. You can start by filling out this form:

**Bug description**
<A clear and concise description of the bug.>

**To Reproduce**
<Update the following list with your specific information.>
Steps to reproduce the behavior:
1. Compile with '...'
2. Run '...' case with '...' settings
3. Open '...' output
4. See the error

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots, if applicable**
<Add screenshots to help explain your problem.>

**OpenFAST Version**
<Please provide as much detail as possible including git commit. The best information is a screenshot of the OpenFAST system description that prints when running OpenFAST:>

```
**************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.0.0
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
  - Date: Nov 27 2018
  - Time: 17:19:38
 Execution Info:
  - Date: 11/29/2018
  - Time: 10:52:28-0700
```

**System Information (please complete the following information):**
 - OS: <e.g. Ubuntu 14.04 or macOS 10.12>
 - Compiler: <e.g. GFortran 4.4>
 - Compiler settings: <e.g. CMake flags or other settings>

**Additional context**
<Add any other context about the problem here.>

**Comment by andrew-platt** [comment]
@tchatte3 when you attempt to _install the executable_, how are you doing this? The executables provided are not installation executables, but rather the full OpenFAST executables.

These should be run through a command or powershell window one Windows 10. So if you double click on the executable file through the file explorer, it will briefly open a command window then exit since no input file name was given.

**Comment by tchatte3** [comment]
@rafmudaf I am closing this issue here and reopening it as a bug.

**Comment by tchatte3** [comment]
@andrew-platt I understand that. OK, so that solves the problem, I closed the issue.

**Comment by saeidfn** [comment]
> @tchatte3 when you attempt to _install the executable_, how are you doing this? The executables provided are not installation executables, but rather the full OpenFAST executables.
> 
> These should be run through a command or powershell window one Windows 10. So if you double click on the executable file through the file explorer, it will briefly open a command window then exit since no input file name was given.

Dear Andrew,
I installed the required Intel Fortran compiler, so what is the next step to run openfast_x64.exe??

**Comment by jjonkman** [comment]
Dear @saeidfn,

I've responded to your related question in #434.

Best regards,

**Comment by ArezooN** [comment]
Hi, I have also the tchatte3's problem. In AeroDyn standalone. 
1. for running I have to install the visual studio + Intel fortran?
2. If I download the example files in https://openfast.readthedocs.io/en/latest/source/user/aerodyn/appendix.html#ad-appendix  page and place  with Aerodyn.exe, it will be run??

**Comment by jjonkman** [comment]
Dear @ArezooN,

 NREL has not provided a precompiled binary executable for the standalone AeroDyn driver, so, you must compile this from the source code and compile scripts that NREL has provided.  If you are using Windows, I find Visual Studio + Intel Fortran the most straight forward.  Documentation on compiling is found here: https://openfast.readthedocs.io/en/main/source/install/index.html.

Once you've compiled the standalone AeroDyn driver, I agree that the executable can be run with the example files that you reference.

Best regards,
