### ISSUE TITLE
Questions for the r-test 

### ISSUE THREAD

**Issue by ChaoREN1994** [OpenFAST/openfast#467]

**Comment by ChaoREN1994** [comment]
Dear,all
It is about the modules “5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth” and “5MW_OC4Jckt_ExtPtfm”.  I did not compile the openfast. I used the windows binaries download from  https://github.com/OpenFAST/openfast/releases  to run the two modules. But they both failed. 

![1](https://user-images.githubusercontent.com/66703137/84439379-5efce700-ac38-11ea-8a87-b4ca02710fd4.png)
![2](https://user-images.githubusercontent.com/66703137/84439386-63c19b00-ac38-11ea-85d3-5f9e624adc59.PNG)



For “5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth” , I try to replace the InflowWind input file by one used in FASTv8 , It worked.

![3](https://user-images.githubusercontent.com/66703137/84439404-6c19d600-ac38-11ea-9ea8-6f23624117a8.PNG)


But for the “5MW_OC4Jckt_ExtPtfm” module,  I think it is also the problem of input file?? But in r-test site https://github.com/OpenFAST/r-test/tree/master/glue-codes/openfast, I can not find the input file. In addition, for the ExtPtfm module, how could I import my new platform matrix using superelement(substructure) method? Do you have any tutorial, technical report or paper about this part? Thanks!!!

**Comment by andrew-platt** [comment]
You are likely looking at the wrong version of r-test.  Try this one: https://github.com/openfast/r-test/tree/283707d5f3a9d8e23acd08c9521fba81d275530a

**Comment by ChaoREN1994** [comment]
Thanks for your reply!  I did follow the steps in  https://openfast.readthedocs.io/en/master/source/testing/index.html#configuring-the-test-suite. Here are the files I cloned.
![1](https://user-images.githubusercontent.com/66703137/84441210-a9cc2e00-ac3b-11ea-9889-ff4ec5d657f9.png).

But there are also the same problem. And in this one  https://github.com/openfast/r-test/tree/283707d5f3a9d8e23acd08c9521fba81d275530a ,  I did not find the this file "5MW_OC4Jckt_ExtPtfm". It has been deleted?

**Comment by andrew-platt** [comment]
I'm not entirely sure where you cloned the above files from. The `5MW_OC4Jckt_ExtPtfm` test case is not yet released.  We have that test case in a branch that we will be merging into OpenFAST in the future (#350 which uses https://github.com/OpenFAST/r-test/tree/pullrequest/350/glue-codes/openfast). It should be noted that there are changes in the input files for this unreleased feature that are not compatible with OpenFAST v2.3.0.

**Comment by ChaoREN1994** [comment]
Ok, thanks!  It will be released in this year or not ?  Thanks for your reply!!!

**Comment by rafmudaf** [comment]
@ChaoREN1994 `5MW_OC4Jckt_ExtPtfm` exists in the `dev` branch but not the `master` branch of r-test. Generally, the `dev` branch will be up-to-date and contain slightly more new features (or in this case, new models and model updates) than the `master` branch.

That being said, the compiled binaries you downloaded are for v2.3.0 which is the latest commit on the OpenFAST `master` branch. So, they don't have the required code recently added to the `dev` branch to parse the inputs for ExtPtfm. Thats why you're seeing that error.

For the OC4 Jacket case, I don't know why an older InflowWind input file should work. In fact, there are no [documented changes](https://openfast.readthedocs.io/en/master/source/user/api_change.html) to the InflowWind API since FAST 8.

**Comment by rafmudaf** [comment]
For what its worth, there is a corresponding version of r-test for each version of OpenFAST. In your case, all of the files at https://github.com/OpenFAST/r-test/tree/v2.3.0 will work.

**Comment by ChaoREN1994** [comment]
Thanks for your reply.  You are really nice.  I am looking forwaid to  the new version of Openfast with 5MW_OC4Jckt_ExtPtfm module. Thanks again!!!
