### ISSUE TITLE
Feature request: improved installation docs

### ISSUE THREAD

**Issue by jennirinker** [OpenFAST/openfast#474]
**Is your feature request related to a problem? Please describe.**
Perhaps clarify that the link to the redistributables are *installers* not the libraries themselves. I think users who aren't familiar with MSI versus DLL might just unzip the file and not run the installers. Also, you need to close/restart your command prompt if you have one open.

**Describe the solution you'd like**
Update Section 2.1 of docs to include these note, and update text in the releases.

**Describe alternatives you've considered**
Just leave the docs as they are.

**Comment by rafmudaf** [comment]
Hi @jennirinker - The items we distribute via GitHub Releases are the OpenFAST executables (32 bit single precision, 64 bit single precision, and 64 bit double precision) themselves and the controller library dll's (32 bit and 64 bit). After downloading the .zip file and extracting the contents, those executable can be run directly. The only caveat is that since they are compiled with the Intel Fortran compiler some additional Intel libraries should be installed, if they aren't already.

So that I can understand where the documentation is lacking, can you describe in more detail what's happening on your end after downloading the .zip file?

**Comment by andrew-platt** [comment]
@jennirinker if I understand correctly you referring to the Intel MKL redistributables. I can update the section 2.1 info on the MKLs.

**Comment by jennirinker** [comment]
yeah sorry, i submitted the issue on the way out the door or i would have made a pull request with what i meant. give me a few minutes to whip something up. :)

**Comment by jennirinker** [comment]
@andrew-platt @rafmudaf see the suggested text in the PR. Note that I also suggest in the PR suggestions to the release text that reference the docs. Just think it will be a little bit more straightfoward for unfamiliar users.

**Comment by andrew-platt** [comment]
@jennirinker Thanks for PR #475!  That is good clarification text.

**Comment by jennirinker** [comment]
My pleasure -- thanks for making the docs open so I can contribute. :) Will you move forward with the PR, or is there something else that should be done from my side?

**Comment by andrew-platt** [comment]
Thanks for doing this!  Merged!
