### ISSUE TITLE
Compiling OpenFAST for Matlab: OpenFAST-Simulink file is not built

### ISSUE THREAD

**Issue by iman-tepsco** [OpenFAST/openfast#490]
Hello!

I intend to use OpenFAST in Simulink. I have two questions regarding this:

1. According to my understanding, to make the S-Function I need to compile OpenFAST first, and then using "create_FAST_SFunc.m" I can make the file. 

I did what is written in [this link](https://openfast.readthedocs.io/en/master/source/install/install_vs_windows.html), but I was not successful to compile OpenFAST. The "Build" process in Visual Studio finished without an error, as:

```
5>FAST - 0 error(s), 0 warning(s)
========== Build: 4 succeeded, 0 failed, 0 up-to-date, 1 skipped ==========
```

The skipped one is actually the OpenFAST-Simulink file. The output of the VS writes:

```
4>------ Skipped Build: Project: OpenFAST-Simulink, Configuration: Debug_Matlab x64 ------
4>Project not selected to build for this solution configuration 

```
I am not sure what the problem is. 

The programs I am using are:
- Visual studio 2019 community
- Intel parallel studio xe 2020 update 1
- Git for windows (2.27.0) 64 bit

(It should be noted that I am new to Visual Studio and Fortran.)

2. I want to know if a Simulink file of ROSCO is available. 

Thank you very much for your help in advance. 

Cheers,
Iman

**Comment by jjonkman** [comment]
Dear @iman-tepsco,

Perhaps something is not set up properly in the "Debug_MATLAB" configuration (bug I'm not sure; I've never tried to use it).  But is there a reason you've selected a debug configuration?  Does selecting the "Release_MATLAB" configuration (which I'd recommend that you always use when compiling the OpenFAST-Simulink interface) work for you?

Regarding ROSCO, I'm not aware that a corresponding Simulink implementation of the controller is available, but I would suggest asking that question in the ROSCO repository (https://github.com/nrel/rosco) rather than here.

Best regards,

**Comment by iman-tepsco** [comment]
Dear Jason, 

Thank you so much for your answer. 

I set the configuration on "Release_MATLAB", here is what I got:

```
5>OpenFAST-Simulink - 0 error(s), 0 warning(s) 
========== Build: 4 succeeded, 0 failed, 0 up-to-date, 1 skipped ========== 
```

The skipped one now is the OpenFAST.exe itself: 

```
4>------ Skipped Build: Project: FAST, Configuration: Release x64 ------
4>Project not selected to build for this solution configuration 
```

What do you think is the problem now?

Best,
Iman

**Comment by bjonkman** [comment]
That is expected behavior. 

The `Release_Matlab` configuration is expected to build the DLL for Simulink, not the OpenFAST executable, so it skips the FAST project that creates OpenFAST.exe. Likewise, when you choose `Release` configuration, it will build the OpenFAST executable but skip OpenFAST-Simulink project that builds the DLL. So, having a project `skipped` is not an error.

Did it generate the DLL you need for OpenFAST in Simulink?

**Comment by iman-tepsco** [comment]
Dear Bonnie, 

Thank you so much for your explanations.

I followed the instruction, and could successfully build the DLL and the S-Function. 

Thank you very much for your help. 

Sincerely,
Iman
