### ISSUE TITLE
Difference in simulation results

### ISSUE THREAD

**Issue by TiasaGhosh** [OpenFAST/openfast#518]
Hello Everybody!
I have finally managed to run OpenFAST with Cygwin on my Windows system and have been running the test cases to check the results against the old version of FAST (FASTv8.16). I am running the testcase 24 which is the 5MW NREL with OC3 Hywind Spar. I have kept every input file constant. When I run my case in OpenFAST, the results vary with FASTv8.16 simulation results.
I have taken the variable PtfmHeave (Platform heave) for both cases and plotted the difference in numerical values. The graph is plotted in red as shown in the attachment.
![ptfmhv](https://user-images.githubusercontent.com/66112322/89177927-c9713a00-d58c-11ea-8dbe-3d1ced9b53e7.png)

the individualresults are shown as:
![Anmerkung 2020-08-03 134436](https://user-images.githubusercontent.com/66112322/89179190-8795c300-d58f-11ea-8c08-97cc18a37499.png)

blue for FASTv8.16 and OpenFAST in red.
the difference goes upto 1m for heave motion. I am aware there have been upgradation in the code which have resulted in difference of these values, but I am curious to know if there are any particular reason for this deviation? any new scenario considered for the calculation or updated calculation methods.

Thanks! :)

**Comment by jjonkman** [comment]
Dear @TiasaGhosh,

Is this difference simply the result of different wave-elevation time series between the two versions, per issue https://github.com/OpenFAST/openfast/issues/89, which is being fixed in PR https://github.com/OpenFAST/openfast/pull/508?

Best regards,

**Comment by TiasaGhosh** [comment]
Hello Dr. jonkman,
Thank you for your prompt response. I read the issues you stated and the subsequent solution provided by Rafmudaf.
I will surely try to use RANLUX in HydroDyn module for verifying OpenFAST results across other OS.
But, what I understood from the links you provided is that RanLUX is not implemented for Hydrodyn module in FASTv8.16.
So even if I implemented this added feature in OpenFAST, the difference is still supposed to exist between OpenFAST and FAST v8.16 I guess. So in that case, would I assume the values of OpenFAST to be more accurate? 
thank you again! :)

**Comment by jjonkman** [comment]
Hi @TiasaGhosh,

We do not intend to make further changes to FAST v8.16, so, using RANLUX rather than a built-in pseudo-random number generator will improve the comparison of wave elevations when comparing OpenFAST solutions across different compilers/platforms, but it will not improve the comparison to FAST v8.16.  To compare OpenFAST and FAST v8.16, you should use the same compiler and platform.  Are you using the Windows binaries provided with FAST v8.16 or did you compile yourself?  Likewise for OpenFAST?

RANLUX is not "more accurate" than the built-in pseudo-random number generators; its just not compiler/platform dependent.

Best regards,
