### ISSUE TITLE
CompInFlow 1 vs CompInflow 2

### ISSUE THREAD

**Issue by tchatte3** [OpenFAST/openfast#519]
Hi openfast development team,

WhenI am using CompInFlow = 1, the inflow wind is directly supplying the inflow velocity U_infty
![image](https://user-images.githubusercontent.com/14302216/89336955-2db4fc00-d668-11ea-8f3c-4cdea481aa93.png)

that is being used to compute inflow angle for the BEMT iteration. 

When I am using CompInFlow = 2, as with Nalu-wind other CFD code, I guess openfast is receiving the induced velocity at the actuator lines. So does the formula above is changing during the computation of \phi, that in the numerator instead of U_infty(1-a), now we are supplying U_induced? Any thoughts, suggestions.

Also, when Computing C_p, C_t, is it differently computed based on CompInFlow = 1 vs CompInFlow =2? 
What velocity is used in the denominator for InFlowWind = 1 vs InFlowWind = 2?

Any help?

Best Regards,

**Comment by ebranlard** [comment]
For BEM simulations, if `WakeMod=0` then `a` and `a'` are 0 in your formula, otherwise when `WakeMod=1` they will have some values. 

For CFD simulations, AeroDyn runs BEM with `WakeMod=0`, which means the inductions are zero, but, the CFD effectively overwrites the `Uinfty` , with the value from the CFD at the rotor. The flow angle is then "correct". 

Note that some output of AeroDyn are not provided when running with CFD. Also, the outputs that relies on the Free stream might be different because of the "free stream replacement". 

I hope that helps!

**Comment by tchatte3** [comment]
@ebranlard Thank you for the sclarification. This is very detailed and clears all the doubt. I really appreciate taking time to resolve this doubt. 

Best Regards,
Tanmoy
