### ISSUE TITLE
Error in configuration while running CMake for OpenFast 

### ISSUE THREAD

**Issue by jsurabhi501** [OpenFAST/openfast#525]
Hello,
I am installing OpenFast for my master thesis topic. I am following documentation and in 2.2.4 section facing the following error while running CMake. Please guide me on how to solve this.

![image](https://user-images.githubusercontent.com/68113824/90133553-f92ff700-dd6f-11ea-84fa-81ed17e811cb.png)

**Comment by rafmudaf** [comment]
Do you need to compile the software? For Windows, we distribute precompiled binaries as described in the installation section of the documentation: https://openfast.readthedocs.io/en/master/source/install/index.html#download-binaries.

**Comment by jsurabhi501** [comment]
Hi,

Yes, I need to compile the files.

Also, can you please provide any user guide on how to run openfast? I am
confused about how to run input files in openfast.

Awaiting your reply.

**Comment by andrew-platt** [comment]
Start here for compiling from source: https://openfast.readthedocs.io/en/master/source/install/index.html#compile-from-source

Since OpenFAST does not have a graphical interface, you will need to run it from the command prompt:

```
openfast <InputFile.fst>
```

where `<InputFile.fst>` is your main input file for OpenFAST and `openfast` is your compiled OpenFAST executable.

**Comment by jsurabhi501** [comment]
I have installed the Fortran compiler but still, I am getting the same error.

**Comment by bjonkman** [comment]
Please see this issue for help in getting cmake to find your MKL libraries on Windows with Intel Fortran: https://github.com/OpenFAST/openfast/issues/372#issuecomment-674973046
