### ISSUE TITLE
Problems with ExtPtfm inputs

### ISSUE THREAD

**Issue by engenheirovitor** [OpenFAST/openfast#549]
Cordially compliment to all OPENFAST developers and collaborators
I am writing my Doctor Thesis, and I am massively using the family of program: Fast and open fast.

I have a problems with ExtPtfm inputs. The last file (R-test 2.3.0) doenst exist this one.
And the R-test-master have one, but doenst work.

Could you help me?

The ExtPtfm code is working in current version open fast?
If yes, where can I download inputs for ExtPtfm. 
I am focus on change stiffnes and mass matrix on the base

Thank you

**Comment by ebranlard** [comment]
Hi, 
The new ExtPtfm implementation was added in OpenFAST 2.4, and the r-test are at the same version. You should be able to run the following test case if you update your OpenFAST binary: 

https://github.com/OpenFAST/r-test/tree/master/glue-codes/openfast/5MW_OC4Jckt_ExtPtfm

You can change the mass and stiffness matrix of the file `ExtPtfm_SE.dat` provided in the r-test example.  You can read/write input files using my python library [weio ](https://github.com/ebranlard/weio/) for instance. 
 
You can find some additional documentation in the pdf mentioned in the following pull request:   https://github.com/OpenFAST/openfast/pull/344

I hope that helps!

**Comment by PM1980** [comment]
Dear sirs,

I have some questions concerning the 5MW_OC4Jckt_ExtPtfm test case. To my understanding this new module enables the superelement approach with 6x6 stiffness, mass ,and damping matrices defined at the tower bottom (and load vector as well). This aspect modifies ElastoDyn boundary conditions and it is a new feature in OpenFast v. 2.4.0. 

I'm currently using the following paper as reference "Superelement reduction of substructures for
sequential load calculations in OpenFAST" by Branlard et al. (2020), and SubDyn user's and theory guide. 

Some specific questions related to ExtPtfm module:

1. I figure that the superelement matrices are of order 6 and obtained through external software (e.g. FEM). This reduction is based on the top node of the substructure, positioned at the tower bottom. On the other hand, the current 5MW_OC4Jckt_ExtPtfm test case presents superelement matrices of order 31 (and readme.md points to 31 degrees of freedom). I don't know what is happening in this case. Perhaps this reduction includes additional nodes in the substructure that go beyond a single node at the interface? 

2. If ExtPtfm module enables a larger selection than the interface nodes, how are these ordered? The first 6 degrees of freedom are related to the tower interface and the remaining are additional nodes for the dynamic reduction? This leads to ElastoDyn coupled to more than 1 substructure node?

3. Since ElastoDyn is based on user provided mode shapes (modes 1 and 2, 6th order polynomials), and these depend on the substructure flexibility, what is the recommend procedure for a superelement usage with ExtPtfm module? Bmodes as a starting point with Kbbt and Mbbt input as substructure's equivalent stiffness and mass matrices? Followed by an update of ElastoDyn mode shapes?

4. 5MW_OC4Jckt_ExtPtfm test case can be modified for the inclusion of wind loading? Is this as simple as switching the corresponding flags to 1 and including the required input files path on the *.fst file?  

Please feel free to correct if my interpretation is wrong. I'm deeply grateful for your support.

Regards,

Paulo

**Comment by ebranlard** [comment]
Dear @PM1980

I'll attempt to answer your questions below:

1. The Craig-Bampton reduction, condenses the full set of degrees of freedom (DOF), to a set of Guyan DOF (or leader DOF), and Craig-Bampton DOF (constrained mode shapes).  The methodology is general, but for the particular case of ExtPtfm, we can only have 6 Guyan DOFs, corresponding to the 6 DOFs at the tower bottom node as you mentioned. The other 25 DOFs that you see in the example, are Craig-Bampton modes, representing the mode shapes of the structure when clamped at the interface. For simplicity, you can use the 6 Guyan DOFs only, but you get more and more dynamics of the structure if you include more Craig-Bampton modes. ExtPtfm assumes that the first 6 DOFs are the Guyan DOFs, ordered as Surge Sway Heave, Roll Pitch Yaw. The other DOFs are Craig-Bampton modes. The content of the Superelement file can be generated using a Finite-Element software, by performing a Craig-Bampton reduction of the substructure with the tower bottom node as interface node. 

3. The methodology would indeed be the same as with SubDyn, and facilitated if the FEM software outputs the equivalent rigid body mass and stiffness matrix of the substructure.

4. You are correct. You also need to provide `AeroFile` that links to an AeroDyn model of the rotor. 

I hope that helps,

Emmanuel

**Comment by PM1980** [comment]
Dear Emmanuel,

Thanks for your prompt reply. Sure it helped a lot. 

Just one more question:

The current 5MW_OC4Jckt_ExtPtfm case (OpenFast v. 2.4.0) doesn't include aerodynamic loads. But I've noticed in your paper (Branlard et al., 2020) that there is an analysis with aerohydrodynamic loading (section 4.4, pag. 9). I would be more than happy to reproduce these results. Do you mind sharing the input files for this specific case?

If this is not possible, then are these the required steps for any other R-test case modification, where the user defines external platform parameters?

1. Set CompSub flag value to 2 and provide the SubFile input path to ExtPtfm.dat in the *.fst file;
2. Provide ExtPtfm.dat file which points to the superelement data;
3. Provide the ExtPtfm_SE.dat file with the corresponding superelement matrices and load vector. 

Thank you!

Regards,

Paulo

**Comment by ebranlard** [comment]
Hi Paulo,

I've edited the message of #344 and added a zip file with the "Wind Wave" test case presented in the article (Compatible OpenFAST 2.4). The turbulence box is too big to be added, to be added to the zip file, so you would need to run TurbSim to generate the ".bts" Wind file in the folder "Wind". As a note, this test case uses AeroDyn14. You can use other `r-tests` for examples using AeroDyn 15. 

You are correct regarding the steps needed. Please note that you will need different superelement files for each sea state simulated. The structure and matrices may be the same, but the load vector would change since the hydrodynamic forces will be different for a different sea state.  The example provided in the zip file is for the sea state corresponding to the wave elevation given in `data_OF/A001_SURF_PROF.elev`. The load time series should be calculated by the FEM software, and outputted into the ExtPtfm superelement format. 

Best regards,

Emmanuel

**Comment by engenheirovitor** [comment]
@ebranlard 
Thank you for this big help. You was very fast.
I am working with Superelement in wind turbine, and I am using open fast.
Best regards

**Comment by kashyap5794** [comment]
Is there a possibility to include seismic load case using the extptfm module for different platforms along with wind and wave scenarios? 
I am new to openfast and had been using only FAST v7 seismic module for my thesis so far. Guidance shall be helpful. 

Thanks
Subham

**Comment by jjonkman** [comment]
Dear @kashyap5794,

What do you mean by "different platforms"?  Are you referring to fixed-bottom or floating offshore substructures?

The external platform (ExtPtfm) module of OpenFAST provides an interface for a user-defined superelement representation of the substructure.   What is accounted for in the superelement (substructure type, wave/seismic loading) will depend on how you deriving the super element.  Are you using a specific software to derive the super element?

Best regards,

**Comment by kashyap5794** [comment]
Dear Sir, 

I don't know the concept of super elements at the theory level. Are there any simple examples that illustrate it using some simple systems? Do you have any textbook references for it?
Ideally, I wish to include various bottom-fixed support structures such as a monopile, tripod, jacket, and suction caisson. I am not aware which software packages can give me super elements as well at the moment. Can you recommend some software packages for the same?

I am kind of stuck with the implementation of seismic loads in openfast for quite some time with no guidance at my disposal. It would really help if you could help. 

Thanks 
Subham

**Comment by ebranlard** [comment]
Hi @kashyap5794, the following [paper ](https://iopscience.iop.org/article/10.1088/1742-6596/1452/1/012033) goes over some of the theory behind superelements and how they are typically used: . You most likely need a finite element software (it's quite easy to perform a Craig-Bampton reduction of a FEM model, see for instance this [python script](https://github.com/ebranlard/welib/blob/dev/welib/FEM/reduction.py)), and I would think most FEM software can produce superelements. The additional complexity is that you need a software to compute the hydrodynamic and soil loads on your FEM model, your superelement should contain time series of your loads projected onto your reduced model (to indeed account for hydrodynamics and soil). You'll also have to be able to simulate the earthquake with this software. 

In the paper mentioned above, our co-authors used the software package [SACS ](https://www.bentley.com/software/sacs-offshore-structure/) from the commercial company Berkeley. I believe [OpenSees ](https://opensees.berkeley.edu/) (from Berkeley university) and [SAP2000 ](https://www.csiamerica.com/products/sap2000) are other alternatives, but I have never used them. I think they can do the FEM+loads and maybe the earthquake part, but I'm not sure. Maybe others will have other ideas.
