### ISSUE TITLE
Need help with Turbosim

### ISSUE THREAD

**Issue by SudharsanKalidoss** [OpenFAST/openfast#581]
Hi everyone,

  I'm new to OpenFAST. I'm trying to run 5MW reference  wind turbine with monopile support. In tutorial case files, the wind is given for 60 s. I want to increase the duration of the wind data. I tried altering the .inp file and run Turbosim. I encountered with invalid logical input file. I compiled the Turbosim exe through vbproj file available with OpenFAST. I'm not sure whether this is the right way to compile or not? 

Can someone help in this regard?

Thanks
Sudharsan
![wind_data](https://user-images.githubusercontent.com/17265645/98164107-c8181c00-1eb1-11eb-846f-0da1c87aba06.png)

**Comment by jjonkman** [comment]
Dear Sudharsan,

It looks like you are running an example TurbSim input file from the OpenFAST r-test by executing TurbSim compiled from the OpenFAST repository.  The problem here is that the TurbSim input file you are running is quite old--compatible with TurbSim v1.50--and TurbSim within OpenFAST requires a newer file format.  TurbSim within OpenFAST is based on TurbSim v2.00 from FAST v8.  Unfortunately, the TurbSim documentation and regression tests have not yet been migrated from FAST v8 to OpenFAST per issue https://github.com/OpenFAST/openfast/issues/176.  However, you can find the old archive of TurbSim v2.00 from FAST v8 with this information here: https://drive.google.com/file/d/1eCvgoOnvJrxsMgXxewDQFBQ5w3k3l_WB/view?usp=sharing.  Or if you prefer, you can find the old archive of TurbSim v1.50 here: https://drive.google.com/file/d/1QCRdEhsvHBLulFA0ZGNgb3q_Zvche1ps/view?usp=sharing.

Best regards,

**Comment by SudharsanKalidoss** [comment]
Hi Jonkman,

  I tried with TurbSim v1.50 and it worked. Thank you for your help.

Regards,
Sudharsan
