### ISSUE TITLE
Need a Way to Compile the FAST Dynamic Library for Calling OpenFAST within Simulink

### ISSUE THREAD

**Issue by jjonkman** [OpenFAST/openfast#59]
The Simulink interface to FAST consists of Simulink calling the FAST S-Function, which calls the FAST dynamic library.  While the OpenFAST repository includes the glue code and MATLAB script for compiling the FAST S-Function, the OpenFAST repository doesn't include a CMake script or VS-Build solution for compiling the FAST dynamic library.

Related to this missing build, is a misplacement of the FAST_Library.f90 source file.  FAST_Library.f90 is to the FAST dynamic library for the Simulink interface as FAST_Prog.f90 is to compiling the OpenFAST executable.  FAST_Library.f90 is currently included in the modules-local/fast-library/src directory; however, it seems like FAST_Library.f90 should be moved to the glue-codes/Simulink directory.

**Comment by sayerhs** [comment]
Wouldn't turning on shared library `ON` in CMake allow using `openfastlib.so` with Simulink?

**Comment by ghaymanNREL** [comment]
@sayerhs, yes you are correct (I didn't know this until reading your comment), for cmake builds, but there is currently no equivalent build for visual studio.  (The vs-build of the FASTlib, does not include the FAST_Library.f90 file, and the vs-build output is only a static library)

**Comment by bjonkman** [comment]
A couple of differences with the `openfastlib.so` as it seems to be implemented in CMake:
- It should use the Matlab libmex library so that all messages that normally get written to the screen appear in the Matlab command window. On Windows with Intel Fortran, we replace SysIVF.f90 with SysMatlab.f90 (which calls Matlab routines for printing) and link with libmex.lib from the Matlab installation. As far as I know, no one has modified the other Sys*.f90 files for other platforms/compilers.
- It should use the `COMPILE_SIMULINK` preprocessor directive.

Instructions for how this is supposed to work are on pages 54-55 of the [FAST8 ReadMe](https://wind.nrel.gov/nwtc/docs/README_FAST8.pdf)

**Comment by bjonkman** [comment]
One other thing to note here is that FAST_Library.h is used in FAST_SFunc.c (which gets compiled in MATLAB as a mex file). It looks like the interfaces defined in the header file have changed, but the code that calls those routines in FAST_SFunc.c has not.

**Comment by gantech** [comment]
Thanks @bjonkman. 

@ghaymanNREL This may have to be addressed to have Simulink work again with OpenFAST. I was not aware that Simulink uses the "OpenFOAM" module in OpenFAST.

**Comment by bjonkman** [comment]
@rafmudaf , since this has been merged into OpenFAST/dev I think this issue can be closed.
