### ISSUE TITLE
Does current AeroDyn still support the APIs of AeroDyn v13.0

### ISSUE THREAD

**Issue by yub-ship** [OpenFAST/openfast#608]
Hi,

We are promoting a cosimulation system which involves AeroDyn. We connected our program to AeroDyn v13.0 by referring to the APIs explanations from the file of AeroDyn v13.0 (
[March312010UpdatesAndNewAeroDynInterface.pdf](https://github.com/OpenFAST/openfast/files/5654165/March312010UpdatesAndNewAeroDynInterface.pdf)
). 

However, from the openFAST source code in the GitHub, just about the AeroDyn, we saw there are lots of new files having been added since AeroDyn13.0. So, we wonder if the current AeroDyn still has the same interfaces as AeroDyn v13.0? If not, is there any documents about the new interfaces? Or are there still interfaces for current AeroDyn to connect with software other than FAST?

Many thanks for your reply in advance. We hope we could connect to the latest version AeroDyn. If it is not possible, we may face the task of switching to another aerodynamic software module depending on the customer's requests.  

Thanks again.

Kind regards

**Comment by jjonkman** [comment]
Dear @yub-ship,

The AeroDyn v13 interface was last supported by the older FAST v7 software.  In FAST v8 and now OpenFAST, all modules follow the requirements of the FAST modularization framework in terms of their interface, as outlined in the NWTC Programmer's Handbook: https://drive.google.com/file/d/1bDV1fBkiZUWs6Tkzb6nhCMUQvHpN_OtM/view?usp=sharing.

Both FAST v8 and OpenFAST support interfaces to both AeroDyn v14 and AeroDyn v15.  AeroDyn v15 was written from scratch and is fully compatible with the FAST modularization framework.  AeroDyn v14 was based AeroDyn v13 and generally the follows framework, but includes a few "hacks" to support the functionality that was previously available in AeroDyn v13.  Regardless, we are putting all of our development efforts into AeroDyn v15 and plan to deprecate AeroDyn v14 soon per issue #93.  So, I would encourage you to interface your software with AeroDyn v15 moving forward.

By the way: which company are you from and which software are you interfacing AeroDyn with?

Best regards,

**Comment by yub-ship** [comment]
Hi, jjonkman,

Thank you very much for your answer.

I am from Ansys. More about the project we are doing, I think your colleague, Senu, knows about it. He used to provide us with a testing model. If you are interested, I could send an email directly to you to explain it. (Don't worry about the email address, I found it on NREL's website.)

For double-checking, to ensure I understand correctly, AeroDyn v15 and AeroDyn v14 both follow the modularization framework described in the Programmer's Handbook (thanks for the link) and no longer support the AeroDyn v13 interface. This Programmer's Handbook is about 8 years ago, I wonder if there are any updates?

Besides, no matter what the form of the AeroDyn's interface becomes, I wonder if the definition of the input variables has changed or not, for example, the HubOrientation, BladeRootOrientation, Node's orientations, and also their Positions. If those have changed, I wonder if there is any document explaining them? (Unfortunately, from the source code comment, I am still not very clear about their definitions, like, what does DCM mean?)

Thank you for your help again!

Kind regards

**Comment by jjonkman** [comment]
Hi @yub-ship,

OK, thanks for providing some background.  It has been a while since I talked to Senu about ANSYS, so, I'm a bit out of date.

Yes, both AeroDyn v15 and AeroDyn v14 follow the modularization framework.  AeroDyn v15 is fully compatible and AeroDyn v14 includes a few "hacks" to make it compatible, but AeroDyn v14 will be deprecated soon anyway.

The Programmer's Handbook has not been updated recently, but most of it still generally applies.  Some details have changed, e.g., the swap from SVN to git, but generally the material is still valid and any changes from what is spelled out there to what is done now should be fairly obvious.

Most inputs and outputs from AeroDyn v15 reside on mesh data structures.  These are documented in an internal AeroDyn v15 implementation plan.  This document is not tracked on this github site, but a slightly outdated version is available here: https://github.com/old-NWTC/AeroDyn/blob/master/Documentation/AeroDynMesh.docx (again, recent updates should be fairly obvious).  By DCM, we mean a direction-cosine matrix, i.e., an orthornormal rotation matrix from a global to local coordinate system.

Best regards,

**Comment by yub-ship** [comment]
Hi, @jjonkman 

Thank you very much for your reply!

One more question, does openFAST have any plan to support the cosimulation in another generic and standardize way, like Functional Mock-up Interface?

Many thanks.

Kind regards.

**Comment by jjonkman** [comment]
Hi @yub-ship,

One could say that the FAST modularization framework is similar to the FMI concept, but the general and standardized interface of the FAST modularization framework is formatted a bit differently than say, the FMI standard.  NREL is not currently budgeted to develop an interface that follows the FMI standard, but this could certainly make for interesting future work.

Best regards,

**Comment by yub-ship** [comment]
Hi, @jjonkman 

Thank you again for your reply.

While I was doing testing and debugging, I found the results of AeroDyn 13.0 and AeroDyn 15.0 have a bit large differences. I noticed you mentioned AeroDyn v15.0 uses DBEMT instead of Generalized Dynamic Wake, and in the AeroDyn v15 manual, it also mentions the results of AeroDyn v15 will differ a bit from earlier versions of AeroDyn. So, I wonder, about the performance and accuracy of AeroDyn v13.0 and v15.0, if you have any validation/verfication reports or papers that mention/indicate them and also can be shared with me. The materials about the influence of certain different methods used in the old and new version of AeroDyn (e.g. the UA model, DBEMT vs Generalized Dynamic Wake) would also be very good.

Sorry for having so many questions as AeroDyn is such an intriguing software which makes me want to dig a bit more. Thank you very much for your help.

Kind regards

**Comment by jjonkman** [comment]
HI @yub-ship,

The new BEMT method of AeroDyn v15, including some validation results, is published in the following paper: https://www.nrel.gov/docs/fy15osti/63217.pdf (although the BEMT implementation has been updated a bit since this was published).

An implementation plan was developed when implementing DBEMT, but this was never published.  And we have done some internal comparisons of DBEMT against GDW, but don't have a publication on that either.

The new UA models of AeroDyn v15, including some validation results, are published in the following papers: https://arc.aiaa.org/doi/10.2514/6.2016-1007 and https://www.nrel.gov/docs/fy20osti/66347.pdf.

AeroDyn v15 also supports the inclusion of a new vortex free-wake aerodynamics model (OLAF): https://www.nrel.gov/docs/fy20osti/75959.pdf.

Further verification and validation of these models (and the wider OpenFAST tool) has happened within specific industry collaborations and in the various V&V collaboratives within IEA Wind, e.g. Task 29 (Aerodynamics), Task 30 (Offshore), and Task 31 (Wakebench).

In general, we have greater confidence in AeroDyn v15 over past versions of AeroDyn and plan to deprecate AeroDyn v14 soon.

Best regards,

**Comment by yub-ship** [comment]
Hi, @jjonkman, 

Thank you very much for all the materials. It will be a very good learning for me.

I had a quick view of the documents and found the performance comparisons in those papers are between AeroDyn v15 and v14, not v13. This brought me a new question which is what the differences between AeroDyn v14.0 and v13.0 are, in terms of the performance or the adopted methods.

To be honest with you, as AeroDyn 15.0 altered the interface framework, in order to connect it, we need to develop a new wrapper program and also may face some maintenance work in the future, which might require many resources. As we already have a successful connection with AeroDyn v13.0, we need to understand the version differences/improvements (in different aspects) and let them help us decide the priority of this development (i.e. connection with AeroDyn v15.0). 

Thank you very much for your help again.

Kind regards,

**Comment by jjonkman** [comment]
Hi @yub-ship,

AeroDyn v13 was used in FAST v7.  AeroDyn v14 is basically AeroDyn v13 internally, with an updated interface to support the requirements of the FAST modularization framework introduced in FAST v8 (and now, OpenFAST).  So comparing AeroDyn v15 with v14 should be quite similar to compare AeroDyn v15 with v13.

Best regards,

**Comment by yub-ship** [comment]
Hi, @jjonkman,

Cool, thanks a lot for the clarification.

I deeply appreciate your great help. 

Wish you a Merry Christmas and a Happy & Prosperous New Year! 

Best regards,
