### ISSUE TITLE
Openfast simulink lib

### ISSUE THREAD

**Issue by Hermse** [OpenFAST/openfast#621]
Hello , I try to run the program **create_FAST_SFunc.m**,but I get a error:can't find the OpenFAST-Simulink_x64.lib，

**Comment by jjonkman** [comment]
Dear @Hermse,

Similar questions have been asked and answers on this OpenFAST github issues page before, e.g.:
https://github.com/OpenFAST/openfast/issues/387
https://github.com/OpenFAST/openfast/issues/548

Have you followed the guidance from these issues?

Best regards,

**Comment by Hermse** [comment]
@jjonkman Thank you very much . In fact, I guess I need compile **OpenFAST-Simulink.vfproj** to get the .lib, am I in the right way? But ,I got a error #**7002: Error in opening the compiled module file.  Check INCLUDE paths.   [FAST_SOLVER]		D:\workplace\openfast\openfast\modules\openfast-library\src\FAST_Library.f90	15**	, when I compile the .vfproj. I am not good at English and Openfast, thank you for your help again.

**Comment by bjonkman** [comment]
@hermse, Yes, you must build OpenFAST-Simulink, using `Build Solution` with the `Release_Matlab | x64` configuration in Visual Studio. If you continue to have issues, please post screen shots so we can identify the issue easier.

**Comment by SimoneCov** [comment]
Hi team,

I want to use OpenFAST v.2.5 for Matlab and I am trying to generate MEX files required to run OpenFAST through Simulink.
I followed the guidelines of the UserGuide and I caught the advices provided for other users but I can't create correctly the bin folder.
In particular I must specify that I followed Windows path installation using VS 2019 with Intel® Fortran Compiler Classic since I can't find a way to obtain Intel Parallel Studio, furthermore I can't use Intel® oneAPI Base Toolkit because my device doesn't match software requirements(hence I'm not able to download Intel® oneAPI Math Kernel Library which is suggested by the UserGuide).

![Immagine 2021-01-26 145602](https://user-images.githubusercontent.com/75087074/105860017-703f0c00-5fed-11eb-95fc-9de6768264b0.png)

I think that the problem is strictly related to the missed library but I don't know how to fix it since I can't download it.

Thanks for your help and support.

**Comment by rafmudaf** [comment]
I'm working on establishing a path for distributing the OpenFAST Library compiled for Simulink integration along with the other executables we regularly share for each release. I've added a file included in the last [Release](https://github.com/openfast/openfast/release/latest) called `openfastlib_simulink.dll`. Is someone able to test the attached library? This is the OpenFAST Library that should be linked in the mex-function.

**Comment by cgh2530** [comment]
> Hello , I try to run the program **create_FAST_SFunc.m**,but I get a error:can't find the OpenFAST-Simulink_x64.lib，

Have you solved it yet
