### ISSUE TITLE
Error in Inflow wind file

### ISSUE THREAD

**Issue by SudharsanKalidoss** [OpenFAST/openfast#622]
Hi everyone,

    I'm running the NREL 5 MW wind turbine with tlp platform. When I tried running the case, I get an error message stating that the ref height is negative in inflow wind file. I tried running monopile case with same wind file and it worked. But it shows error for TLP case. I have attached the error. 

Sudharsan
![Inflow_neg_ht](https://user-images.githubusercontent.com/17265645/103561175-0ff1fa00-4e87-11eb-9bbc-baed2d1efacf.png)

**Comment by jjonkman** [comment]
Dear @SudharsanKalidoss,

Did you change this r-test TLP case in some way?

The error is triggered because an aerodynamic analysis node on the tower has heaved downward a tiny amount (-1.08935E-04 m), and there is no wind data in the TurbSim file below the mean sea level (0.0 m).  Due to its design, I would not expect the TLP to heave downward by much.  So, the simple solution is likely to raise the lowest tower aerodynamics node in AeroDyn.  Currently, the lowest node is at TwrElev = 0.0 m, so, any downward motion will trigger an error.  Raising TwrElev from 0.0 to something a bit higher (say from 0.0 to 1.0 m) should solve the problem.  Disabling tower aerodynamic loads (TwrAero = False) should also solve the problem.

Best regards,

**Comment by SudharsanKalidoss** [comment]
Dear @jjonkman,

    Thank you for your help. I moved the tower lowest node higher and it worked.
