### ISSUE TITLE
Having some problems with OpenFAST compiling on VS 

### ISSUE THREAD

**Issue by AngelCamargoUSP** [OpenFAST/openfast#625]
**Bug description**
<A clear and concise description of the bug.>
@jjonkman @bjonkman 

Hello developers! I am Angel Camargo a student form the mechanical engineering master degree curse of Universidade de São Paulo in Brazil. My team and me are having some problems while compiling the OpenFAST versions on Visual Studio (Windows users). It seems like there are too many errors but then applying typing corrections on the code some of they disapear. However there is still errors which we don't understand how to fix. I read before one issue related to and it were said that the format was modified for Windows.

So, there is any file or zip/tgr with the correct format for Windows or edited by someone? 

**System Information (please complete the following information):**
 - OS: Windows 10
 - Compiler: Visual Studio 2013

**Additional context**
<Add any other context about the problem here.>
We followed all the steps of: https://openfast.readthedocs.io/en/master/source/install/index.html#compile-from-source

**Comment by AngelCamargoUSP** [comment]
[error-vs.txt](https://github.com/OpenFAST/openfast/files/5788843/error-vs.txt)

**Comment by andrew-platt** [comment]
You shouldn't need to add any corrections to the code to get it to compile.  Which branch of the source code are you using: master or dev?

From your error log, it looks like the `USE FAST_Subs.f90` is causing issues since VS can't find that module.  This makes me suspicious that VS didn't get the build order correct for some reason.  All the type definition errors that follow should have been inherited from this and other modules.

**Comment by AngelCamargoUSP** [comment]
Thanks for the information Andrew I think I tried before with both versions. But I gonna retry. Which one do you recommend?

**Comment by haojunjie0429** [comment]
![warning](https://user-images.githubusercontent.com/76469531/104401008-4f5acd80-558e-11eb-857f-1eea80494d8c.jpg)
@andrew-platt 
Hello developers! i also having the problem(As above picture) while compiling the OpenFAST versions on Visual Studio (Windows users).I have these warnings. Is it because the Fortran version is low?i use Fortran2019. Do these warnings affect the generated program?
Best regards,

**Comment by andrew-platt** [comment]
@haojunjie0429 
Those warnings are fine. OpenFAST is primarily based on the Fortran 2008 standard.  So some functions used (such as NORM2) are part of that standard, but not part of the Fortran 2003 standard (not all compilers fully support the full 2008 standard yet and we support multiple different compilers).  The warnings are essentially telling you that there are some features from 2008 in use (we enforce that it must be fully compliant with Fortran 2003, but with some extensions from 2008).

The warning about the tab is because there is a rogue tab character somewhere that we didn't get removed yet (our formatting standard says only spaces are allowed, no tabs -- Entertaining reading on the subject: https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/).

Cheers!

**Comment by haojunjie0429** [comment]
@andrew-platt 
thanks~~

**Comment by AngelCamargoUSP** [comment]
I just retry with the dev version and all compiled correctly I was using a version of build Tools for VS for a different VS version. Now I'm trying to run the Simulink samples;
