### ISSUE TITLE
guidance request about running and testing compiled openfast 

### ISSUE THREAD

**Issue by sina778** [OpenFAST/openfast#626]
hello
I am a new user of GitHub
recently I joined a project about modeling wind turbine and in this project I need to simulate wind turbine with openfast.
unfortunately I am not familiar with open source codes and I know a little programming and have just started learning Python therefore I have many problems and questions about using compiled openfast binaries code for simulating wind turbines in openfast.
can somebody help me about this?
is there any Instruction and guidance for simulation in openfast Which is explained to beginners step by step?
If help me, you have done me a great favor
Thank you all
best regards

**Comment by jjonkman** [comment]
Dear @sina778

You may not need to compile OpenFAST yourself if you are a Windows user and do not need to change the source code because precompiled binaries for Windows users have been provided with each release (https://github.com/OpenFAST/openfast/releases).

We don't really have a step-by-step beginners guide for learning how to use OpenFAST.

A good way to learn OpenFAST is to review the presentations and sample models/simulations that were presented at our last modeling workshop, which are available here: https://drive.google.com/drive/folders/1BDDfcnIyvmZCwf7eFo0ISI7aF_FMAOvt?usp=sharing. These are available for FAST v8.08 (not quite the newest version, but I don’t have newer materials that are so comprehensive) in the workshop from September, 2014 (1409).  A more up-to-date presentation for OpenFAST (but less detailed, without the corresponding sample models/simulations) is available from our last “mini-workshop” that we held in October, 2019 (191017).

After that, I suggest that you study the various user’s guides and theory manuals for detailed information.  There is already some good documentation in readthedocs (https://openfast.readthedocs.io/en/master/index.html), including details on installing/compiling, running the test suite, using git, user-documentation on the ElastoDyn, AeroDyn, and BeamDyn modules, etc.  

More complete, but not up-to-date, documentation is available in the FAST v7 User’s Guide (https://drive.google.com/file/d/1d_-vRRK3sXlunf1I1tDmtSWUveed91gg/view?usp=sharing, pertinent to ElastoDyn and ServoDyn) and FAST v8 ReadMe file (https://drive.google.com/file/d/17LDwMnCVmLfbRWSaVFxxqphVrtawMwlj/view?usp=sharing, pertinent to the glue code, the transition to the FAST modularization framework and updates relative to the FAST v7 documentation).  Depending on which OpenFAST modules you intend to use, we have documentation for various modules, which most of which are still be ported over to readthedocs.  But the module-level documentation from FAST v8 that has not yet been ported over to readthedocs is available here:
SubDyn: https://drive.google.com/file/d/1mX-_qI15ZN7rMxmEynlOE-6-yoAjO9-3/view?usp=sharing
InflowWind: https://drive.google.com/file/d/1-yJox2Kj-eBHfX2FdjE7RCaOkXRml9Mw/view?usp=sharing
HydroDyn: https://drive.google.com/file/d/11WY1LRk70w-nsj5q39j4-WakMMFa4hiz/view?usp=sharing
MAP++: https://map-plus-plus.readthedocs.io/en/latest/index.html
MoorDyn: http://www.matt-hall.ca/files/MoorDyn%20Users%20Guide%202017-08-16.pdf

There are open actions (https://github.com/OpenFAST/openfast/issues/181, etc.) that are being worked on to migrate the documentation from previous versions of FAST v8 and FAST v7 into readthedocs.

Best regards,
