### ISSUE TITLE
Deflections in ED

### ISSUE THREAD

**Issue by ptrbortolotti** [OpenFAST/openfast#631]
**Bug description**
This is likely not a bug, but I'd still like to hear the feedbacks from the OpenFAST team about it.
Within the BAR project, Nikhar Abbas and I are running the WEIS framework (https://github.com/WISDEM/WEIS, develop branch) to optimize blade structure and flaps simultaneously. 
Unfortunately we see a marked difference in terms of blade deflections between the WISDEM beam model frame3dd (http://frame3dd.sourceforge.net) and ElastoDyn. In WISDEM, when we start from our baseline design BAR0, if we reduce spar caps thickness, we end up reducing stiffnesses and unit mass and blade deflections grow. 
In ElastoDyn, when we decrease spar caps thickness (by up to 30%), deflections surprisingly decrease. 
I worked to isolate the problem and I now have two identical openfast models, one with stiffer blades and one with more flexible blades. The models face a wind of 7 m/s and operate at constant rpm and pitch. I also removed gravity and locked all DOFs except the blade ones, without success. 
The stiffer blades deflect more than the more flexible ones, see screenshots below. If I artificially impose the same beam modes, then the stiffer model does deflect less than the more flexible one. In WEIS, frame3dd is used to compute the modes.

Question for you: is this physical? Is this somewhat to expect? 

**To Reproduce**
I attach the two models, which run with the latest openfast develop.
[flex.zip](https://github.com/OpenFAST/openfast/files/5815547/flex.zip)
[stiff.zip](https://github.com/OpenFAST/openfast/files/5815548/stiff.zip)

**Expected behavior**
I expected a closer behavior between frame3dd and ElastoDyn, where thinner spar caps result in higher blade deflections for given aerodynamic loads.

**Screenshots, if applicable**
![TipDxb1](https://user-images.githubusercontent.com/20641647/104615597-a02dfd00-5646-11eb-9372-0823f053c143.png)
![edge1](https://user-images.githubusercontent.com/20641647/104615616-a4f2b100-5646-11eb-99e7-6deacd420777.png)
![flap2](https://user-images.githubusercontent.com/20641647/104615620-a58b4780-5646-11eb-985b-b74b1e3810a4.png)
![flap1](https://user-images.githubusercontent.com/20641647/104615624-a623de00-5646-11eb-8cde-987e86c2a2f9.png)
![mass](https://user-images.githubusercontent.com/20641647/104615627-a623de00-5646-11eb-90db-f81b6af22d56.png)
![edge](https://user-images.githubusercontent.com/20641647/104615629-a6bc7480-5646-11eb-8164-254e6f4c8558.png)
![flap](https://user-images.githubusercontent.com/20641647/104615631-a6bc7480-5646-11eb-980d-66b2deaa668d.png)

**OpenFAST Version**
Latest OpenFAST develop compiled with GCC 9.2 in single precision

**System Information (please complete the following information):**
 - OS: macOS 10.14.6
 - Compiler:  GCC version 9.2.0
 - Compiler settings: standard cmake

**Comment by ptrbortolotti** [comment]
@ebranlard

**Comment by jjonkman** [comment]
Hi @ptrbortolotti,

This is my summary understanding based on your comments:

- If you change the mass and stiffness in ElastoDyn, and derive the mode shapes from Frame3DD, then the stiffer blade results in more deflection then the flexible blade, which is not physical.
- If you change the mass and stiffness while keeping the mode shapes unchanged, you get the the results you expect, i.e., that the stiffer blade results in the less deflection than the flexible blade. 

Is that correct?

From this it appears that the change to the mode shapes is having a large effect on the ElastoDyn solution.  This is a bit surprising to me, as from my experience, the deflections and loads are not strongly tied to small changes to the mode shapes (at least for the first mode).  Regardless, are your sure that Frame3DD is giving accurate mode shapes for this case?  Does Frame3DD include effects from rotor rotation (e.g., centrifugal stiffening)?  How do the mode shapes derived from Frame3DD compare to those derived from, say, the older NREL software BModes or Modes for this blade, which do include centrifugal stiffening?

Best regards,

**Comment by ptrbortolotti** [comment]
Yes, your interpretation of my message is correct. I am going to loop back to Garrett, who is our main expert of frame3dd, and compare the modes with the ones from BModes
I'll update the issue once I know more
Thanks

**Comment by ptrbortolotti** [comment]
With the help of Roger B and Garrett B I ran BModes assuming 0 str_tw, 0 tw_iner, flp_iner and edge_iner of 1.e-10, and tor_stff and axial_stff of 1.e10

<img width="1081" alt="Screen Shot 2021-01-14 at 12 08 04 PM" src="https://user-images.githubusercontent.com/20641647/104637290-d62caa80-5661-11eb-8308-1afc94c5c0ee.png">

The new modes look like this
![BModes_vs_frame3dd_1stmode](https://user-images.githubusercontent.com/20641647/104637350-eb093e00-5661-11eb-83b7-de56fd095e44.png)
![BModes_vs_frame3dd_2ndmode](https://user-images.githubusercontent.com/20641647/104637354-ec3a6b00-5661-11eb-8efe-b1221a69db54.png)

And the deflections are back to what one would expect (final=flex higher than init=stiff)
![deflections_new](https://user-images.githubusercontent.com/20641647/104637479-12600b00-5662-11eb-99c1-10c829fc661a.png)

My next step consists of checking frame3dd and figure out what makes the modes different. Probably the inputs. 


And here comes my question. @jjonkman, do the BModes inputs above make sense?

**Comment by jjonkman** [comment]
Hi @ptrbortolotti,

It sounds like you are making progress.

Yes, I agree with those settings in BModes, which agrees with the recommendations I provided on our forum: https://wind.nrel.gov/forum/wind/viewtopic.php?f=3&t=1264&p=11526.

Best regards,

**Comment by ptrbortolotti** [comment]
Ok! The trick here is to fool frame3dd and make it support ED by removing all those terms. I'm working with Garrett to see if we find a way. BModes is indeed not easy to integrate within WEIS... I'll keep you updated on the progress

**Comment by gbarter** [comment]
To add to the thread, we have not found a way to simplify or hack the Frame3DD inputs in a way to be consistent with BModes/ElastoDyn.  Frame3DD does have axial stiffening and a few more bells and whistles than BModes or ElastoDyn.  We are somewhat stuck in that we cannot simplify the Frame3DD physics enough to be inline with ElastoDyn, but cannot bump them up to be inline with BeamDyn either.  We will keep thinking and working the issue.

**Comment by ptrbortolotti** [comment]
I setup an even cleaner test where I only have FlapDOF1 set True and all other DOFs set to False. 

I switch between flexible and stiffer designs with the modes from frame3dd and the modes from BModes (a total of 4 cases). 

The tip deflections are very different, especially between the two flex cases 

![bmodes_vs_frame3dd](https://user-images.githubusercontent.com/20641647/104667696-e9586e00-5693-11eb-8f93-14ae9a43e232.png)

despite very similar mode shapes

![flex_modes](https://user-images.githubusercontent.com/20641647/104667724-fb3a1100-5693-11eb-9ddb-1af4bef2c79d.png)

Is this to be expected?

I attach the model should anyone have any desire to test it out

[firstmodeonly.zip](https://github.com/OpenFAST/openfast/files/5817793/firstmodeonly.zip)

**Comment by jjonkman** [comment]
Hi @ptrbortolotti,

I would suggest plotting/comparing the second derivative of the mode shape, `d/dr(phi(r))`, where `phi(r)` is the radially (`r`) dependent mode shape.  This is because the second derivative is used to calculate the generalized elastic stiffness.  Because `phi(r)` is a written as a polynomial, computing its derivatives is trivial.

For an untwisted beam of length `R`, the `(i,j)` element of the generalized elastic stiffness matrix for modes `i` and `j` is:

`K_ij = INTEGRAL( EI(r)*d/dr(phi_i(r))*d/dr(phi_j(r))*dr, r=0, r=R )`

(For only one mode, `i=j=1`.)

You could also see how the generalized elastic stiffness changes between the cases through an OpenFAST linearization analysis.

Best regards,

**Comment by ebranlard** [comment]
As Jason mentions, the curvature will drive the stiffness (I'm guessing  `d^2/dr^2`  would represent the second derivative instead of `d/dr`).

I have an openfast branch that output these matrices to the ElastoDyn summary file:
      https://github.com/ebranlard/openfast/tree/f/EDsum
I find this pretty useful, so maybe I'll do a pull request
   
I have a set of python tools to compute these terms if you want. 
To get phi, dphi, and ddphi from the polynomial coefficients:
     https://github.com/ebranlard/welib/blob/master/welib/yams/flexibility.py#L21  

To get the generalized mass, stiffness and damping matrix from EI and the polynomial coefficients:
        https://github.com/ebranlard/welib/blob/master/welib/yams/flexibility.py#L122     

One thing to note is that FAST does not use trapezoidal integration but the mid-point rule. You might want a sufficient number of ElastoDyn nodes (50+) to get similar stiffness.

**Comment by jjonkman** [comment]
@ebranlard -- Thanks for pointing out my typo!  I've corrected my comment above to avoid confusion.

**Comment by ebranlard** [comment]
Thinking back about the question, ElastoDyn has limitation regarding the displacement fields that can be represented, and assumes that the displacement field of each shape functions that is entered is in a given direction, where structural twist is only used a posteriori. 

The question is then how to best obtain these shape functions given an FEM model which has full 6x6 matrices along the span (and also, should we simplify/project the shape functions onto the ElastoDyn space, or, should ElastoDyn simplify/project it inherently). I'm not sure how to fully answer that. 

I guess (I haven't used frame3dd) some of the inputs that Jason mentions on the forum can be directly applied to the 6x6 matrices: increasing the EA, increasing the torsion stiffness, and remove the CG offsets. For the shear, it might require moving each 6x6 to the shear center to remove cross coupling terms of the stiffness matrix? Also, instead of computing modes, we could use deflection shapes from a unit displacement in each direction? Or somehow change the tip boundary conditions when determining the modes to remove couplings? I'm sure Jason would have better inputs on that. 

There is still the problem of the rotational stiffening, and this would require adding an additional stiffness matrix in the FEM representation of frame3dd. 

One way to figure out which of the shape function is "right' and has the proper generalized stiffness, would be to compare the tip displacement for a known loading between OpenFAST and frame3dd. I'm not sure we fully have the feature to apply tip-loads yet in OpenFAST. Maybe we could do gravitational loading when the blade is at 90deg azimuth (with no rotation) and pitched 0 and 90 degrees. I think it could be best to use two flap shape functions if these are not "true" modes.  Another way would be to look at the eigenfrequencies in vacuum from the linearization. 

That's definitely some work...

**Comment by jjonkman** [comment]
Hi @ebranlard,

My general recommendation to computing mode shapes for ElastoDyn is outlined in the forum post linked above, and in other forum topics.  Basically, it is best to neglect the structural pretwist (because the pretwist is--as you said--captured posteriori within ElastoDyn), to neglect blade pitch, to neglect terms that ElastoDyn does not account for (rotational inertia and mass and elastic offsets from the pitch axis), and to increase the shear and torsion stiffness.  This leaves only the distributed mass, the distributed bending stiffness in the out-of-plane (flap) and in-plane (edge) directions. blade precone (if nonzero), the hub radius, and the rotational speed (for centrifugal stiffening effects).

Best regards

**Comment by ptrbortolotti** [comment]
Thank you all for the support. 

I'm closing this issue and opening one in WEIS, as this issue is, as somewhat expected, not an OpenFAST bug, but rather a problem in WEIS. The last update is that Garrett revisited the polynomial interpolation of the modes generated by frame3dd and deflections are now correct in trend (flex>stiff)

![tipdxb1](https://user-images.githubusercontent.com/20641647/104972547-511dfa00-59af-11eb-9f42-6492bf34951d.png)

although the modes between frame3dd and BModes are still not identical, here a plot for the 1st mode of the "stiff" blade

![mode1st_stiff](https://user-images.githubusercontent.com/20641647/104972564-609d4300-59af-11eb-8e25-292944e16361.png)

Talk to you soon on the WEIS side!
