### ISSUE TITLE
Mapping error, and scaled turbine model

### ISSUE THREAD

**Issue by SudharsanKalidoss** [OpenFAST/openfast#640]
Hi Everyone,

    I am trying to run a 1:100 scaled model of NREL 5 MW turbine on monopile support. I scaled down the nodal values for the 5 MW turbine model but I'm encountering a mapping error. I request some suggestion for this error.

Thanks
Sudharsan
![scaled_model](https://user-images.githubusercontent.com/17265645/104956802-e2cf3c80-599a-11eb-8926-71e6b275cce2.png)

**Comment by SudharsanKalidoss** [comment]
Hi Everyone,

    I figured out the error. It was with wrong AeroDyn file. Now, I'm encountering a different error. It seems that the platform is oscillating violently. I attached the screenshot of the error.

Thanks
Sudharsan
![scaled_model_1](https://user-images.githubusercontent.com/17265645/104989336-3ae06000-59e8-11eb-9ce9-a65b64155250.png)

[5MW_OC3Mnpl_DLL_WTurb_WavesIrr.zip](https://github.com/OpenFAST/openfast/files/5833719/5MW_OC3Mnpl_DLL_WTurb_WavesIrr.zip)

**Comment by jjonkman** [comment]
Dear Sudharsan,

Your model is clearly going numerically unstable very quickly.  I've only looked briefly at your input files.  It looks like you applied a factor of 0.01 on the geometry, but I don't see that you applied any factors on the mass or stiffness, which doesn't make physical sense.

Best regards,

**Comment by SudharsanKalidoss** [comment]
Dear Jonkman,

    I followed the scaling given in the literature. I attached the paper for your reference. I did the scaling of all the parameters from scratch again. I tried running the simulation. The program read the input files but didn't run the simulation. I waited for more than 30 mins. It stays in the same status message. I have attached the modified input files for your reference.

Thanks,
Sudharsan
[5MW_OC3Mnpl_DLL_WTurb_WavesIrr_mod.zip](https://github.com/OpenFAST/openfast/files/5837808/5MW_OC3Mnpl_DLL_WTurb_WavesIrr_mod.zip)
[sedran 2011.pdf](https://github.com/OpenFAST/openfast/files/5837811/sedran.2011.pdf)
![scaled_model_2](https://user-images.githubusercontent.com/17265645/105076544-2ee0b680-5a59-11eb-8a3e-05f0f48f4c86.png)

**Comment by jjonkman** [comment]
Dear @SudharsanKalidoss,

I'm not sure why the code is hanging on that line.

I haven't reviewed your paper or input files in great detail, but did you now change all of the geometries, mass, stiffness, and damping coefficients?  You'll also need to change the time step accordingly.  You'd likely also need to change some values within the controller source code and recompile the controller DLL...did you do that?.  If you haven't already, I would go through each input file line-by-line to consider which parameters need to change.  After that, I would simplify the model to debug...e.g., first run with few if any DOFs enabled and without the controller.

Is there a reason you are building an OpenFAST model at model scale?  Presumably you are trying to validate your numerical OpenFAST model against scaled wind tunnel or wave tank measurements; is that correct?  It is much more common to keep the numerical model at full scale, and only scale experimental data for validation purposes.

Best regards,

**Comment by SudharsanKalidoss** [comment]
Dear Jonkman,

   I changed all the parameters such as geometries, mass, stiffness, and damping coefficients. I didn't change the controller source code. Can guide me through the process How to change the controller source code? 

  Yes, I'm trying to validate the numerical model against the scaled experimental results. I tried comparing the full-scale model with the experimental model. The results were not matching properly. That's why I thought of running the numerical model with scaled dimensions.

**Comment by jjonkman** [comment]
Dear @SudharsanKalidoss,

There is documentation provided in OpenFAST readthedocs that describes how to compile the DISCON controller DLLs: https://openfast.readthedocs.io/en/master/index.html.

NREL has not developed documentation that describes how to edit the _DISCON.f90_ source code.  Regardless, you'd have to change the values of the constants defined by the `REAL(4), PARAMETER` declarations near the top of the source file.  If you are unfamiliar, there is documentation on the baseline controller for the NREL 5-MW wind turbine here: https://www.nrel.gov/docs/fy09osti/38060.pdf.

Again though, I would generally recommend to scale the experimental results to full scale rather than to build an OpenFAST model at model scale.  The process should be equivalent, as discussed in our ISOPE 2012 paper: https://www.nrel.gov/docs/fy12osti/54221.pdf.  And I would think it would be easier to scale the experimental results than to scale the OpenFAST model.

Best regards,
