### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by Bruce-Cavanagh** [OpenFAST/openfast#649]
Good afternoon, 

I have just downloaded OpenFAST v2.5.0 from the openfast/releases. I downloaded the precompiled binaries zip. I saw the issues regarding missing .dlls and downloaded the 2017 redistribution libraries as recommended in Issue #352.

However, now when I try to run openfast_x64.exe, I get the error:
"The procedure entry point for_stop_core_quiet could not be located in the dynamic link library" then it gives the path where my openfast_x64.exe is and that is the end of the message. I have included a picture of the error message below:
![image](https://user-images.githubusercontent.com/72988388/106004088-c2923280-60aa-11eb-9c7e-792c181cc8a5.png)

Is this because the redistribution libraries are not at the same location as the executable? 

As a bit of extra information I have been using OpenFAST v1.0.0 with no issues. 

Thanks in advance, 
Bruce

**Comment by andrew-platt** [comment]
Hi Bruce,

We recently upgraded to a newer Intel compiler suite for building the precompiled Windows executables of OpenFAST.  These require a newer version of the redistributable.

@rafmudaf, can you suggest which redistributable is now required?  I can test it later for you.

Cheers,
Andy

**Comment by Bruce-Cavanagh** [comment]
Hi Andy, 

Thank you for the tip, I downloaded the 2020 redistributable libraries and it seems to be working now. Can you or rafmudaf please confirm that I am correct and that these are the redistributables that OpenFAST v2.5.0 needs? 

Thanks, 
Bruce

**Comment by rafmudaf** [comment]
I'm having trouble installing that package on my Windows computer due to inadequate admin rights. @andrew-platt could you try on your virtual machine?
Otherwise, @Bruce-Cavanagh I suspect that version is correct. I used the Intel Fortran classic compiler that came with the new oneAPI installation, and I believe that corresponds to ifort 19 2020.

**Comment by andrew-platt** [comment]
Just tested. The 2020 redistributable corrects the issue.  Should we post a link to that in the release notes?

**Comment by rafmudaf** [comment]
I've added the link to the release. Thanks @andrew-platt and @Bruce-Cavanagh.

**Comment by Bruce-Cavanagh** [comment]
Thank you for your assistance.

**Comment by Christophe-delFosse** [comment]
Good evening,

I have a similar problem as the one mentioned in this post. When I try to run OpenFAST from an Anaconda 3 command prompt, I get the error "The procedure entry point for_stop_core_quiet could not be located in the dynamic link library". Running OpenFAST from a normal command prompt works fine. I am working on a Windows 10 computer and work with precompiled OpenFAST  v2.5.0 binaries and redistributables for the 2020 Intel Fortran compiler (as mentioned in the release notes). What could be the cause of this problem and how can I solve it? 

Thank you in advance!

Christophe

**Comment by rafmudaf** [comment]
It sounds like the Anaconda prompt isn't locating the Intel redistributable libraries. @bjonkman do you have any insight?

**Comment by ebranlard** [comment]
It could be a path issue, I'm not sure if that would help, but you can try to compare the content of the `%PATH%` environment variable in both the usual terminal and the conda terminal. Maybe the anaconda prompt doesn't have the path to the redistributables. You can look at the path using: 

     echo %PATH%

or to split by new lines

      python -c "import os; print(os.environ['PATH'].replace(';', '\n'));"

It could also be that anaconda provides some similar libraries, and shadows the redistributables path since it will put its own path first.  You can try to prepend the path of the dlls:  `set path="C:\PATH\TO\REDISTRIBUTABLES;%path%"` . A last resort is to put the dlls next to you executable, or have everything (folder+exe) in a folder that is always in your path.

**Comment by Christophe-delFosse** [comment]
Dear ebranlard,

Thank you for your solution! I ended up implementing the last resort solution and I put the dlls next to the executable. Now it works fine.

**Comment by Imcxqi** [comment]
> I'm having trouble installing that package on my Windows computer due to inadequate admin rights. @andrew-platt could you try on your virtual machine?
> Otherwise, @Bruce-Cavanagh I suspect that version is correct. I used the Intel Fortran classic compiler that came with the new oneAPI installation, and I believe that corresponds to ifort 19 2020.

Hi rafmudaf,

Recently I'm also having this trouble as Intel no longer supports the Parallel Studio XE for Fortran compiler. My student license expired a couple of days ago and I have to install the oneAPI. It can build my program with no error. However, the issue same as Bruce's occurred when I executed the program. I followed Andy and Bruce's suggestion and installed the new redistributable libraries [vc_redist.x64.exe](https://aka.ms/vs/16/release/vc_redist.x64.exe). It does not help. The problem is still there. 

Do you have any other suggestions or hints that might direct me to the right track?

Thanks,
Chaoxian

**Comment by rafmudaf** [comment]
You should install the Intel redistributables not the Visual Studio redistributables. The link to the appropriate package corresponding to the latest release is included in the release notes.

**Comment by Imcxqi** [comment]
> You should install the Intel redistributables not the Visual Studio redistributables. The link to the appropriate package corresponding to the latest release is included in the release notes.
> 
> https://github.com/OpenFAST/openfast/releases/tag/v2.5.0

Hi rafmudaf,

Thanks for your kind reply. I followed your suggestion and installed the Intel redistributable. However, the problem is still there. I read their installation instruction and found something did not happen during my installation. 

**The installation creates a new env-var "INTEL_DEV_REDIST" with the value of above installation directory, and the PATH env-var is updated with [INTEL_DEV_REDIST]\redist\[ia32|intel64]\compiler and [INTEL_DEV_REDIST]\redist\[ia32|intel64]\mpirt (for Fortran packages). The "redist\intel64" directory is added only on 64-bit systems.**

However, I did not found this new env-var on my computer. Could you please take a look at the computer on your end and see if you can find this new env-var after installing the Intel redistributables?

Very much appreciate it,
Chaoxian

**Comment by rafmudaf** [comment]
![Untitled](https://user-images.githubusercontent.com/13797903/111513417-c93e3d00-871e-11eb-8378-621da1f27ae0.png)

**Comment by rafmudaf** [comment]
Did you restart your command prompt?

**Comment by Imcxqi** [comment]
> Did you restart your command prompt?

Yes. I just realized that the new env_var is already there. I misunderstood the 'INTEL_DEV_REDIST'. I thought the name is 'INTEL_DEV_REDIST'. Actually, it is 'redist'. I did see the changes in the path 'Common Files\Intel\Shared Libraries\redist\intel64_win\compiler\1041'. But it seems that it doesn't work when I executed the program.

**Comment by bjonkman** [comment]
@Imcxqi : are you having trouble running the executable that **you** built (with Intel Parallel Studio? or oneAPI?) or the executable from the OpenFAST GitHub Releases page?

**Comment by Imcxqi** [comment]
> @Imcxqi : are you having trouble running the executable that **you** built (with Intel Parallel Studio? or oneAPI?) or the executable from the OpenFAST GitHub Releases page?

I am having trouble running the executable file **that I built with oneAPI**. The problem is **'' The procedure entry point for_stop_core_quiet could not be located in the dynamic link library"**

**Comment by bjonkman** [comment]
Can you open the Intel compiler command prompt and run the code from there? If you built the code on the computer you are using, the libraries should already be installed without using the redistributable package, but you have to make sure they are on the path (i.e., run it from the Intel compiler command prompt window). I don't have oneAPI, but you should be able to find the Intel compiler command prompt from your start menu, something like this: `Start->Intel oneAPI->compiler 2021 for x64 Visual Studio XXXX environment` (or win32 if that's what you used to build the code). 

Otherwise, you may need to make sure you've got the right redistributable for the compiler(s) you installed (see https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html)

**Comment by Imcxqi** [comment]
> Can you open the Intel compiler command prompt and run the code from there? If you built the code on the computer you are using, the libraries should already be installed without using the redistributable package, but you have to make sure they are on the path (i.e., run it from the Intel compiler command prompt window). I don't have oneAPI, but you should be able to find the Intel compiler command prompt from your start menu, something like this: `Start->Intel oneAPI->compiler 2021 for x64 Visual Studio XXXX environment` (or win32 if that's what you used to build the code).
> 
> Otherwise, you may need to make sure you've got the right redistributable for the compiler(s) you installed (see https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html)

Thanks for your kind reply. I did test it as you suggested. It has the same problem as I run the exe in the system prompt. I totally agree with you that there might be something wrong with the library path. It shows the '**for_stop_core_quiet**' cannot be located. It seems that the program cannot find the DLL related to '**for_stop_core_quiet**' when it is executed.

**Comment by bjonkman** [comment]
Did you build this executable using CMake or the Visual Studio solution file in `<openfast>/vs-build/FAST/FAST.sln`? The Visual Studio build *should* be set to use static libraries, in which case you shouldn't need the redistributable libraries.

**Comment by Imcxqi** [comment]
Hi guys,

I just solved the problem by following the suggestion in Intel Fortran Compiler Community under the [topic](https://community.intel.com/t5/Intel-Fortran-Compiler/unresolved-external-symbol-for-stop-core-quiet-continuation-of/m-p/1265721/highlight/false#M155113).

_Go to  [Intel® oneAPI standalone component installation files](https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html)

Select Runtime Versions > Windows > Intel Fortran Compiler Classic for Windows

Download and install that._

Thanks for your kind help! Hope you doing well.
