### ISSUE TITLE
Documentation error: 2.1. Download binaries

### ISSUE THREAD

**Issue by PerLunsj** [OpenFAST/openfast#650]
The link to Windows binaries is 404. [ 2.1. Download binaries](https://openfast.readthedocs.io/en/dev/source/install/index.html#download-binaries)
"All precompiled binaries can be found in the Assets dropdown in the [GitHub Releases](https://github.com/OpenFAST/openfast/releases). To download the latest binaries, [click here.](https://github.com/OpenFAST/openfast/releases/latest/download/windows_openfast_binaries.zip)"

The Asset dropdown is not easy to find either , ie I have not managed to located it. 

EDIT: 
Never mind the Asset comment, found it at the bottom of the release. But the link in Docs should be https://github.com/OpenFAST/openfast/releases/download/v2.5.0/openfast_v2.5.0_binaries.zip

**Comment by andrew-platt** [comment]
Thanks for pointing that out.  We will update the link in the next release.

**Comment by Echolon** [comment]
Hi,

wouldn't it be better to just provide the general link: https://github.com/OpenFAST/openfast/releases

If you want I can offer to make a PR for you.

**Comment by rafmudaf** [comment]
Ah the link is broken because I named the archive `openfast_v2.5.0_binaries.zip` instead of the convention we were using of `windows_openfast_binaries.zip`.

@Echolon the releases page is also linked in the documentation. The two sentences related to this are:

"All precompiled binaries can be found in the Assets dropdown in the [GitHub Releases](https://github.com/openfast/openfast/releases). To download the latest binaries, click [here](https://github.com/OpenFAST/openfast/releases/latest/download/windows_openfast_binaries.zip)."

When we were only linking to the Releases page, it was difficult to find the Assets dropdown after the release notes so I added a link to that directly.

**Comment by Echolon** [comment]
Ah okay - so not PR necessary?

Are there any other beginner task here? I am really interested to support.
If you need organizational help, I can offer to label all unlabeled issues. I did that work already for Jitsi Meet and the Monal IM repository.

**Comment by rafmudaf** [comment]
Hold off on making this change for now. I prefer to name the archives with the version number, but we do need to fix the broken link in the documentation.

There are a few issues labeled "Help Wanted": https://github.com/OpenFAST/openfast/labels/Help%20wanted
Specifically, the script to convert input files between versions would be very useful.

**Comment by rafmudaf** [comment]
This is addressed in #682
