### ISSUE TITLE
v2.5.0 libdiscon.so not found/recognized

### ISSUE THREAD

**Issue by deepalisingh286** [OpenFAST/openfast#651]
Hi,
I just installed openfast 2.5.0 on Ubuntu 20.04.1 LTS and tried running the IEA-15-240-RWT monopile case. I made a few changes only in the InflowWind input file since some new variables were included in v2.5 as opposed to 2.4 and were missing in the input file. Everything else being untouched, I am getting this error linked to ServoDyn:

FAST_InitializeAll:SrvD_Init:BladedInterface_Init:The dynamic library ././ServoData/libdiscon.so
 could not be loaded. Check that the file exists in the specified location and that it is compiled
 for 64-bit applications.
 FAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

The file libdiscon.so is present at that location. Is there a compatibility issue somewhere between the test case and the new OpenFAST version? If I disable the ServoDyn input, the simulation works fine.

**Comment by andrew-platt** [comment]
How did you do your installation?  Where are your running the regression test?

If you are using git, you will need to do `git submodule update` to get all the updated input files from the `r-test` repository.

If you are using `cmake` and `make` to build the test case, you will need do `make install` to build and install the controller.  If you are doing it manually, you will need to manually build the controller.

**Comment by deepalisingh286** [comment]
Thanks for your response. 
I ran the regression tests in the OpenFAST build directory, is that incorrect? I saw that for the 5MW turbine the three external controllers had to be compiled and installed manually. I had done that.
The test case I am looking at now has the *dll and *so files already in the ServoData folder. What am I supposed to compile here?

**Comment by andrew-platt** [comment]
For the `cmake` build system, the `build` directory is the correct place to run the regression tests with `ctest`.  If you setup the build directory with `cmake -DBUILD_TESTING=On ..` then you can just run `make install` and it will build the controller for you and install it into the regression tests in the build directory (it is slightly simpler than manually building the controller). These would be installed in the build directory at `reg_tests/glue-codes/openfast/5MW_Baseline/ServoData/`.

The path in your error above indicates that you may have copied the regression test over rather than using the `cmake` + `ctest` system.  So you will need to update that path in the `NRELOffshrBsline5MW_OC3Monopile_ServoDyn.dat` to point to where your compiled controller is located.

**Comment by deepalisingh286** [comment]
No I did use the cmake and ctest commands to run the tests and that was fine (results below)- the tests that failed here, I think they failed because I am using Ubuntu 20.04 (I think there is another thread on this topic...).
```
    Start 17: 5MW_Land_DLL_WTurb
17/51 Test #17: 5MW_Land_DLL_WTurb ...........................   Passed   60.92 sec
      Start 18: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr
18/51 Test #18: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr ...............   Passed  210.14 sec
      Start 19: 5MW_OC3Trpd_DLL_WSt_WavesReg
19/51 Test #19: 5MW_OC3Trpd_DLL_WSt_WavesReg .................***Failed  634.56 sec
      Start 20: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth
20/51 Test #20: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth .......***Failed  1491.24 sec
      Start 21: 5MW_ITIBarge_DLL_WTurb_WavesIrr
21/51 Test #21: 5MW_ITIBarge_DLL_WTurb_WavesIrr ..............***Failed   22.26 sec
      Start 22: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti
22/51 Test #22: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti ........***Failed   43.74 sec
      Start 23: 5MW_OC3Spar_DLL_WTurb_WavesIrr
23/51 Test #23: 5MW_OC3Spar_DLL_WTurb_WavesIrr ...............***Failed   40.72 sec
      Start 24: 5MW_OC4Semi_WSt_WavesWN
24/51 Test #24: 5MW_OC4Semi_WSt_WavesWN ......................   Passed  110.96 sec
      Start 25: 5MW_Land_BD_DLL_WTurb
25/51 Test #25: 5MW_Land_BD_DLL_WTurb ........................   Passed  145.93 sec
      Start 26: 5MW_OC4Jckt_ExtPtfm
26/51 Test #26: 5MW_OC4Jckt_ExtPtfm ..........................   Passed   12.56 sec

```


But I am now running the following test case: https://github.com/IEAWindTask37/IEA-15-240-RWT which is supposed to have the ServoData files already but I don't understand why it is not recognizing the *.so file. Don't see this issue with OpenFAST v2.4

**Comment by andrew-platt** [comment]
My apologies.  I had misunderstood your initial question.

The IEA test case (https://github.com/IEAWindTask37/IEA-15-240-RWT ) is managed by a different at NREL.  I suggest posting a question on their repository.  Given the dates I see there, I don't think they have updated to v2.4.0.  I am also uncertain of how their controller was built.

**Comment by deepalisingh286** [comment]
Okay, I'll try there. Thanks!

**Comment by andrew-platt** [comment]
One other thought, the message from ServoDyn could also be triggered if the library can't be loaded due to missing dependencies of the library on your system, or if the architecture is incorrect.  In linux, you can use the `ldd` and `objdump` commands to find out if there are issues with that specific .so on your system (I don't remember the syntax for those commands, so you'll need to figure that out).  It is very possible that it has dependencies on older versions of gcc that are not present on your system.

**Comment by deepalisingh286** [comment]
Ohhh. Yes, you are right. The gfortran library was missing because gcc++ 9 wasn't properly installed. I changed to gcc 7. It's fixed! Thanks a lot.

**Comment by andrew-platt** [comment]
Excellent!

I notified the  IEA-15-240-RWT team about their input files not working with v2.5.0. They say they'll update those, but weren't sure how soon.
