### ISSUE TITLE
Unit test Compiling

### ISSUE THREAD

**Issue by soeren-link** [OpenFAST/openfast#657]
Hi,

I am new at OpenFAST and I running into a problem with the unit test.
After successfully compiling OpenFAST with Visual Studio (Windows10), I followed the OpenFAST documentation and wanted to run the unit test but at the point of compiling the unit test I am getting the error that the 'make' command is not recognized. My problem seems to be like the one stated in issue #215 Testing OpenFAST, I am getting at least the same error message as written there (first error message) but it seems to me like that issue is not really discussed or solved there.  I am also using the Intel Compiler 2019. 

Can someone help me with that problem?

**Comment by rafmudaf** [comment]
The "make" command referenced in your link is a program primarily used on unix systems to compile code. So "make" is analogous to "msbuild" for Windows. Visual Studio is a GUI, among other things, for creating commands that it then uses to make a bunch of calls to the msbuild program. So in your case, you won't be using "make" since you're on Windows and using Visual Studio.

The Visual Studio solution is manually managed and does not include a portion for the unit tests. You can use CMake to create another Visual Studio project that includes a build for the unit tests as described in the [documentation](https://openfast.readthedocs.io/en/master/source/install/index.html#cmake-with-visual-studio-for-windows). If you go this route, you'll have to install CMake and then use these commands:

```
cd openfast\
mkdir build
cd build
cmake .. -G   # this will list the available "generators" on your system
cmake .. -G"<choose on from the list from the command above>" -DBUILD_TESTING=ON
cmake --build . --target beamdyn_utest
cmake --build . --target inflowwind_utest
cmake --build . --target <any other target, etc>
```

You have to do this in an Intel command prompt in order for CMake to find your Intel build tools installation.

**Comment by soeren-link** [comment]
Thanks for the quick response, it helps a lot.
