### ISSUE TITLE
Help required on numerical schemes used in OpenFAST

### ISSUE THREAD

**Issue by SudharsanKalidoss** [OpenFAST/openfast#659]
Hi everyone,

   I trying to understand the theory behind the modeling of different modules. I'm trying to figure out which type of numerical scheme (implicit or explicit) is followed. In AeroDyn module, on looking at the governing equations, it seems an explicit scheme is followed for time marching (I may be wrong). In BeamDyn module, It looks like an implicit scheme is followed. It would be helpful someone clarifies this confusion.

Thanks 

Sudharsan

**Comment by jjonkman** [comment]
Hi Sudharsan,

Whether the time-integration scheme in a module is implicit or explicit will depend on the module of OpenFAST, but most modules of OpenFAST with continuous states use an implicit solver, whereby inputs at time step n+1 are needed when time-integrating the states from n to n+1.  Some modules of OpenFAST have discrete-time states rather than continuous-stime states, and the discrete-time states by their formulation are inherently explicit, whereby states are advanced to n+1 based only on inputs at n.  Some modules of OpenFAST also have algebraic (constraint) states, which are require a nonlinear solve.

Best regards,
