### ISSUE TITLE
Cannot find NREL compiled open_fast.exe file

### ISSUE THREAD

**Issue by Acrbjr** [OpenFAST/openfast#663]
**Is your feature request related to a problem? Please describe.**
<A clear and concise description of the problem.>
I downloaded the open-fast.main zip file from GitHub, and unzipped the file to a folder on my computer.  I then successfully compiled the open_fast and discon files and ran a few of the test files.  Comparison of the analysis files (*.out)  I generated using my compiled open fast program with the analysis files provided by NREL showed minor differences. To investigate further, I would like to obtain the open_fast.exe and discon.dll files compiled by NREL.  These files were not in the folder created by unzipping the open-fast.main.zip file and I could not find them anywhere on your site.
**Describe the solution you'd like**
Would you either let me know where these compiled files are on github or send me copies by email.
<A clear and concise description of what you want to happen.>
Include NREL-compiled files in zip download.  Also, include all test files (now in a separate zip file) in the same open-fast.main.zip file. 
**Describe alternatives you've considered**
<A clear and concise description of any alternative solutions or features you've considered.>

**Additional context**
<Add any other context or screenshots about the feature request here.>

**Comment by rafmudaf** [comment]
What platform are you using?

For Windows, see the assets in the latest release: https://github.com/OpenFAST/openfast/releases/tag/v2.5.0

For macOS or Ubuntu, see the [documentation](https://openfast.readthedocs.io/en/master/source/install/index.html#download-binaries).

**Comment by Acrbjr** [comment]
Hello Rafael,

I am using Windows 10.  I downloaded the openfast_v2.5.0_binaries.zip file and found the compiled open fast programs.  However, when I tried to run openfast_x64.exe program I got an error statement indicating that I did not have the following files:

libifcoremd.dll.
libifportMD.dll
SVml)dispMd.dll
Libmmd.dll

The binaries zip file did come with some .dll’s, but not these.  Do you know where I can find these files?

Thanks,

Arnold

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by andrew-platt** [comment]
The last statement at the bottom of the page https://github.com/OpenFAST/openfast/releases/tag/v2.5.0 has a link to the redistributables from intel that contain those dlls:  https://software.intel.com/content/www/us/en/develop/articles/redistributable-libraries-for-intel-c-and-fortran-2020-compilers-for-windows.html

**Comment by Acrbjr** [comment]
Your email suggests that I download and install a program from Intel that will provide these files.  If I do, these files will be placed into a folder generated by Intel (along with thousands of other files).  They would not be  available to the executable open_fast program unless you copy and paste them into a folder that can be accessed by open_fast.  I actually did so, and the program still did not run.

All previous versions of FAST compiled by NREL did not require installation of *.dll files from Intel.  All files necessary to run FAST.exe were in the appropriate FAST folder.  Additionally, the version of open fast that I compiled does not require these *.dll files either.

Has anyone at GitHub actually downloaded the files to see if they work?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rafmudaf** [comment]
> They would not be  available to the executable open_fast program unless you copy and paste them into a folder that can be accessed by open_fast. 

Can you explain this further? If you follow the instructions from Intel on installing their redistributable libraries, why would they not be available to OpenFAST?

**Comment by Acrbjr** [comment]
When Intel installs the program, it puts it in a path starting with C:\Program Files (86)\Intel\…
An executable program such as OpenFast.exe will not search the entire computer for a file.  It will look in the folder that OpenFast.exe is in and any other folders defined in the path.  Furthermore I did put the Intel files in a path accessible to OpenFast and it still did not run.  When NREL provided the downloads, there was no issue—all necessary files needed  to run and test FAST were put in the correct folders.  There was a single download.  With GitHub, it’s a mess—files are all over the place.  Executive files are in one place, test files in another, and source files somewhere else.   I sincerely wish NREL would provide the downloads again  so we don’t have to endure this aggravation.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rafmudaf** [comment]
I appreciate your comments and understand that it can be challenging to make sense of the different locations for assets related to OpenFAST. Just to restate some of what you've pointed out:

- Binaries for Windows: https://github.com/openfast/openfast/releases/latest
- Binaries for macOS and Linux: use [Conda](https://anaconda.org/conda-forge/openfast) or [Homebrew](https://formulae.brew.sh/formula/openfast)
- Source code: https://github.com/openfast/openfast
- Regression tests: included with the source code or https://github.com/openfast/r-test
- Documentation: https://openfast.readthedocs.io/en/main/

Depending on your objective with OpenFAST, you could simply download the binaries and avoid looking at the source code. Alternatively, you could download the source code and compile yourself, and it sounds like you've already done this.

Regarding the OpenFAST executable finding the Intel libraries, see the [instructions](https://software.intel.com/content/www/us/en/develop/articles/redistributable-libraries-for-intel-c-and-fortran-2020-compilers-for-windows.html) for the Intel redistributable package again as it describes how programs compiled with Intel compilers can find those libraries in "Installation instructions". If you've installed this per the instructions, OpenFAST will find the libraries.

**Comment by Acrbjr** [comment]
I previously  indicated that OpenFast.exe file obtained from GitHub does not work.  The issue is not with the Intel libraries—they are only used for compiling the source code.   My compiled version of OpenFast.exe did not require them at runtime.

Again, there is something wrong with the version of OpenFast.exe provided by GitHub and I suggest you try running it yourself.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bjonkman** [comment]
@Acrbjr ,

The OpenFAST binaries from the Releases page on GitHub are compiled with cmake to be used with _dynamic_ libraries, while the executable you build with the OpenFAST Visual Studio solution file links with _static_ libraries. 

Static libraries are included inside the executable that is generated, so you don't need them to run the code.

When you build with _dynamic_ libraries, Windows also needs to open those libraries in order to **run** the program. While it doesn't search the entire computer, it does look in any location specified in the Windows PATH environment variable as well as in the directory where the main OpenFAST executable file is located to find those libraries. The Intel redistributable libraries do get put in a common location in `C:\Program Files (86)\`, but you don't need to touch them after they are installed in Intel's preferred location.

If you type
```
echo %PATH%
```
at a Windows command prompt, it should list that file location where the redistributable libraries are located (as well as many other locations). Then, you should be able to run the downloaded OpenFAST binaries from this command window in whatever directory you want. I **_have_** tried the binaries that NREL compiled and they do run on my PC.

If you don't see the file location when you echo the path environment variable, you may need to open a different instance of the command window to run OpenFAST. You will need to have opened the command window _after_ installing the Intel libraries so that the path variable is updated.

If you do see the location in the path variable and the code still doesn't run, you may have installed the wrong version of the Intel libraries for the openfast exeuctable or there may be another library that is missing. Showing the error message when you attempt to run the code will be most helpful (preferably a screen shot).

Just for comparison, when you run the OpenFAST exe created with cmake, this is the list of libraries it needs to find:
![image](https://user-images.githubusercontent.com/6108781/110978868-20a86b80-8321-11eb-8aee-40f3f77f064d.png)

When you run the OpenFAST exe created with the Visual Studio project, this is the list:
![image](https://user-images.githubusercontent.com/6108781/110978899-2c942d80-8321-11eb-82ae-b7f48211c3f1.png)

The differences don't mean something is "wrong". It's just different.

**Comment by Acrbjr** [comment]
Thanks for your response.  I think the issue may be that I used newer versions of the Intel compiler and libraries.  I am using compiler version Compiler 2021.1.1 Major Release that includes the patch release 2021.1.2.  I also downloaded the Intel libraries separately.
Anyway, the reason I wanted to download the open_fast.exe program was to verify that my compiled version was working properly.  This is because I re-ran a few of the test files and found slight differences between the .out files I generated with those provided by NREL.

Is there a possibility that I could obtain the Open-Fast.exe program with static libraries so I could make sure I get the same results?

Thanks,

Acrbjr





Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
