### ISSUE TITLE
Error run the openfast_win32orwin64_debug compiled by VS2017

### ISSUE THREAD

**Issue by RuiliangWang** [OpenFAST/openfast#693]
Dear everyone,

 I have recompile the OpenFAST (Debug,win32) with VS2017 and succeed without any errors. But when I open the OpenFAST_win32_debug, the  error happened shows :'Can not find the mkl_sequential.dll '  ,but when i run the release version, there are no problems ,It seems like  only the debug version have the problem .  Could you help me solve the problem?

Best regards.

**Comment by rafmudaf** [comment]
Did you run this from cmd.exe or from the Intel Parallel Studio command prompt?

**Comment by RuiliangWang** [comment]
when i use the cmd.exe ,the debug version shows the same error like above ,But when i use the Intel Parallel Studio command prompt ,if the openfast windows version and  Parallel Studio version is same ,running is normal . if the version is not identical (openfast-WIN32 with IPS IA-64) ,the error `0xc000007b` showed.

**Comment by rafmudaf** [comment]
This sounds like the expected behavior. If you're expecting to run OpenFAST compiled with the 64-bit Intel tools, you should use the 64-bit Parallel Studio command prompt. Same for 32 bit.

**Comment by RuiliangWang** [comment]
I have understand.But I have another question .If I copy the openfast_debug
.exe to another computer without the IPS, I have to run the openfast with the cmd.exe . Then how to solve the problem about  MKL?

**Comment by rafmudaf** [comment]
Actually, @bjonkman doesnt the VS project included with OpenFAST statically link the intel libraries? Is it required to run in an Intel cmd or install the redistributable libraries?

**Comment by bjonkman** [comment]
It does look like the VS project is using statically linked libraries, so I'm not exactly sure why you would have that issue with the debug version of OpenFAST: 
![image](https://user-images.githubusercontent.com/6108781/112872434-a1839900-907d-11eb-9685-bbaf86451dc2.png)

I personally do use dynamic libraries for the debug version, though, because there is a bug with using static debug libraries and math kernel libraries in the version of Intel Fortran I am using. Maybe you have a similar issue? 

Regardless, if you want to use the dynamic libraries on a different machine, you'll have to find the version of the Intel Redistributable libraries that corresponds with the compiler version you are using and install that wherever you want to run it from the cmd.exe prompt.

**Comment by RuiliangWang** [comment]
Thank you for your reply, It helps me  a lot
