### ISSUE TITLE
Problem with libmex.dll

### ISSUE THREAD

**Issue by salicto** [OpenFAST/openfast#705]
**Bug description**
Hello,

After compiling FAST.sln with visual studio. I get the OpenFast_x64.exe file. Then I want to build the version for matlab. I follow the procedure you describe. I add the link
in the additional dependencies on VS in the properties. I compile and get the following error: libmex.dll was not found. Has anyone had the same error? 

Thanks in advance,
![Bin_folder](https://user-images.githubusercontent.com/57439956/113608349-beeecf00-964a-11eb-914e-76c3d0c38ed6.JPG)
![visual studio](https://user-images.githubusercontent.com/57439956/113608529-01181080-964b-11eb-87f9-096372df6eb3.JPG)

**************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.5.0

**System Information
 - OS: window 10
 - Compiler: intel compiler fortran XE 2017
 - Compiler settings: Visual Studio  community 2015

**Comment by bjonkman** [comment]
Which version of Matlab do you have installed? 

You will probably need to update the path that is specified to use the version of Matlab you have installed. In the OpenFAST-Simulink project properties, go to the linker input configuration properties and replace the `R2019b` in the path name with the version you have:
![image](https://user-images.githubusercontent.com/6108781/113615227-d3ae7100-9610-11eb-99e0-e07871851ae8.png)

Make sure you keep the quotation marks around the path name because it contains a space.

**Comment by salicto** [comment]
I have the 2017 version of matlab. I have modified the link with my version. 
![Dependencies](https://user-images.githubusercontent.com/57439956/113621469-f1ed8e80-965b-11eb-836c-713ae9af2b21.JPG)

**Comment by bjonkman** [comment]
Okay, I'm not sure I understand _when_ you are getting the error. Does the `Release_Matlab | x64` configuration build properly (without a linking error)? This configuration should produce a file called `OpenFAST-Simulink_x64.dll`. That dll should be run only from inside the Matlab environment (it is called from the `FAST_SFunc.mexw64` file), not from inside Visual Studio. The libmex.dll file is a Matlab DLL that allows us to print to the Matlab command window; it won't work outside the Matlab environment.

**Comment by salicto** [comment]
This problem happens when I choose "release_matlab" on visual studio and I click on build the solution. I have a window that pops up telling me that the libmex.dll file was not found. 
![erreur](https://user-images.githubusercontent.com/57439956/113623649-ef406880-965e-11eb-96d8-f4404aa9ce82.JPG)

**Comment by bjonkman** [comment]
The screenshot you are showing looks like it is trying to **run** openfast_x64.exe, not just build the solution. 

Please make sure you have updated the correct project file with your Matlab path. It looks to me like you have **added** the dependency to the libmex file to the `FAST` project file instead of **modifying** the path on the `OpenFAST-Simulink` project file. You have to highlight the project you want to modify in the Solution Explorer before changing its properties or you may end up modifying a different project in the solution file.

Did you also modify the `Release_Matlab | x64` configuration to build the `FAST` project instead of the `OpenFAST-Simulink` project? When you build the Release_Matlab configuration, it should generate a DLL file for Simulink using the OpenFAST-Simulink project and **not build** the `FAST` project file at all.
![image](https://user-images.githubusercontent.com/6108781/113712160-05701800-96a3-11eb-8653-601c8a2f6457.png)

**Comment by salicto** [comment]
Thank you for your patience but I still can't do it. I carefully followed all the steps. I opened FAST.sln. I chose Release_matlab. Then right click on "openfast-simulink" and select "properties". I added the additional dependencies. I modified the project file "OpenFAST-Simulink.vfproj"
When I click on "build the solution", I get at the end this message: 
![openfast_x64](https://user-images.githubusercontent.com/57439956/113727925-e3ec4c00-96f5-11eb-83ee-4d10b7aee61c.JPG)

In my bin folder I do not have the right files to be able to then run the matlab script: "create_FAST_SFunc.m" 
![Bin_folder](https://user-images.githubusercontent.com/57439956/113728187-26158d80-96f6-11eb-87b9-96ecb83da259.JPG)

**Comment by bjonkman** [comment]
Did you change anything besides the path with the Matlab version in your Visual Studio configuration? It looks like it's not building the DLL. 

Can you show me a screenshot for the OpenFAST-Simulink project's general configuration properties? It should look like this:
![image](https://user-images.githubusercontent.com/6108781/113734039-3a3a9a00-96b8-11eb-9254-88f37dfe8aa1.png)

Also, can you attach a screenshot of your configuration settings for Release_Matlab (you'll find it in the "build->configuration manager" menu): 
![image](https://user-images.githubusercontent.com/6108781/113734380-884f9d80-96b8-11eb-9b63-8762531eb5c8.png)

**Comment by salicto** [comment]
I haven't changed anything. Maybe I should try removing everything and reinstalling everything? 
![config_Manager](https://user-images.githubusercontent.com/57439956/113735510-9a532f80-96fc-11eb-953a-66c76362979d.JPG)
![properties_simulink](https://user-images.githubusercontent.com/57439956/113735540-9fb07a00-96fc-11eb-817f-b5dcd4e427f6.JPG)

**Comment by bjonkman** [comment]
Strange... Does the build log for the OpenFAST-Simulink project show that it's building a DLL? If you go back in the Output window you showed earlier, there should be a link to the BuildLog.htm file that contains what commands it is running. I'm wondering if it is just completely ignoring that OpenFAST-Simulink project since it says it built only 3 projects.

If everything else looks normal, I'd probably first close Visual Studio and then try again. I'd also do a `git diff` on the Visual Studio projects to double check that nothing else got modified.

**Comment by salicto** [comment]
Hello,

I just fixed the problem. I deleted everything and I reinstalled everything following the procedure scrupulously and it works I can then generate the S-function on matlab. Anyway thank you for your help.
I would have liked to know if it is possible to add entries to the s-function block of simulink by modifying the servodyn.f90 file. I did not find the answer on this forum ... is it possible?

Anyway thank you very much
