### ISSUE TITLE
Issues compiling AeroDyn Driver for #688 & OpenFAST\dev branch

### ISSUE THREAD

**Issue by mayankchetan** [OpenFAST/openfast#719]
**Bug description**

I initially tried compiling the AeroDyn Driver using #688, but the `AeroDyn_Driver_Types.f90` file does not generate correctly while compiling AeroDyn Driver via the visual studio solution. Next, I tried compiling the AeroDyn Driver using the `dev` branch and had issues with the `Registry.lib` file.

**To Reproduce**

Steps to reproduce the behavior for #688:
1. Clone https://github.com/ebranlard/openfast/tree/f/driver .
2. Compile AeroDyn Driver using `AeroDyn_Driver.sln`.
3. Run generated `AeroDyn_Double_Driver.exe`, but no outputs/does not run.
4. Clear solution and re-compile.
5. Error while generating `AeroDyn_Driver_Types.f90`.

![image](https://user-images.githubusercontent.com/4620557/114970345-de9ea800-9e3f-11eb-8eea-5a61c2d54e96.png)

Steps to reproduce the behavior for `OpenFAST\dev` branch:
1. Clone `dev` branch
2. Compile AeroDyn Driver using `AeroDyn_Driver.sln` 
3. Error while generating `Aerodyn Driver`

![image](https://user-images.githubusercontent.com/4620557/115037120-c22c5b00-9e93-11eb-9533-62d1194afb5b.png)

**Expected behavior**

- No errors while generating `AeroDyn_Driver_Types.f90` for #688.
- No errors while generating AeroDyn Driver for `dev` branch.

**Screenshots, if applicable**

`.txt` appears where it's not expected

![image](https://user-images.githubusercontent.com/4620557/114970562-4b19a700-9e40-11eb-824e-9197e5bfaa33.png)

`AeroDyn_Driver_Types.f90` doesn't complete generating via `FAST registry`

![image](https://user-images.githubusercontent.com/4620557/114970585-553ba580-9e40-11eb-8b13-67171bcbc7dd.png)

**OpenFAST Version**

- https://github.com/ebranlard/openfast/tree/f/driver
- `dev`

**System Information (please complete the following information):**
 - OS: Windows 10 [20H2]
 - Compiler: [Intel OneAPI Fortran Compiler](https://software.intel.com/content/www/us/en/develop/tools/oneapi/hpc-toolkit/download.html) + Visual Studio 2019
 - Compiler settings: Release x64, Release Double x64

**Additional context**
- Able to compile OpenFAST for both https://github.com/ebranlard/openfast/tree/f/driver branch & `OpenFAST/dev` branch with the current setup.

Note: Please let me know if I should split this into two issues, one for #688 and one for the `dev` branch.

**Comment by ebranlard** [comment]
Hi @mayankchetan 

Thanks for your report, I had not caught this error which indeed occurs when you clean the solution. The RunRegistry.bat needed to include InflowWind as an include path for Aerodyn. I hope my latest commit fixes the issue. 

As for your issue compiling dev I cannot reproduce it, but I have a different setup than you unfortunately (earlier Fortran and Visual studio).  Are you able to compile the dev openfast.exe?  There has been are a couple of open issues related to compiling openfast with visual studio lately. I wonder if some of them might help: #322 #714 #697 #649

If you think it's an aerodyn_driver issue, we can try to dive more into it, otherwise it might make sense to create a separate issue. 

Thanks

**Comment by mayankchetan** [comment]
Hi @ebranlard,

Thank you for the update, I tried out your latest commit and it was able to resolve the `AeroDyn_Driver_Types.f90` issue.

Sadly, it falls back to the `dev` branch issue for the AeroDyn driver that I have pointed above. 

Yes, I am able to compile `OpenFAST.exe` for both the `dev` branch and `f/driver` branch (corresponding to #688).

Please let me know if there is any information that I can provide.

Thank you!

**Comment by ebranlard** [comment]
Ok, thank you for trying it out. So somehow the linker wants to add "Registry.lib" to the exe, but actually the registry is not to be linked with our exe. I don't know what's different with the openfast project that triggers this on your setup. 


@bjonkman  do you have this issue?

**Comment by bjonkman** [comment]
@ebranlard , there was another issue like this regarding OpenFAST a while back. It seems like newer versions of Visual Studio try to link a Registry library when the main project depends on the Registry executable (set in the project dependencies) and "link library dependencies" is enabled. In the OpenFAST solution file, I removed the dependency of the Registry from the main executable and that solved the issue. In this case, the solution file is set up a little differently so we might have to change the link dependencies. I would try changing "Link Library Dependencies" to "No" in the AeroDyn driver properties window and see if that fixes the issue.

![image](https://user-images.githubusercontent.com/6108781/115294683-22caca80-a116-11eb-85c0-f872a6f53c20.png)

**Comment by mayankchetan** [comment]
Thank you for the inputs @ebranlard @bjonkman, changing "Link Library Dependencies" to "No" helps with compiling the AeroDyn driver.

But looks like the compiled `AeroDyn_Driver_x64_Double.exe` is not responding to begin called or when I pass it the AeroDyn driver input file.

**Comment by ebranlard** [comment]
Thanks bonnie, so we are making progress. I'll likely submit a pull request to fix the "Link Library Dependencies" issue. 

The only time I've seen exe that didn't reply, was for FastFarm compiled with OpenMP, and it depended on how I chose the the runtime library option. 

Can you try desactivating OpenMP and seeing if that works for you
 `Configuration Properties->Fortran->Language -> Process OpenMP directives: False`

If you find that OpenMP is the issue, can you try activating it, but experimenting with different options for the Runtime library: 
 `Configuration Properties->Fortran->Libraries -> Runtime Library`
I think Bonnie recommends Multithread DLL, but I recall that in the past I had to used Multithreaded on my machine... 

Let us know if that helps.

**Comment by mayankchetan** [comment]
Hi @ebranlard,

Looks like the "Link Library Dependencies" issue exists for other independent module drivers as well.

I've been trying the options you mentioned and along with other compiler settings like precision, but haven't had an AeroDyn Driver program run successfully. I was able to get a working BeamDyn Driver so I think that would eliminate the setup I have (compared the settings in the configuration properties, they were identical).

Since you mentioned fastfarm and OpenMP, I've seen that issue too when I tried compiling the OMP version. The single-threaded program runs fine.

do you have any other recommendations?

Thank you.

**Comment by ebranlard** [comment]
Hi @mayankchetan, 

I don't really have other thoughts right now, I would have really hoped that  turning off openmp or changing the runtime library options would have done it. 

Something you could try would be to close Visual Studio and compare the BeamDyn.vfproj and AeroDyn_Driver.vfproj (using a text comparator like WinMerge), focusing on one configuration (Win32 Debug for instance, if that's the one you are compiling with), and progressively making these configurations match for the AeroDyn driver, and trying to compile AeroDyn_Driver. The configurations are defined at the top of the vproj file. Some file specific options are given below, but I hope it's not in those.

**Comment by mayankchetan** [comment]
Hi @ebranlard!

Looks like OpenMP was at fault. Editing the `AeroDyn_Driver.vproj` file to remove OpenMP for `FVW_BiotSavart.f90` solved it. Thank you for your help on this!

I know this is an ad-hoc solution to avoid OpenMP. Do you know of any long-term fixes especially since I'm trying to compile fast.farm with OpenMP?

Closing issue since I'm able to compile AeroDyn Driver for both #688 and `dev`.

**Comment by ebranlard** [comment]
Thank you for testing that. I've removed OpenMP in the AeroDyn project of dev for this FVWBiotSavart file, I've kept it as a general project option for now... It seems the AeroDyn driver would be a good case to experiment (since it might take less time than FastFarm to recompile). 

Most likely, it's a question of which dll are available (in the system path) when running the executable.

If you have the time, there are a couple of things to try:


- Within visual studio, some path are set. You can try running the executable from Visual Studio (maybe as a post build event, I'm not too familiar with how to do that). That should work. 

- it might be worth trying again some of these RunTime library options with OpenMP enabled as a global project option, to see which one can generate an exe that works for you.  

- Sometimes, double clicking on the exe, instead of running it from a terminal displays an error message of which dll is not found. That can give some hint. On my machine, for FAST.Farm, I can see that mkl_sequential.dll and mkl_core.dll were missing. You can try to find where they are on your machine, copy them next to the exe, or add their path to your system path. 

- You can use the dependency walker tool, to see which dll are needed and can't be found. 

- You might need to setup up your system path so that these dlls are found (maybe reinstall a visual studio redistribuate would do that). 

I hope that helps.
