### ISSUE TITLE
Warning in header file

### ISSUE THREAD

**Issue by jrood-nrel** [OpenFAST/openfast#73]
Is it possible to fix this warning directly in OpenFAST?

```
include/FAST_Library.h:37:12: warning: ‘AbortErrLev’ defined but not used [-Wunused-variable]
```

**Comment by rafmudaf** [comment]
hmm ... but it is used:
https://github.com/OpenFAST/openfast/blob/master/modules-local/fast-library/src/FAST_Library.f90#L411
@gantech ?

**Comment by jrood-nrel** [comment]
Then it should probably just be declared in fortran and not the header?

**Comment by gantech** [comment]
Ah.. yes.. I have to fix this issue. The warning keeps showing up on every compile. The problem is I do use it in C++ as well here https://github.com/OpenFAST/openfast/blob/master/glue-codes/fast-cpp/src/OpenFAST.cpp#L322. So I need to remove including this file from OpenFAST.H and just include it directly in OpenFAST.cpp.

**Comment by gantech** [comment]
Fixed through https://github.com/OpenFAST/openfast/pull/76
