### ISSUE TITLE
Skewed wake correction applied outside of root finding iteration

### ISSUE THREAD

**Issue by nkr0** [OpenFAST/openfast#780]
**Bug description**
Reference for this issue is NREL/CP-5000-63217 "Development and Validation of a New Blade Element Momentum Skewed-Wake Model within AeroDyn". At the end of Section III, it says "The only modiﬁcation is that a_yaw is used in Eq. (22) instead of a." Eq. 22 being the residual equation. However, in OpenFAST, as far as I can tell, a_yaw is applied after finding a root. Wouldn't this change the residual?

**Details**
This is the only call to skewed wake model I could find, and it is outside of `subroutine sub_brent`. https://github.com/OpenFAST/openfast/blob/bbbb1ca7b28a4ba411613b5c85f5de02f8316754/modules/aerodyn/src/BEMT.f90#L1636
Inside `sub_brent`, we've calls to `BEMTU_InductionWithResidual`. https://github.com/OpenFAST/openfast/blob/bbbb1ca7b28a4ba411613b5c85f5de02f8316754/modules/aerodyn/src/mod_root1dim.f90#L223
Within `BEMTU_InductionWithResidual`, or `inductionFactors` (which computes the induction factor and residual), https://github.com/OpenFAST/openfast/blob/bbbb1ca7b28a4ba411613b5c85f5de02f8316754/modules/aerodyn/src/BEMTUncoupled.f90#L414-L428 there is no mention of a skewed wake model.

**Expected behavior**
Skew factor should be applied inside `inductionFactors`, such that the residual is computed with the skew factor.

**Comment by jjonkman** [comment]
Dear @nkr0,

I can't comment on the original meaning of the sentence you reference in the paper, but it was our intent to implement the skewed-wake correction after the BEMT iteration.  This is not a bug.  And when DBEMT is enabled, the skewed wake correction is applied to the dynamic inductions after DBEMT is called as well.  This is also by design.

The basic idea is that BEMT inductions are solved based on the blade-element / momentum (BEM) iteration (and DBEMT, if enabled, is solved as well), and the skewed wake correction is applied afterwords.  Indeed, the Pitt and Peters model is a correction between what happens in uniform flow normal to the disk, where BEM applies, and what happens in uniform skewed flow (granted, in AeroDyn, the skewed-wake correction is applied even when local wind and structural conditions are used in the BEM iteration.)  This skewed wake will effect the local induction, local inflow angle, and angle of attack before the unsteady airfoil aerodynamics model and aerodynamic loads are calculated.

Best regards,

**Comment by nkr0** [comment]
Thanks for the response.
