### ISSUE TITLE
Maximum number of outputs

### ISSUE THREAD

**Issue by pschuenemann** [OpenFAST/openfast#796]
Hi,

OpenFAST and MoorDyn are having a limit of the maximum number of outputs a user could request.

In OpenFAST this is set by `INTEGER(IntKi), PARAMETER             :: MAXOUTPUTS = 4000        ! Maximum number of outputs` in [FAST_Library.f90](https://github.com/OpenFAST/openfast/blob/42a5a8196529ae0349eda6d797a79461c2c03ff0/modules/openfast-library/src/FAST_Library.f90) in line 24. In MoorDyn it's set by `CALL AllocAry( InitInp%OutList, 1000, "MoorDyn Input File's Outlist", ErrStat2, ErrMsg2 )` in [MoorDyn_IO.f90](https://github.com/OpenFAST/openfast/blob/42a5a8196529ae0349eda6d797a79461c2c03ff0/modules/moordyn/src/MoorDyn_IO.f90#L578) in line 578 .

As I overshoot these limits in some special simulations, I was wondering whether there is a specific reason for these limits?
If yes, is there a reason for choosing those values (4000 and 1000)?

If there are no specific reasons, what do you think of removing these limits?

Any thoughts and ideas on this are appreciated.

Best regards,
Paul

**Comment by bjonkman** [comment]
The `MAXOUTPUTS` parameter is the maximum number of outputs passed through the C/C++ interface (e.g., for Simulink or CFD). That interface uses a fixed-length array to pass the outputs from Fortran to C, and `MAXOUTPUS` determines the size of that array. You can certainly change it if necessary, though you should make sure you change both the Fortran and C sides of the interface. If you run the normal OpenFAST executable, that maximum value is not used (the output files can contain _any_ number of channels).

I am less familiar with the MoorDyn module. Typically the OpenFAST modules store an integer indicating the maximum number of unique outputs that the module can generate. They will then allocate an array of that size to read in the outputs that a user requests (this allocation is done _before_ the code knows how many variables it needs to read). It looks like MoorDyn has set it to an arbitrary large number. You should be able to increase the size of that array (and re-build) without any issue.

Rather than remove the limits, it would be much easier to just increase them.

**Comment by pschuenemann** [comment]
Hi @bjonkman,

Thank you very much for your fast answer.
That makes sense. I also already thought about just increasing them, but than was wondering why they are needed at all. So, now I know. Thanks. Especially, I wasn't aware of the dependencies regarding the C/C++ interface.
Thanks also for your description of the typical behaviour of the OpenFAST modules. That was enlightening.

Best regards,
Paul
