### ISSUE TITLE
Build the floating platform model

### ISSUE THREAD

**Issue by robytian** [OpenFAST/openfast#797]
Dear all,
What do I need to do if I want to build a new floating platform model in OPENFAST? The methods I know so far:

1. Solve the potential flow solution through WAMIT, and call the.1,.3,.hst files in HydroDyn. Besides, what else do I need to modify about HydroDyn and MoorDyn modules to realize the calculation of my new model (perhaps this question can be understood as how do these two modules know the geometric characteristics of my calculation model, Is it due to the file results calculated by WAMIT? 

2. Modeling and solving frequency domain solution in software such as AQWA, and orcaflex is imported to solve the time domain solution and mooring related parameters. CompMooring directly selects Orcaflex for calculation in the main file. 
If the above method does not require any changes to HydroDyn and MoorDyn, how does OPENFAST know the geometric characteristics of the model I calculate, just from the output file of Orcaflex?
@jjonkman I would appreciate it if you could help me with the answer.

Best regards,

**Comment by jjonkman** [comment]
Dear @robytian,

Here are my answers to your questions:

1. HydroDyn allows the user to model the hydrodynamics via a potential-flow solution (based on the output from WAMIT or the like), a strip-theory solution (based on an extended Morison formulation), or a hybrid combination of these two.  For a potential-flow solution, HydroDyn does not need to know the floater geometry; the hydrodynamic coefficients provided by WAMIT (or equivalent) suffice.  For the strip-theory solution, the geometry is specified within HydroDyn via joints and members.  In MoorDyn, the geometry of the mooring system (fairlead and anchor positions, connection points, mooring line lengths, etc.) are specified within the MoorDyn input file.

2.  If you select CompMooring = 4 (for the OpenFAST-OrcaFlex interface), the hydrodynamics and moorings are solved within OrcaFlex, in which case MoorDyn is not used and HydroDyn should be disabled (CompHydro = 0).  Again, in this case the floater geometry does not need to be known by OpenFAST because it is solved within OrcaFlex.

Best regards,

**Comment by robytian** [comment]
> Dear @robytian,
> 
> Here are my answers to your questions:
> 
> 1. HydroDyn allows the user to model the hydrodynamics via a potential-flow solution (based on the output from WAMIT or the like), a strip-theory solution (based on an extended Morison formulation), or a hybrid combination of these two. For a potential-flow solution, HydroDyn does not need to know the floater geometry; the hydrodynamic coefficients provided by WAMIT (or equivalent) suffice. For the strip-theory solution, the geometry is specified within HydroDyn via joints and members. In MoorDyn, the geometry of the mooring system (fairlead and anchor positions, connection points, mooring line lengths, etc.) are specified within the MoorDyn input file.
> 2. If you select CompMooring = 4 (for the OpenFAST-OrcaFlex interface), the hydrodynamics and moorings are solved within OrcaFlex, in which case MoorDyn is not used and HydroDyn should be disabled (CompHydro = 0). Again, in this case the floater geometry does not need to be known by OpenFAST because it is solved within OrcaFlex.
> 
> Best regards,

Thank you for your reply.
Best regards,
