### ISSUE TITLE
Turbsim

### ISSUE THREAD

**Issue by Unique-Wang** [OpenFAST/openfast#810]
Dear@jjonkman,

I'm a bit confused lately about the use of TurbSim,I wanna know how can I generate  wind files with a .WND extension through changing the parameters in the inuput file,I've tried so many times to make it closer to the output I want ,but always not very satisfactory（i.e Tiu,Yiv,Tiw）,and the process is a bit time-consuming,so is there any way to make it right? Thank u!

Best regards,

**Comment by Unique-Wang** [comment]
To show you what I mean,here's a screenshot I found in#334,
![image](https://user-images.githubusercontent.com/87693817/129518518-7dfff8bd-6246-40a1-bc9b-ce238b21f164.png)
if i wanna get  the same Ti(u),Ti(v) and Ti(w) showed in the screenshot ,what should I do?

Best regards,

**Comment by Unique-Wang** [comment]
To show you what I mean,here's a screenshot I found in#334,
![1629094315(1)](https://user-images.githubusercontent.com/87693817/129518873-1da0c3ee-ed0f-49bd-b20f-429f095d6198.png)
if i wanna get  the same Ti(u),Ti(v) and Ti(w) showed in the screenshot ,what should I do?

Best regards,

**Comment by Unique-Wang** [comment]
To show you what I mean,here's a screenshot I found in#334,
1629094315(1)
if i wanna get the same Ti(u)41.86% ,    Ti(v) 33.49% ,and Ti(w)20.93% showed in the screenshot ,what should I do?

Best regards,

**Comment by Unique-Wang** [comment]
To show you what I mean,here's a screenshot I found in#334,
![image](https://user-images.githubusercontent.com/87693817/129519121-1601f72e-2b68-4c09-b574-988ea45b592f.png)

if i wanna get the same Ti(u)41.86% , Ti(v) 33.49% ,and Ti(w)20.93% showed in the screenshot ,what should I do?

Best regards,

**Comment by jjonkman** [comment]
Dear @Unique-Wang,

I'm not sure I understand your question; can you clarify what issue you are facing?  Is the problem that you are getting different turbulence intensities than you prescribe?  What settings have you specified in your TurbSim input file?

Best regards,

**Comment by Unique-Wang** [comment]
Dear @jjonkman ，

I don't know how to prescribe turbulence intensities .For  instance ,what should I do if I wanna prescribe 41.86% for Ti(u) , 33.49% for Ti(v) ,and 20.93% for Ti(w)  ,and the settings what I have specified are show in the screenshot below

![1629162160(1)](https://user-images.githubusercontent.com/87693817/129647605-6a81ce2b-f161-4ed3-a29a-56149aecb702.png)

 I've used  so many different values trying to figure out how they affect turbulence intensities respectively ,but still couldn't get the output I want .Sorry I didn't make my question clear enough.

Best regards,

**Comment by jjonkman** [comment]
Dear @Unique-Wang,

The various turbulence models (`TurbModel`) have specific predifined standard deviations across the u-, v-, and w-components of the turbulence, i.e., setting the u-component turbulence intensity via `IECturbc` will result in specific standard deviations of the v- and w-components.  If you wish to override these default models and prescribe your own standard deviations, you'll need to use the  user-defined velocity spectra model (`TurbModel` = "USRINP").  See the TurbSim v2.00 documentation for more information: https://drive.google.com/file/d/1h92h8QqgzvVGmz7c078CV27vC0hoOiPx/view?usp=sharing.

Best regards,

**Comment by Unique-Wang** [comment]
Dear @jjonkman ，

Your answers are always helpful! And I have another problem here ,when I  was trying to run it in turbsim, a problem occurred .To show you what I mean, here's a screenshot I got
![1629258051](https://user-images.githubusercontent.com/87693817/129840488-2119cb8d-55b2-4fe9-9c3f-5a7324dbcf52.png)
I don't know why is this happening ,and could you please tell me  how to fix it?

Best regards,

**Comment by jjonkman** [comment]
Dear @Unique-Wang,

The first error is generated because the TurbSim input file you are using is formatted for TurbSim v1.50, but the version of TurbSim you are using is TurbSim v2.00.  The input file format has changed between these versions of TurbSim.  There are sample TurbSim v2.00 input files available in the corresponding archive: https://www.nrel.gov/wind/nwtc/assets/downloads/TurbSim/TurbSim_v2.00.07a-bjj.exe.

These turbulence scaling variables from the InflowWind module input file are valid only for HAWC-formmated wind data files and are documented in the InflowWind User's Guide.  The version of this guide on readthedocs is not yet complete, but the original and more complete PDF version is available from: https://www.nrel.gov/wind/nwtc/assets/downloads/InflowWind/InflowWind_Manual.pdf.

Best regards,

**Comment by Unique-Wang** [comment]
Dear @jjonkman ，

Thank you for your reply ,and I realized that must has something to do with the  versions of  TurbSim, and I replaced the original input file in  folder **5MW_Baseline\Wind** with this
![1629351717(1)](https://user-images.githubusercontent.com/87693817/130014257-1d9ef715-e3e5-46d2-a362-f356b1e23d85.png)
No errors occurred when I was running it in TurbSim v2.00 ,but after that when I was running **5MW_Land_DLL_WTurb.fst** in OpenFAST ,encountered this error
![1629351388(1)](https://user-images.githubusercontent.com/87693817/130013731-2e2b1bcf-3c86-4f63-8f0e-8e28f74dc02d.png)

How am I gonna fix that?

Thank you!

Best regards,

**Comment by SkyupChen** [comment]
Dear @jjonkman,
I have encountered a problem when using pre-compiled OpenFast version 2.4 to call Bladed style wind file generated by Turbsim (either version 1.06 or 2.0). The error message I got is shown below as highlighted. 
![openfastwindproblem](https://user-images.githubusercontent.com/89191738/130060102-ecf75a1b-e1cb-4322-93b5-b2f2fd88e66a.JPG)
I had tried to search the solution but I can't really find it anywhere. According to the OpenFast user manual, the "WindType" is set to 7 in my case and without a Bladed style scaling file. In case of setting to 4, with a scaling factor intermediate file, the same error message occurred as well. 
I am running the pre-compiled OpenFast version 2.4 for the IEA 15MW model. I am able to run simulation with steady wind speed. 
Did I do anything wrong? Could you please help me with this problem?
Many thanks in advance!
Best Regards,

**Comment by jjonkman** [comment]
Dear @Unique-Wang,

This error is generated because your wind domain starts at 17.5 m above the ground, but you have aerodynamic analysis nodes on the tower (that need wind data) at locations lower than 17.5 m.  You can fix this either by changing the TurbSim settings so that the wind domain extends lower to the ground or by changing the AeroDyn settings so that the first tower node is higher than 17.5 m.

I'm not sure why you want to use the Bladed format for wind data; I tend to prefer the TurbSim format myself because then I don't have to worry about having to keep the corresponding summary file needed by InflowWind to process Bladed formatted wind data.  To use the native Bladed format, you must set WindType = 7, then FileNameRoot should locate the name and directory of the native Bladed scaling file.

Dear @SkyupChen,

The support for native Bladed files was added in OpenFAST v2.5; you'll need to upgrade your version of OpenFAST if you wish to use this feature.

When you set WindType = 4, can you clarify what issue you are running into?

Best regards,

**Comment by SkyupChen** [comment]
Dear @jjonkman,
Many thanks for your quick reply!

I meant when I used WindType = 4 and used the scaling input file, I also got the same error message. 

I shall try to run OpenFast v2.5 and come back to you whether I get it works. 

Best Regards,

**Comment by bjonkman** [comment]
@SkyupChen , I don't believe that you got the "same" error when using WindType = 4 as WindType = 7. In some prior versions of OpenFAST, WindType = 7 was used internally for FAST.Farm simulations, which is what your error message states. If you got the same error message when using WindType = 4, you should double-check that you are using the InflowWind input file that you edited.

In more recent versions of OpenFAST, WindType=7 is the native Bladed format (and WindType=8 is used internally for FAST.Farm). Note that "native Bladed" format is **not** the same as the Bladed format generated with TurbSim, unless you are running IEC turbulence models with ScaleIEC=2 and have omitted shear when generating the file with TurbSim. 

Based on your TurbSim input file, you should use WindType = 4, and then make sure that the TurbSim summary file is stored in the same directory as the .wnd file generated by TurbSim, so that it can read both <RootName>.sum and <RootName>.wnd. Then specify that <RootName> in the InflowWind input file under the section for Bladed inputs. You could also use WindType=3 and have it read the <RootName>.bts file instead.

**Comment by SkyupChen** [comment]
Dear @bjonkman, 
Thanks a lot for your clarifications. Indeed I was wrong in case of WindType =4. I had tried it just now and actually I get the same error as @Unique-Wang's last post.

But ok, so for the "native Bladed" format, ScaleIEC should be equal to 2 and the wind shear factor should be 0, is it right? is it then the format is identical to the wind files as generated by GH Bladed software? When WindType =7, does it then mean I can also directly call to the wind files as generated by GH BLaded?

The more recent versions of OpenFAST, do you mean version 2.5 and later versions as already mentioned by @jjonkman, in order to use WindType = 7? 

@jjonkman, I had the same error as @Unique-Wang has about the wind grid position. By following your explanation, I had tried these two options. In my example, a 260m wind grid was generated in TurbSim and the hub height is being 150m, so I get a lowest point 20m above ground. For the first option, I had created a wind grid of 299m and it actually runs through. For option 2, to be more specific, when using 260m wind grid, I then Changed the first "TwrElev" from 15 to 21, which is then higher than the lowest point of wind grid, and the simulation run through as well. But for me to be clear, the "NumTwrNds" is used for the analysis only and the first "TwrElev" node's elevation can be set to any value unless it is higher than the last station of substructure and it does not influence the tower base output, since tower base and tower top output is not belong to the range of "NTwOuts", am I right? 

Many thanks in advance!

Best Regards,

**Comment by jjonkman** [comment]
Dear @SkyupChen,

Regarding your quetions to @bjonkman, I would answer yes to all of your questions.

I'm not sure I understand your question regarding `TwrElev` and `NTwOuts`; please clarify.  I did mean--as you said--that option 2 is for the first `TwrElev` to be within the wind domain (likely not at the tower base or ground level).

Best regards,

**Comment by SkyupChen** [comment]
Dear @jjonkman,

Thanks a lot for your confirmation regarding questions to @bjonkman. I understood in the way that the intermediate scaling file is required while running native Bladed wind file, i.e. WindType = 7, where the wind file is either generated by GH Bladed or TurbSim. I am now able to use OpenFAST version 2.5 to make use of this features and get it works. (so WindType = 4 and WindType=7 both work in my case).

Regarding TwrElev and NTwOuts, what I meant here is that: the tower base and tower top (yaw) output list is specified via ElastoDyn file, and they are not related to the tower node output as specified by NTwOuts that given in AeroDyn file, so the first TwrElev can be given for a value higher than ground (if onshore) or higher than the top position of sub-structure (if offshore foundation fixed), for the purpose of letting it be within the wind grid point. Do I understand it good? 

Best Regards,

**Comment by jjonkman** [comment]
Dear @SkyupChen,

I'm glad `WindType` = 4 and 7 are now working for you.

The structural discretization in ElastoDyn is independent from the aerodynamic discretization in AeroDyn, so, yes, the lowest `TwrElev` specified in AeroDyn does not need to align with the tower-base location in ElastoDyn.  And the AeroDyn tower nodes must lie within the wind domain.  When the aerodynamic loads applied to the tower are transferred from AeroDyn to ElastoDyn, there will be no aerodynamic loads applied to the tower in ElastoDyn between the ElastoDyn tower base and lowest `TwrElev` specified in AeroDyn.

Best regards,

**Comment by SkyupChen** [comment]
Dear @jjonkman,

Ok, I see now. So in order to cover as much the aerodynamic loading transferred from AeroDyn to ElestoDyn as possible, the better way would be to use a larger wind grid.  This would be good for onshore tower. But in case of offshore foundation fixed, for example in my example, the top position of sub-structure is 15m above MSL, and the first elevation of TwrElev has to be at least 15, otherwise the line2 mapping will give error, in this case, how do you calculate the aerodynamic loading for structure part starting from MSL to 15m? 

Best Regards,

**Comment by jjonkman** [comment]
Dear @SkyupChen,

Correct.

OpenFAST only currently supports aerodynamic loading of the tower (a mapping from AeroDyn to ElastoDyn).  No functionality currently exists for computing aerodynamic loads on the substructure (SubDyn or the platform in ElastoDyn).

Best regards,

**Comment by SkyupChen** [comment]
Dear @jjonkman,

Thanks a lot for your explanation! It is clear.

Best Regards,
