### ISSUE TITLE
Tower dam model; potential flow: equations wrong

### ISSUE THREAD

**Issue by rwegnerGermany** [OpenFAST/openfast#837]
**Bug description**
In AeroDyn v15 AeroDyn.f90 TwrInfl() the equations seem to differ to AeroDyn **v14** and AeroDyn theory manual.
Or am I simply unable to rearrange the equation?
`u_TwrPotent = ( -1.0*xbar**2 + ybar**2) / denom`

**Expected behavior**
Disturbance factor for u-component due tower potential flow must be (according to AeroDyn theory manual and AeroDyn v14):
`u_TwrPotent = 1.0 - (xbar**2 - ybar**2) / denom`

**OpenFAST Version**
All OpenFAST AeroDyn v15

Edit:
More precise wording.

**Comment by jjonkman** [comment]
Dear @rwegnerGermany,

I assume you are referring to the 2005 AeroDyn Theory Manuel from Moriarty and Hansen: https://www.nrel.gov/wind/nwtc/assets/pdfs/ad-theory.pdf.  Actually, Eq. [111] is not written correctly in this manual because the disturbance should be based on the wind velocity at the tower and this disturbance should be added to the wind velocity local to the blade element (the 1 in Eq. [111].  Regardless, u_TwrPotent within the source code represents only the disturbance from the tower, not the total wind speed.  This is not a bug.

Best regards,

**Comment by jjonkman** [comment]
Dear @rwegnerGermany,

I'm not too familiar with the implementation in AeroDyn v14, but the AeroDyn v15 implementation is as intended.  I agree that `u_TwrPotent` is multiplied by `W_tower`.  This term is then added to the wind velocity local to the blade element elsewhere in AeroDyn, to mimic the effect of the "1" in Eq. [111], which is only valid for uniform inflow, where the wind velocity local to the blade is identical to the wind velocity at the tower.  AeroDyn v15 allows for the wind velocities local to the tower and local to the blade to differ before applying the disturbance.

Best regards,

**Comment by rwegnerGermany** [comment]
Dear @jjonkman ,
thank you very much for the explanation!
I only was impressed by the power loss due to the tower potential flow with Bak correction (see below).
I think I will stick to the baseline model as the colleagues in this paper did: [https://iopscience.iop.org/article/10.1088/1742-6596/1618/5/052052/pdf](url)

![grafik](https://user-images.githubusercontent.com/69688683/134309893-15e2434e-b390-4821-ae46-2217582e5f7e.png)
