### ISSUE TITLE
Invalid AbortLevel specified in FAST input file.

### ISSUE THREAD

**Issue by leggod1004** [OpenFAST/openfast#903]
Hello. I am beginner in offshore wind power.
I tried to run OpenFAST, however I could not run it because of the error as below.

```
C:\openFAST\AeroDyn_inputs>openfast_x64.exe ad_primary_example.inp

**************************************************************************************************
OpenFAST

Copyright (C) 2021 National Renewable Energy Laboratory
Copyright (C) 2021 Envision Energy USA LTD

This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
See the "LICENSE" file distributed with this software for details.
**************************************************************************************************

OpenFAST-v3.0.0
Compile Info:
 - Compiler: Intel(R) Fortran Compiler 1900
 - Architecture: 64 bit
 - Precision: single
 - OpenMP: No
 - Date: Jun 23 2021
 - Time: 21:25:05
Execution Info:
 - Date: 11/02/2021
 - Time: 15:40:17+0900

OpenFAST input file heading:
    Description line that will be printed in the output file and written to the screen.


FAST_InitializeAll:FAST_Init:FAST_ReadPrimaryFile:Invalid AbortLevel specified in FAST input
file. Valid entries are "WARNING", "SEVERE", or "FATAL".

 OpenFAST encountered an error during module initialization.
 Simulation error level: FATAL ERROR

 Aborting OpenFAST.
```

I thought the format of the input file is not the latest version. So I tried to find information about `AbortLevel` from [AeroDyn Users Guide and Theory Manual](https://openfast.readthedocs.io/en/main/source/user/aerodyn/index.html), but I couldn't.
And I also tried to write `AbortLevel` in  `ad_primary_example.inp`. However another error was occured as `Tmax`.

1) How to fix this error?
2) and if I downloaded wrong input files, where can I get the latest version of input file and format?

I downloaded these files.
`openfast_x64.exe`,`MAP_x64.dll` from [github releases](https://github.com/OpenFAST/openfast/releases).
 `ad_primary_example.inp` from  [openfast.readthedocs.io](https://openfast.readthedocs.io/en/main/source/user/aerodyn/appendix.html#aerodyn-input-files).

Thank you.

**Comment by jjonkman** [comment]
Dear @leggod1004,

It looks like you are using an AeroDyn primary input file instead of an OpenFAST primary input file, which NREL generally names with a _*.fst_ extension.  Are you trying to run a coupled OpenFAST simulation or a standalone AeroDyn simulation?

Full OpenFAST models, including the associated OpenFAST primary input files, are available in the OpenFAST r-test: https://github.com/OpenFAST/r-test.

To run standalone AeroDyn, you'd first have to compile the standalone AeroDyn driver executable (which NREL has not precompiled and provided) using the provided source code and compile scripts, and then when the standalone AeroDyn executable is run, you need to use an AeroDyn driver input file (e.g., https://openfast.readthedocs.io/en/main/_downloads/116c42a5b36da89f920252c54d37d53f/ad_driver_example.inp) rather than an AeroDyn primary input file.

Best regards,

**Comment by leggod1004** [comment]
@jjonkman 
Thank you for answer.
