### ISSUE TITLE
SSI in SubDyn

### ISSUE THREAD

**Issue by DaraeShin** [OpenFAST/openfast#961]
Dear, all

I have modeled the monopile with flexible foundation and checked the reaction force.
I used SSI to give boundary conditions in SubDyn.
However, the following error occurs.
 
![LC4 1b error](https://user-images.githubusercontent.com/95604833/148473221-13c9726c-d0f4-49ea-8765-c69c64a30f9e.PNG)

Reaction Joint condition is below.
![image](https://user-images.githubusercontent.com/95604833/148473586-b5a3c396-b380-419e-8126-55817e336a0b.png)

Could you help what the problem is?

Best regards,

**Comment by ebranlard** [comment]
The structure likely has some rigid body modes due to too low stiffness's at the sea bed. 
Here's some things you can try to debug your model: 
- Use "Echo = True" in the SubDyn file and look at the .SD.ech file  generated to see if the SSI matrix match what you entered. 
- Try freeing only one degree of freedom at a time to get an idea of which stiffness is likely too low or causing an issue. 
- Try increasing the stiffnesses of your SSI file
If none of this help, you can paste your SSI file here, we can have a look at it.

**Comment by DaraeShin** [comment]
Dear @ebranlard,

I try to free only one degree of freedom (RctTDXss=0). There is no error.
However, I'm worried that there will be a difference in the results if the degree of freedom in reaction join is changed due to rigidity.

Is there no difference in the reaction force results of the substructure if the DOF is changed?

**Comment by jjonkman** [comment]
Dear @DaraeShin,

The response of the structure will certainly be different if the DOF is locked rather than enabled with a stiffness applied.  But as @ebranlard said, your model does not likely have an appropriate stiffness set.  You should be able to enable the DOFs you want if you specify an appropriate stiffness in the SSI file.

Best regards,
