### ISSUE TITLE
Tower Top Fore-aft Deflection for the IEA15MW UMiane Model

### ISSUE THREAD

**Issue by QusayHawari** [OpenFAST/openfast#963]
Hello,

I was checking some of the responses of the IEA15MW UMaine model using the ROSCO controller in the above rated zone. 

I wanted to ask about the tower top fore-aft deflection [m] shown below.  for a step wind change from 14-15m/s.

![TTFA_Disp](https://user-images.githubusercontent.com/91909348/148813750-ce1e8ed5-3c7f-4ff9-b8c0-af6a0fae3783.jpg)

Is a deflection of around 17 meters realistic? I am using TwrTpTDxi as the output.

Thanks,
Qusay.

**Comment by jjonkman** [comment]
Dear @QusayHawari,

That would be large if it was pure tower-top deflection relative to a rigid tower.  But this specific output from ElastoDyn also includes floating platform motions (e.g., surge, pitch), which I would guess is dominating this output.  If you want just the elastic deflection of the tower (not including rigid-body motion of the floater), you can use ElastoDyn output TTDspFA.

Best regards,

**Comment by QusayHawari** [comment]
Hello,


Great! 

Thanks for the clarification.

![TTDspFA](https://user-images.githubusercontent.com/91909348/148931520-4edec290-45ff-432a-ad46-77d18047d8bc.jpg)

Qusay.

**Comment by AssiduousAsule** [comment]
> Dear @QusayHawari,
> 
> That would be large if it was pure tower-top deflection relative to a rigid tower. But this specific output from ElastoDyn also includes floating platform motions (e.g., surge, pitch), which I would guess is dominating this output. If you want just the elastic deflection of the tower (not including rigid-body motion of the floater), you can use ElastoDyn output TTDspFA.
> 
> Best regards,
Hello, I have a question to ask. When only considering the deflection of the tower, is the TTDspFA calculated in Openfast strictly the displacement along xt in six degrees of freedom? What I mean is whether it includes the displacement of the tower top caused by the pitch motion of the tower top around the tower base. Because when I thought about it, I realized that if I only looked at the structure, does the tower top surge in strict six degrees of freedom not exist.
