### ISSUE TITLE
P and I Interpolation in ROSCO for the PI pitch controller?

### ISSUE THREAD

**Issue by QusayHawari** [OpenFAST/openfast#967]
Hello,

I am now performing turbulence cases on the IEA 15 MW UMaine model in the above rated region. 

I wanted to ask about the operation of the ROSCO controller in that case.

I can see from the DISCON.IN file that there are 28 gain scheduled parameters for the P and I for the PI pitch controller. I assume that in the above rated region those 28 values will be selected depending on the wind speed in the increments of 0.5m/s, because assuming pitching starts at 11m/s and ends at 25m/s, meaning we have 14*2 = 28 values for P and I?

- In the case of turbulence, is there any interpolation between those 28 values depending on the wind speed?

A semi-related question: 

- If I use a linearized state space model (linearized at 15m/s) and wanted to observe the outputs under turbulent wind, is there a way I can add the wind contribution in the Y and Z direction as inputs into the state space model? I can see that the horizontal direction is the only one. Or would you recommend I linearize the model using the .bts file as input wind instead of a steady wind? 

Thanks in Advance,
Qusay.

**Comment by jjonkman** [comment]
Dear @QusayHawari,

Perhaps someone from the ROSCO or IEA Wind 15-MW reference wind turbine teams can comment here, but it is probably better to ask questions related to those in their respective github sites:
ROSCO: https://github.com/NREL/ROSCO/issues
IEA Wind 15-MW reference wind turbine: https://github.com/IEAWindTask37/IEA-15-240-RWT/issues

Regarding linearization in OpenFAST, linearization is not possible with full-field turbulence (from TurbSim) enabled.  This is because a (periodic) steady-solution does not exist with full-field turbulence.  Instead, linearization requires the use of steady, uniform wind inflow (with shear).  In addition to the wind speed, the effect of wind direction and shear exponent are included as inputs in the linearized models.

Best regards,

**Comment by QusayHawari** [comment]
Hello,


Thank you for your reply.

I will ask on the ROSCO site. 

Yes, it made sense that linearization only works when all DOFs settle to their respective steady state. 


Thanks for your help.
